"""Map node icons: hand-painted fill rows (symmetric ones as a left half, mirrored), auto black outline.

Usage: python3 tools/sprites/map_icons.py   (writes src/art/mapIcons.ts and tools/out/map-icons.png at 8x)
"""
import os
import re
import struct
import zlib

ROOT = os.path.join(os.path.dirname(__file__), '..', '..')
LEGEND = {
    'K': 'black', 'W': 'white', 'L': 'lightGray', 'M': 'gray', 'A': 'slate',
    'G': 'gold', 'Y': 'yellow', 'O': 'orange', 'T': 'tan', 'B': 'brown', 'b': 'darkBrown',
    'R': 'red', 'r': 'darkRed', 'C': 'cyan',
}
# Right halves of mirrored icons are shaded one step darker.
MIRROR_SHADE = {'L': 'M', 'W': 'L'}


def mirror(half, shade=True):
    rows = []
    for row in half:
        right = ''.join(MIRROR_SHADE.get(c, c) if shade else c for c in reversed(row))
        rows.append(row + right)
    return rows


def blank(size):
    return [['.'] * size for _ in range(size)]


def outline(rows):
    size = len(rows)
    g = [list(r) for r in rows]
    for y in range(size):
        for x in range(size):
            if rows[y][x] != '.':
                continue
            for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1)):
                nx, ny = x + dx, y + dy
                if 0 <= nx < size and 0 <= ny < size and rows[ny][nx] not in '.K':
                    g[y][x] = 'K'
                    break
    return [''.join(r) for r in g]


SWORD = [
    '................',
    '.......W........',
    '.......WL.......',
    '.......WL.......',
    '.......WL.......',
    '.......WL.......',
    '.......WL.......',
    '.......WL.......',
    '.......WL.......',
    '.......WL.......',
    '....GGGGGGGG....',
    '.......BB.......',
    '.......BB.......',
    '.......bb.......',
    '......GGGG......',
    '................',
]

EPIC = mirror(shade=False, half=[
    '........',
    '.R......',
    '.RR.....',
    '..Rr..LW',
    '...rLWWW',
    '...LWWWW',
    '..LWWWWW',
    '..LWKKKW',
    '..LWKRKW',
    '..LWWWWK',
    '...LWWWW',
    '....WKWK',
    '....LWWW',
    '.....LLL',
    '........',
    '........',
])

EVENT = [
    '................',
    '.....YYYYY......',
    '....YYYYYYG.....',
    '...YYY...YYG....',
    '...YY.....YG....',
    '..........YG....',
    '.........YYG....',
    '........YYG.....',
    '.......YYG......',
    '.......YG.......',
    '.......YG.......',
    '................',
    '.......YG.......',
    '.......YG.......',
    '................',
    '................',
]

STORE = [
    '................',
    '.....TT..TT.....',
    '......TTTT......',
    '.......bb.......',
    '......TTTB......',
    '.....TTTTTB.....',
    '....TTTGGTTB....',
    '...TTTGTTTTBB...',
    '...TTTTGGTTBB...',
    '...TTTTTTGTBB...',
    '...TTTGGGTTBB...',
    '...TTTTGTTTBB...',
    '....TTTTTTBB....',
    '.....BBBBBB.....',
    '................',
    '................',
]

TREASURE = [
    '................',
    '................',
    '...TTTTTTTTTT...',
    '..TTTTTTTTTTTB..',
    '..BTTTTTTTTTBB..',
    '..GGGGGGGGGGGG..',
    '..BBBBBGGBBBBb..',
    '..BBBBBGYBBBBb..',
    '..BBBBBGGBBBBb..',
    '..BBBBBBBBBBBb..',
    '..BBBBBBBBBBBb..',
    '..GGGGGGGGGGGG..',
    '................',
    '................',
    '................',
    '................',
]

BOSS = mirror(shade=False, half=[
    '............',
    '...Y.......Y',
    '...GY.....GY',
    '...GGY...GGY',
    '...GGGGGGGGG',
    '...GGGRGGGGG',
    '...GGGGGGGGG',
    '..LWWWWWWWWW',
    '.LWWWWWWWWWW',
    '.LWWWWWWWWWW',
    '.LWWKKKKWWWW',
    '.LWKKRRKKWWW',
    '.LWKKRRKKWWW',
    '.LWWKKKKWWWW',
    '..LWWWWWWWKK',
    '..LLWWWWWWWK',
    '...LWWWWWWWW',
    '....WKWKWKWK',
    '....WKWKWKWK',
    '.....LWWWWWW',
    '......LLLLLL',
    '............',
    '............',
    '............',
])

ICONS = {
    'battle': SWORD,
    'epic': EPIC,
    'event': EVENT,
    'store': STORE,
    'treasure': TREASURE,
    'boss': BOSS,
}


def emit():
    out = ["import type { SpriteDef } from './sprite';", '', '// Generated by tools/sprites/map_icons.py.',
           'export const MAP_ICONS: Record<string, SpriteDef> = {']
    for name, rows in ICONS.items():
        rows = outline(rows)
        size = len(rows)
        assert all(len(r) == size for r in rows), name
        used = sorted(set(''.join(rows)) - {'.'})
        missing = set(used) - set(LEGEND)
        assert not missing, (name, missing)
        out.append(f'  {name}: {{')
        out.append(f'    width: {size},')
        out.append(f'    height: {size},')
        out.append('    legend: { ' + ', '.join(f"{k}: '{LEGEND[k]}'" for k in used) + ' },')
        out.append('    frames: {')
        out.append('      idle: [')
        out += [f"        '{r}'," for r in rows]
        out.append('      ],')
        out.append('    },')
        out.append('  },')
    out += ['};', '']
    open(os.path.join(ROOT, 'src', 'art', 'mapIcons.ts'), 'w').write('\n'.join(out))


def palette():
    src = open(os.path.join(ROOT, 'src', 'art', 'palette.ts')).read()
    return {k: tuple(int(v[i:i + 2], 16) for i in (1, 3, 5)) for k, v in re.findall(r"(\w+): '(#[0-9a-f]{6})'", src)}


def preview(scale=8):
    pal = palette()
    bg = (0x5a, 0x3a, 0x2f)
    cell = 24 * scale + 16
    w, h = cell * len(ICONS), cell
    px = [[bg] * w for _ in range(h)]
    for i, rows in enumerate(ICONS.values()):
        rows = outline(rows)
        for y, row in enumerate(rows):
            for x, c in enumerate(row):
                if c == '.':
                    continue
                for sy in range(scale):
                    for sx in range(scale):
                        px[8 + y * scale + sy][i * cell + 8 + x * scale + sx] = pal[LEGEND[c]]
    raw = b''.join(b'\x00' + bytes(v for p in row for v in p) for row in px)

    def chunk(t, d):
        return struct.pack('>I', len(d)) + t + d + struct.pack('>I', zlib.crc32(t + d) & 0xffffffff)
    png = b'\x89PNG\r\n\x1a\n' + chunk(b'IHDR', struct.pack('>IIBBBBB', w, h, 8, 2, 0, 0, 0)) + chunk(b'IDAT', zlib.compress(raw)) + chunk(b'IEND', b'')
    os.makedirs(os.path.join(ROOT, 'tools', 'out'), exist_ok=True)
    open(os.path.join(ROOT, 'tools', 'out', 'map-icons.png'), 'wb').write(png)


if __name__ == '__main__':
    emit()
    preview()
    print('ok')
