import type { EquipmentDef } from '../combat/types';

// Stat points: 1 ATK/MAG/DEF/RES = 1, 4 HP = 1. Common 8, Rare 14, Epic 20, Legendary 28 (+ enchantment).

const armor: EquipmentDef[] = [
  { id: 'leatherVest', name: 'Leather Vest', slot: 'armor', rarity: 'common', stats: { hp: 12, defense: 3, resistance: 2 } },
  { id: 'chainmail', name: 'Chainmail', slot: 'armor', rarity: 'common', requires: 'heavy', stats: { hp: 8, defense: 6 } },
  { id: 'clothRobe', name: 'Cloth Robe', slot: 'armor', rarity: 'common', stats: { magic: 3, resistance: 5 } },
  { id: 'paddedTunic', name: 'Padded Tunic', slot: 'armor', rarity: 'common', stats: { hp: 16, defense: 4 } },
  { id: 'scaleMail', name: 'Scale Mail', slot: 'armor', rarity: 'rare', requires: 'heavy', stats: { hp: 16, defense: 10 } },
  { id: 'studdedLeather', name: 'Studded Leather', slot: 'armor', rarity: 'rare', stats: { hp: 16, defense: 6, resistance: 4 } },
  { id: 'silkRobe', name: 'Silk Robe', slot: 'armor', rarity: 'rare', stats: { magic: 6, resistance: 8 } },
  {
    id: 'dragonscaleMail',
    name: 'Dragonscale Mail',
    slot: 'armor',
    rarity: 'epic',
    requires: 'heavy',
    stats: { hp: 16, defense: 12, resistance: 4 },
    enchantment: { kind: 'resist', element: 'fire', amount: 0.5 },
  },
  {
    id: 'shadowweaveRobe',
    name: 'Shadowweave Robe',
    slot: 'armor',
    rarity: 'epic',
    stats: { magic: 10, resistance: 10 },
    enchantment: { kind: 'resist', element: 'shadow', amount: 0.5 },
  },
  {
    id: 'thornmail',
    name: 'Thornmail',
    slot: 'armor',
    rarity: 'epic',
    requires: 'heavy',
    stats: { hp: 32, defense: 12 },
    enchantment: { kind: 'thorns', fraction: 0.3 },
  },
  {
    id: 'aegisPlate',
    name: 'Aegis Plate',
    slot: 'armor',
    rarity: 'legendary',
    requires: 'heavy',
    stats: { hp: 16, defense: 16, resistance: 8 },
    enchantment: { kind: 'onHitTaken', chance: 0.25, effect: { kind: 'barrier', stat: 'defense', scaling: 1, duration: 3 } },
  },
  {
    id: 'archmageVestments',
    name: 'Archmage Vestments',
    slot: 'armor',
    rarity: 'legendary',
    stats: { hp: 16, magic: 14, resistance: 10 },
    enchantment: { kind: 'onHitTaken', chance: 0.3, effect: { kind: 'barrier', stat: 'resistance', scaling: 1, duration: 3 } },
  },
];

const helmets: EquipmentDef[] = [
  { id: 'leatherCap', name: 'Leather Cap', slot: 'helmet', rarity: 'common', stats: { hp: 16, defense: 4 } },
  { id: 'ironHelm', name: 'Iron Helm', slot: 'helmet', rarity: 'common', requires: 'heavy', stats: { hp: 8, defense: 6 } },
  { id: 'wizardHat', name: 'Wizard Hat', slot: 'helmet', rarity: 'common', stats: { magic: 5, resistance: 3 } },
  { id: 'hood', name: 'Hood', slot: 'helmet', rarity: 'common', stats: { hp: 8, attack: 3, defense: 3 } },
  { id: 'greatHelm', name: 'Great Helm', slot: 'helmet', rarity: 'rare', requires: 'heavy', stats: { hp: 16, defense: 10 } },
  { id: 'circlet', name: 'Circlet', slot: 'helmet', rarity: 'rare', stats: { magic: 8, resistance: 6 } },
  { id: 'rangersHood', name: "Ranger's Hood", slot: 'helmet', rarity: 'rare', stats: { hp: 8, attack: 8, defense: 4 } },
  { id: 'tauntHelm', name: 'Taunt Helm', slot: 'helmet', rarity: 'epic', stats: { hp: 40, defense: 10 }, enchantment: { kind: 'taunt' } },
  {
    id: 'helmOfFrost',
    name: 'Helm of Frost',
    slot: 'helmet',
    rarity: 'epic',
    stats: { hp: 16, defense: 8, resistance: 8 },
    enchantment: { kind: 'resist', element: 'ice', amount: 0.5 },
  },
  {
    id: 'crownOfThorns',
    name: 'Crown of Thorns',
    slot: 'helmet',
    rarity: 'epic',
    stats: { hp: 16, attack: 10, defense: 6 },
    enchantment: { kind: 'thorns', fraction: 0.2 },
  },
  {
    id: 'lichCrown',
    name: 'Lich Crown',
    slot: 'helmet',
    rarity: 'legendary',
    stats: { hp: 16, magic: 16, resistance: 8 },
    enchantment: { kind: 'onAllyDeath', effect: { kind: 'buff', stat: 'magic', amount: 15, duration: 10 } },
  },
  {
    id: 'warlordsHelm',
    name: "Warlord's Helm",
    slot: 'helmet',
    rarity: 'legendary',
    requires: 'heavy',
    stats: { hp: 16, attack: 10, defense: 14 },
    enchantment: { kind: 'onAllyDeath', effect: { kind: 'buff', stat: 'attack', amount: 12, duration: 10 } },
  },
];

const boots: EquipmentDef[] = [
  { id: 'leatherBoots', name: 'Leather Boots', slot: 'boots', rarity: 'common', stats: { hp: 16, defense: 4 } },
  { id: 'ironBoots', name: 'Iron Boots', slot: 'boots', rarity: 'common', requires: 'heavy', stats: { hp: 8, defense: 6 } },
  { id: 'sandals', name: 'Sandals', slot: 'boots', rarity: 'common', stats: { hp: 16, resistance: 4 } },
  { id: 'softShoes', name: 'Soft Shoes', slot: 'boots', rarity: 'common', stats: { hp: 8, attack: 4, defense: 2 } },
  { id: 'greaves', name: 'Greaves', slot: 'boots', rarity: 'rare', requires: 'heavy', stats: { hp: 16, defense: 10 } },
  { id: 'elvenBoots', name: 'Elven Boots', slot: 'boots', rarity: 'rare', stats: { attack: 6, defense: 4, resistance: 4 } },
  { id: 'mageSlippers', name: 'Mage Slippers', slot: 'boots', rarity: 'rare', stats: { magic: 6, resistance: 8 } },
  {
    id: 'bootsOfWarding',
    name: 'Boots of Warding',
    slot: 'boots',
    rarity: 'epic',
    stats: { hp: 16, defense: 8, resistance: 8 },
    enchantment: { kind: 'resist', element: 'lightning', amount: 0.5 },
  },
  { id: 'spikedBoots', name: 'Spiked Boots', slot: 'boots', rarity: 'epic', stats: { hp: 40, defense: 10 }, enchantment: { kind: 'thorns', fraction: 0.25 } },
  {
    id: 'treadsOfVenom',
    name: 'Treads of Venom',
    slot: 'boots',
    rarity: 'epic',
    stats: { hp: 16, attack: 10, defense: 6 },
    enchantment: { kind: 'resist', element: 'poison', amount: 0.6 },
  },
  {
    id: 'stormwalkers',
    name: 'Stormwalkers',
    slot: 'boots',
    rarity: 'legendary',
    stats: { hp: 32, attack: 12, defense: 8 },
    enchantment: {
      kind: 'onHit',
      chance: 0.2,
      effect: { kind: 'damage', damageType: 'magic', stat: 'attack', scaling: 0.5, element: 'lightning' },
    },
  },
  {
    id: 'colossusSabatons',
    name: 'Colossus Sabatons',
    slot: 'boots',
    rarity: 'legendary',
    requires: 'heavy',
    stats: { hp: 16, defense: 16, resistance: 8 },
    enchantment: { kind: 'onHitTaken', chance: 0.2, effect: { kind: 'barrier', stat: 'defense', scaling: 1, duration: 3 } },
  },
];

const weapons: EquipmentDef[] = [
  { id: 'shortSword', name: 'Short Sword', slot: 'weapon', rarity: 'common', requires: 'martial', stats: { attack: 8 } },
  { id: 'handAxe', name: 'Hand Axe', slot: 'weapon', rarity: 'common', requires: 'martial', stats: { hp: 8, attack: 6 } },
  { id: 'oakStaff', name: 'Oak Staff', slot: 'weapon', rarity: 'common', requires: 'caster', stats: { magic: 8 } },
  { id: 'shortBow', name: 'Short Bow', slot: 'weapon', rarity: 'common', requires: 'ranged', stats: { attack: 8 } },
  { id: 'longsword', name: 'Longsword', slot: 'weapon', rarity: 'rare', requires: 'martial', stats: { attack: 14 } },
  { id: 'wandOfSparks', name: 'Wand of Sparks', slot: 'weapon', rarity: 'rare', requires: 'caster', stats: { magic: 12, resistance: 2 } },
  { id: 'longbow', name: 'Longbow', slot: 'weapon', rarity: 'rare', requires: 'ranged', stats: { attack: 14 } },
  {
    id: 'flametongue',
    name: 'Flametongue',
    slot: 'weapon',
    rarity: 'epic',
    requires: 'martial',
    stats: { attack: 20 },
    enchantment: { kind: 'onHit', chance: 0.3, effect: { kind: 'dot', stat: 'attack', scaling: 0.3, duration: 3, element: 'fire' } },
  },
  {
    id: 'staffOfFrost',
    name: 'Staff of Frost',
    slot: 'weapon',
    rarity: 'epic',
    requires: 'caster',
    stats: { magic: 20 },
    enchantment: { kind: 'onHit', chance: 0.3, effect: { kind: 'debuff', stat: 'attack', amount: 5, duration: 4 } },
  },
  {
    id: 'venomBow',
    name: 'Venom Bow',
    slot: 'weapon',
    rarity: 'epic',
    requires: 'ranged',
    stats: { attack: 20 },
    enchantment: { kind: 'onHit', chance: 0.4, effect: { kind: 'dot', stat: 'attack', scaling: 0.25, duration: 4, element: 'poison' } },
  },
  {
    id: 'doombringer',
    name: 'Doombringer',
    slot: 'weapon',
    rarity: 'legendary',
    requires: 'martial',
    stats: { attack: 28 },
    enchantment: {
      kind: 'onHit',
      chance: 0.25,
      effect: { kind: 'damage', damageType: 'physical', stat: 'attack', scaling: 0.6, element: 'shadow', drain: 0.5 },
    },
  },
  {
    id: 'staffOfAges',
    name: 'Staff of Ages',
    slot: 'weapon',
    rarity: 'legendary',
    requires: 'caster',
    stats: { magic: 28 },
    enchantment: { kind: 'onHit', chance: 0.2, effect: { kind: 'debuff', stat: 'resistance', amount: 8, duration: 5 } },
  },
];

const jewelry: EquipmentDef[] = [
  { id: 'copperRing', name: 'Copper Ring', slot: 'jewelry', rarity: 'common', stats: { attack: 4, magic: 4 } },
  { id: 'amuletOfHealth', name: 'Amulet of Health', slot: 'jewelry', rarity: 'common', stats: { hp: 32 } },
  { id: 'ironBand', name: 'Iron Band', slot: 'jewelry', rarity: 'common', stats: { defense: 4, resistance: 4 } },
  { id: 'luckyCharm', name: 'Lucky Charm', slot: 'jewelry', rarity: 'common', stats: { hp: 8, attack: 3, magic: 3 } },
  { id: 'silverRing', name: 'Silver Ring', slot: 'jewelry', rarity: 'rare', stats: { attack: 7, magic: 7 } },
  { id: 'pendantOfVigor', name: 'Pendant of Vigor', slot: 'jewelry', rarity: 'rare', stats: { hp: 40, defense: 4 } },
  { id: 'wardStone', name: 'Ward Stone', slot: 'jewelry', rarity: 'rare', stats: { defense: 7, resistance: 7 } },
  {
    id: 'emberwardRing',
    name: 'Emberward Ring',
    slot: 'jewelry',
    rarity: 'epic',
    stats: { hp: 40, resistance: 10 },
    enchantment: { kind: 'resist', element: 'fire', amount: 0.6 },
  },
  {
    id: 'holySymbol',
    name: 'Holy Symbol',
    slot: 'jewelry',
    rarity: 'epic',
    stats: { magic: 12, resistance: 8 },
    enchantment: { kind: 'resist', element: 'shadow', amount: 0.5 },
  },
  {
    id: 'vampireFang',
    name: 'Vampire Fang',
    slot: 'jewelry',
    rarity: 'epic',
    stats: { hp: 32, attack: 12 },
    enchantment: {
      kind: 'onHit',
      chance: 0.25,
      effect: { kind: 'damage', damageType: 'physical', stat: 'attack', scaling: 0.3, drain: 1 },
    },
  },
  {
    id: 'heartOfTheMountain',
    name: 'Heart of the Mountain',
    slot: 'jewelry',
    rarity: 'legendary',
    stats: { hp: 32, defense: 12, resistance: 8 },
    enchantment: { kind: 'onHitTaken', chance: 0.25, effect: { kind: 'barrier', stat: 'defense', scaling: 1, duration: 3 } },
  },
  {
    id: 'eyeOfTheStorm',
    name: 'Eye of the Storm',
    slot: 'jewelry',
    rarity: 'legendary',
    stats: { hp: 32, attack: 10, magic: 10 },
    enchantment: {
      kind: 'onHit',
      chance: 0.25,
      effect: { kind: 'damage', damageType: 'magic', stat: 'magic', scaling: 0.5, element: 'lightning' },
    },
  },
];

export const ITEM_LIBRARY: EquipmentDef[] = [...armor, ...helmets, ...boots, ...weapons, ...jewelry];

export const ITEMS_BY_ID: Record<string, EquipmentDef> = Object.fromEntries(ITEM_LIBRARY.map((i) => [i.id, i]));
