import type { SpriteDef } from '../sprite';

export const ABOMINATION_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    L: 'lightGray',
    M: 'gray',
    n: 'night',
    G: 'green',
    g: 'midGreen',
    d: 'darkGreen',
    Y: 'yellow',
    O: 'orangeBrown',
    R: 'rust',
    r: 'darkBrown',
    b: 'deepBrown',
    P: 'skin',
    p: 'skinShade',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '...............KKKKKKK..........',
      '..............KLLLLLLLK.........',
      '.............KLLLLLnMMMK........',
      '.......KKKK.KLLLLMnnnMMMKKK.....',
      '......KLLLnKLLLMMMMnMMMggLMK....',
      '.....KLLLLnMLMMMMMMngggggMMMK...',
      '.....KLYLMngMMMMMMnnnggggMMggK..',
      '.....KLMMMggKMMggggnggggMMgggK..',
      '......KnnggKKKgggggngggMMggggK..',
      '.......KKKKLPpLLLgggggKLMMMMgK..',
      '........KLLnnpLLLMMKKKKLMMMMgK..',
      '.......KLPpppLMMMMMMK.KLMMGdgK..',
      '......KLPpppMMMMMMMMMKKLMMddgK..',
      '.....KKPppLMnMMnMMnMgKKLMMMMgK..',
      '....KPPPpnnnnnnnnnngggKLMMMMgK..',
      '....KpppMnMMnMMnggngggKLMMMMgK..',
      '.....KOMMMMMMMMgGddggKKLLLLMgK..',
      '.....KrMMMMMMgggdddggKKnLMMMMK..',
      '....KOOKMMgggggggGggKKLLMMMMggK.',
      '.K..KORRRRRRRRRRRRRRbKMnMMggggK.',
      'KOK.KORKrrrrrrrrrrrrbKKggggggK..',
      'KORKKORKKLRrrbKKLMMdK..KddddK...',
      'KORRKORrKLRrrbKKLMMdK...KKGK....',
      '.KRRRRrKKLrrrbKKLMMdK....KGK....',
      '..KrrrK.KLMMdK.KLMMdK.....K.....',
      '...KGK..KLMMdK.KLMMdK...........',
      '....K..KggggdKKggggdK...........',
      '........KKKKK..KKKKK............',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '...............KKKKKKK..........',
      '..............KLLLLLLLK.........',
      '.............KLLLLLnMMMK........',
      '.......KKKK.KLLLLMnnnMMMKKK.....',
      '......KLLLnKLLLMMMMnMMMggLMK....',
      '.K...KLLLLnMLMMMMMMngggggMMMK...',
      'KOK..KLYLMngMMMMMMnnnggggMMggK..',
      'KORK.KLMMMggKMMggggnggggMMgggK..',
      'KORKKKKnnggKKKgggggngggMMggggK..',
      'KORROOOOrPPLLLLLLgggggKLMMMMgK..',
      '.KrrrrRrOPPPnPLLLMMKKKKLMMMMgK..',
      '..KgKKKKLPppnpMMMMMMK.KLMMGdgK..',
      '.KGK..KLLLLLMMMMMMMMMKKLMMddgK..',
      '..K...KLLnLMnMMnMMnMgKKLMMMMgK..',
      '.....KLLnnnnnnnnnnngggKLMMMMgK..',
      '.....KLMMnMMnMMnggngggKLMMMMgK..',
      '......KMMMMMMMMgGddggKKLLLLMgK..',
      '......KMMMMMMgggdddggKKnLMMMMK..',
      '.......KMMgggggggGggKKLLMMMMggK.',
      '......KRRRRRRRRRRRRRbKMnMMggggK.',
      '.......KrrrrrrrrrrrrbKKggggggK..',
      '........KLRrrbKKLMMdK..KddddK...',
      '........KLRrrbKKLMMdK...KKGK....',
      '........KLrrrbKKLMMdK....KGK....',
      '........KLMMdK.KLMMdK.....K.....',
      '........KLMMdK.KLMMdK...........',
      '.......KggggdKKggggdK...........',
      '........KKKKK..KKKKK............',
      '................................',
    ],
  },
};
