import type { SpriteDef } from '../sprite';

export const BANDIT_KING_SPRITE: SpriteDef = {
  width: 48,
  height: 48,
  legend: {
    K: 'black',
    D: 'darkGreen',
    d: 'deepTeal',
    m: 'midGreen',
    g: 'green',
    S: 'skin',
    s: 'skinShade',
    R: 'red',
    r: 'darkRed',
    B: 'brown',
    b: 'darkBrown',
    e: 'deepBrown',
    Y: 'yellow',
    o: 'gold',
    x: 'orangeBrown',
    L: 'lightGray',
    W: 'white',
    M: 'gray',
    n: 'night',
  },
  frames: {
    idle: [
      '...............................KKK..............',
      '..................KKKKKKKKKKKKKRRRKKKK..........',
      '.................KbbbbbbbbbbRRRWWWWWRRKK........',
      '................KbBBbbbbbbbbWWWRRRRRWWRRK.......',
      '...............KbBbbbbbbbbbebRRRrrrrrRRRRK......',
      '...............KBbbbbbbbbbbberrrKKKKRrrrRK......',
      '..............KbYYYYWRYYYYYYooKK....KKRrRK......',
      '..............KbooooRRoooooooxKKK.....KKrRK.....',
      '.........KKKKKKbbbbbbbbbbbbbbebbbK......KrK.....',
      '........KeebbbbbbbbbbbeeeeeeeeeeeeK....K.K......',
      '.........KeeeeeeeeeeeeeeeeeeeeeeKK....KgK.......',
      '..........KKKDDssssssssssDddddKK......KgmK......',
      '............KmDeesSSseesDDddddK.......KgmK......',
      '...........KDmSSKSSSSKSSsDdddddK......KLMK......',
      '...........KDmSSSSSSSSSSsDdddddK......KLMK......',
      '...........KmDRWRRRRRRRRRDdddddK......KLMK......',
      '...........KmDRRRRRRRRrrrDDddddK......KLMK......',
      '...........KmDRRRRRRRRRRRDDddddKK....KSSSK......',
      '..........KDmDDRRRRRrrrrrDDdddddLK...KSSSK......',
      '.........KLDDDDDRRrrrrRDDDDdddddLLK..KSSsK......',
      '........KLLDDDDWLLLWLLLWLLLWLLLLLLLKKDLWLWK.....',
      '.........KLDDDDLLLMLLLMLLLMLLLMLLMMKKDLLLLK.....',
      '.........KDmDDDLLoMLLBMLLbMLLMMLLMdddDmDDK......',
      '........KDmDDDDWLBoBBBBBBbobLMdddddddDmDK.......',
      '........KDmDDDDWLBBoBBBBBobbLMdddddddDmDK.......',
      '.......KDmDDDDDWLxxxoYooobbbLMddddddDmDDK.......',
      '......KDDmDDDDDWLbbbboRobbbbLMddddddDmDDK.......',
      '......KDmDDDDDDWLBBBBoooBbbbLMddddddDmDDK.......',
      '......KDmDDDDDDWLxxxxxxxxbbbLMdddddKKDDK........',
      '.....KWLWLLDDDDWLbbbbbbbbbbbLMdddddK.KK.........',
      '.....KSLLLLDDDDWLBBBYYYYBbbbLMddddddK...........',
      '....KSSSDDDDDDYYYYYYYxxYYYYYYYYdddddK...........',
      '...KoSSsDmDDDDooooooYxxYooRRRoodddddK...........',
      '...KMYSDDmDDDDDWLBbbYYYYbbRRrLMdddddK...........',
      '..KmWooDDmDDDDDWLBbbbbbbbbRRrLMddddddK..........',
      '.KmgKKKKmDDDDDWLDBbbbbbbbbBRRrLMdddddK..........',
      '.KgK...KmDDDDDWLbBbbbbbbbbBRRrLMdddddK..........',
      '..K...KDmDDDDDWLbBbbbnnbbbbBRrLMdddddK..........',
      '......KDmDDDDWLDbBbbbnnbbbbBbDDLMdddddK.........',
      '......KDmDDDDWLDbBbbbnnbbbbBbDDLMdddddK.........',
      '......KmDDDDDWLxxxxxxxnnxxxxxxxLMdddddK.........',
      '......KmDDDDDWLbbbbbbDDDbbbbbbDLMdddddK.........',
      '.....KDmDDDDWLDeeeeeeDDDeeeeeeDdLMdddddK........',
      '.....KDDDDDDWLeeeeeeeDDeeeeeeeDdLMdddddK........',
      '......KKKKKKWLbeeeeeeeebeeeeeeKKWLKKKKK.........',
      '...........KMLeeeeeeeeeeeeeeeeKKLMK.............',
      '............KKKKKKKKKKKKKKKKKK..KK..............',
      '................................................',
    ],
    attack: [
      '................................................',
      '................................................',
      '.................................KKK............',
      '....................KKKKKKKKKKKKKRRRKKKK........',
      '...................KbbbbbbbbbbRRRWWWWWRRKK......',
      '..................KbBBbbbbbbbbWWWRRRRRWWRRK.....',
      '..........KKK....KbBbbbbbbbbbebRRRrrrrrRRRRK....',
      '......KKKKLLLK...KBbbbbbbbbbbberrrKKKKRrrrRK....',
      '.....KWWLLKKK...KbYYYYWRYYYYYYooKK....KKRrRK....',
      '...KKWWWKK......KbooooRRoooooooxKKK.....KKrRK...',
      '..KWWWKK...KKKKKKbbbbbbbbbbbbbbebbbK......KrK...',
      '.KWWWK....KeebbbbbbbbbbbeeeeeeeeeeeeK......K....',
      'KWWWK......KeeeeeeeeeeeeeeeeeeeeeeKK............',
      'KWWK........KKKDDssssssssssDddddKK..............',
      'KWWK..........KmDeesSSseesDDddddK...............',
      'KWK..........KDmSSKSSSSKSSsDdddddK..............',
      'KWK..........KDmSSSSSSSSSSsDdddddK..............',
      'KgKK.........KmDRWRRRRRRRRRDdddddK.KK...........',
      '.KgmK........KmDRRRRRRRRrrrDDddddKKLLK..........',
      '..KgmKK......KmDRRRRRRRRRRRDDddddLLLLLK.........',
      '...KWMoKKKKKKDDDDDRRRRrrrrrDDdddddLLLLLK........',
      '...KYYSSWLmmmmmmmmDRrrrrRDDDDdddddMLLMMK........',
      '...KoSSSLWDDDDDDDDDLLoMLLBMLLbMLLMMLLMK.........',
      '....KSSsLLDDDDDDDDDWLBoBBBBBBbobLMddddK.........',
      '.....KKKLLDDDDDmDDDWLBBoBBBBBobbLMddddK.........',
      '........KKKKKDmDDDDWLxxxoYooobbbLMddddK.........',
      '............KDmDDDDWLbbbboRobbbbLMdddddK........',
      '.........KKKDDmDDDDWLBBBBoooBbbbLMdddddK........',
      '......KKKdDDDmDDDDDWLxxxxxxxxbbbLMdddddK........',
      '.....KSSSWLdDmDDDDDWLbbbbbbbbbbbLMdddddK........',
      '.....KSSSLLDmDDDDDDWLBBBYYYYBbbbLMddddddK.......',
      '....KYSSsLLDmDDDDDYYYYYYYxxYYYYYYYYdddddK.......',
      '...KWMoKKKDDmDDDDDooooooYxxYooRRRoodddddK.......',
      '..KgmKK..KDmDDDDDDDWLBbbYYYYbbRRrLMdddddK.......',
      '.KgmK....KDmDDDDDDWLbBbbbbbbbbRRrLMddddddK......',
      'KgKK.....KDmDDDDDDWLBbbbbbbbbbBRRrLMdddddK......',
      'KWK.....KDmDDDDDDWLbBbbbbbbbbbBRRrLMdddddK......',
      'KWWK....KDmDDDDDDWLBbbbbbnnbbbbBRrLMdddddK......',
      'KWWK....KmDDDDDDWLbBbbbbbnnbbbbBbDDLMdddddK.....',
      'KWWWK..KDmDDDDDWLDBbbbbbbnnbbbbBbDDLMdddddK.....',
      '.KWWWKKKDmDDDDDWLxxxxxxbbnnnxxxxxxxLMdddddK.....',
      '..KWWWWmmDDDDDWLbbbbbbDDDDDDbbbbbbDLMdddddK.....',
      '...KKWWDmDDDDDWLeeeeeeDDDDDDeeeeeeDdLMdddddK....',
      '.....KKDDDDDDWLeeeeeeeDDDDDeeeeeeeDdLMdddddK....',
      '.......KKKKKKWLbeeeeeeKKKKebeeeeeeKKLWKKKKK.....',
      '............KMLeeeeeeeK..KeeeeeeeeKKLMK.........',
      '.............KKKKKKKKK....KKKKKKKK..KK..........',
      '................................................',
    ],
  },
};
