import type { SpriteDef } from '../sprite';

export const BANDIT_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    D: 'darkGreen',
    d: 'deepTeal',
    S: 'skin',
    s: 'skinShade',
    K: 'black',
    R: 'red',
    r: 'darkRed',
    B: 'brown',
    b: 'darkBrown',
    e: 'deepBrown',
    G: 'gold',
    L: 'lightGray',
    M: 'gray',
    g: 'green',
    m: 'midGreen',
    n: 'night',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '............KKKK................',
      '..........KKDDDDK...............',
      '.........KDDDDDDdK..............',
      '........KDDDDDDDddK.............',
      '.......KDDDDDDDDdddK............',
      '.......KDDnnnnDDdddK............',
      '.......KDSKSSKsDdddK............',
      '.......KDSSSSSsDddddK...........',
      '.......KRRRRRRrrDdddK...........',
      '.......KRRRRRrrrddddK...........',
      '.......KKrRRrrrDDddddK..........',
      '......KDDBBBBBBBbDDdddK.........',
      '.....KDDBBBBBBBBbbDdddK.........',
      '..KKKKDDDBBBBBBBbbDddddK........',
      '.KLLLGSSDBbBBBBbbbDddddK........',
      'KgMMMGssDBbBBBBbbbbDdddK........',
      'KgmKKKKKDeeeGeeeeebDdddK........',
      '.KK....KDBBBBBBbbbbDddddK.......',
      '.......KDBBBBbBBbbbDddddK.......',
      '........KbBBBbBBbbDdddddK.......',
      '........KbBBbKbBbbDddddK........',
      '........KbBBbKKbBbbKKKK.........',
      '........KbBBbKKbBbbK............',
      '........KbBBbKKbBbbK............',
      '........KeeebKKeeebK............',
      '.......KeeeebKeeeebK............',
      '........KKKKK.KKKKK.............',
      '................................',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '...........KKKK.................',
      '.........KKDDDDK................',
      '........KDDDDDDdK...............',
      '.......KDDDDDDDddK..............',
      '......KDDDDDDDDdddK.............',
      '......KDDnnnnDDdddK.............',
      '......KDSKSSKsDdddK.............',
      '......KDSSSSSsDddddK............',
      '......KRRRRRRrrDdddK............',
      '......KRRRRRrrrddddK............',
      '..KKKKKKrRRrrrDDddddKK..........',
      '.KLLLGSSSDBBBBBBbDDdddK.........',
      'KgMMMGssDBBBBBBBBbbDdddK........',
      'KgmKKKKKDDBBBBBBBbbDddddK.......',
      '.KK.....KDBbBBBBbbbDddddK.......',
      '........KDBbBBBBbbbbDdddK.......',
      '........KDeeeGeeeeebDdddK.......',
      '........KDBBBBBBbbbbDddddK......',
      '........KDBBBBbBBbbbDddddK......',
      '........KbBBBbBBbbDdddddK.......',
      '.......KbBBbKKbBbbDddddK........',
      '......KbBBbK..KbBbbKKKK.........',
      '.....KbBBbK....KbBbbK...........',
      '.....KbBBbK....KbBbbK...........',
      '....KeeebK.....KeeebK...........',
      '...KeeeebK.....KeeeebK..........',
      '....KKKKK.......KKKKK...........',
      '................................',
      '................................',
    ],
  },
};
