import type { SpriteDef } from '../sprite';

export const BANSHEE_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    A: 'slate',
    W: 'white',
    L: 'lightGray',
    G: 'gray',
    C: 'cyan',
    B: 'blue',
    N: 'navy',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '.........KKKKKKKKKKK............',
      '........KLLLLLLLLLLLKKKK........',
      '.......KLGGGGGGGGGGGLLLLKKKK....',
      '......KLGGGGGGGGGGGGGGGGLLLLK...',
      '......KLWWWWGAAAAAAAAAAAAAAK....',
      '......KWKWKWLGLLLLLLLLLKKKK.....',
      '......KWKWKWLGGGGGGGGGGLLLLKK...',
      '......KWWWWWLGGGGGGGGGGGGGGLLK..',
      '.......KWKWLLGAAAAAAAAAAAAAAK...',
      '........KLLKGLLLLLLLLKKKKKKK....',
      '......KKWCCCBGGGGGGGGLLK........',
      '....KKWWWCCCBGGGGGGGGGLK........',
      '...KWWLLWCCCBAAAAGGGGGGLK.......',
      '..KWLLKKWCCCBKKKKKAAAGGGLK......',
      '.KWLKK..KWCCBK....KKAAAGLK......',
      '..KK....KWCCCBK.....KKKALK......',
      '........KWCCCBBK.......KK.......',
      '........KWCCBCCBK...............',
      '.......KWCCCBCCBBK..............',
      '.......KWCCCBCCCBBK.............',
      '.......KWCCBCCCBCBBK............',
      '.......KWCCBCCCCBCBBK...........',
      '.......KWCCBCCCCCBCBBKKK........',
      '.......KCBBBBBBBBBBBBBNNKK......',
      '.......KBBNNBBBBNNNNNNNNNNK.....',
      '.......KBNKKNNNNNKNNNNNNNNNK....',
      '.......KNK..KNNNK.KNNNKKNNNNK...',
      '........K....KNK...KNK..KKKK....',
      '..............K.....K...........',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '...........KKKKKKKKKKKKK........',
      '..........KLLLLLLLLLLLLLKKKK....',
      '.....K...KLGGGGGGGGGGGGLLLLLKK..',
      '....KCK.KLGGGGGGGGGGGGGGGGGGLLK.',
      '...KCCK.KLWWWWGAAAAAAAAAAAAAAK..',
      '...KCCKKKWKWKWLGLLLLLLLLLLLKK...',
      '..KCCKKWWWKWKWLGGGGGGGGGGGGLLK..',
      '..KCCKWWKWWWWLLGGGGGGGGGGGGGGLK.',
      '..KCKKWKKWKKWLLGAAAAAAAAAAAAKK..',
      '..KCKKWKKWKKLKGLLLLLLLLLLLKKKK..',
      '..KCKKWK.KWLKGGGGGGGGGGGGGGGLLK.',
      '..KCCKWWKKWCCCBWWWAAAAAAAAAAKK..',
      '..KCCKKWWKWCCCBLLWWWKKKKKKKK....',
      '...KCCKKKKWCCCBKKLLWWWK.........',
      '...KCCK...KWCCBK.KKLLWLK........',
      '....KCK...KWCCCBK..KKKK.........',
      '.....K....KWCCCBBK..............',
      '..........KWCCBCCBK.............',
      '.........KWCCCBCCBBK............',
      '.........KWCCCBCCCBBK...........',
      '.........KWCCBCCCBCBBK..........',
      '.........KWCCBCCCCBCBBK.........',
      '.........KWCCBCCCCCBCBBKKK......',
      '.........KCBBBBBBBBBBBBBNNKK....',
      '.........KBBNNBBBBNNNNNNNNNNK...',
      '.........KBNKKNNNNNKNNNNNNNNNK..',
      '.........KNK..KNNNK.KNNNKKNNNNK.',
      '..........K....KNK...KNK..KKKK..',
      '................K.....K.........',
      '................................',
    ],
  },
};
