import type { SpriteDef } from '../sprite';

export const BARBARIAN_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    E: 'sand',
    S: 'skin',
    s: 'skinShade',
    O: 'orange',
    R: 'rust',
    F: 'tan',
    f: 'brown',
    B: 'darkBrown',
    b: 'darkBrown',
    d: 'deepBrown',
    Y: 'gold',
    W: 'white',
    L: 'lightGray',
    M: 'gray',
  },
  frames: {
    idle: [
      '................................',
      '.............KK.................',
      '............KOOK................',
      '...........KKOOKKK..............',
      '..........KESOOSSsK.............',
      '..........KESSSSSsK.............',
      '..........KSSSSbbSK.KKKKK.......',
      '..........KSsSSKSSSKWLBLMK......',
      '..........KSSSOOOORKWLBLMK......',
      '..........KSSOOOORRKWLBLMK......',
      '...........KOOORRRKKWLBLMK......',
      '............KOORRK..KLBLK.......',
      '.......KKKKKKsSsKKKKKKBK........',
      '......KFFfBESSSSSsSsKKBK........',
      '......KFffBEssSsssSsKKBK........',
      '.......KBBKESSSSSsSsKKbK........',
      '.......KSsKESsSsSsSsKKBK........',
      '.......KSsKESSSSSsSSSSBS........',
      '.......KSsKEsSSSssSsssBs........',
      '.......KSSKbbbYbbbdK.KbK........',
      '.......KKKKFfffFfBBK..K.........',
      '.........KfffBffBBK.............',
      '.........KfBfKfBfBK.............',
      '..........KSsKKSsK..............',
      '..........KSsKKSsK..............',
      '..........KEsKKEsK..............',
      '..........KSsKKSsK..............',
      '..........KFfKKFfK..............',
      '..........KfBKKfBK..............',
      '..........KfBBKfBBK.............',
      '..........KKKKKKKKK.............',
      '................................',
    ],
    attack: [
      '................................',
      '.............KK.................',
      '............KOOK................',
      '...........KKOOKKK..............',
      '..........KESOOSSsK.............',
      '..........KESSSSSsK.............',
      '..........KSSSSbbSK.............',
      '..........KSsSSKSSSK............',
      '..........KSSSOOOORK............',
      '..........KSSOOOORRK............',
      '...........KOOORRRK.............',
      '............KOORRK..............',
      '.......KKKKKKsSsKKKKK.......KKKK',
      '......KFFfBESSSSSsSsK......KWWWW',
      '......KFffBEssSsssSsSKKKKKKLLLLL',
      '.......KBBKESSSSSsSbBBBbBBBBBBBB',
      '.......KSsKESsSsSsSssKKKKKKLLLLL',
      '.......KSsKESSSSSsK........KMMMM',
      '.......KSsKEsSSSssK.........KKKK',
      '.......KSSKbbbYbbbdK............',
      '.......KKKKFfffFfBBK............',
      '.........KfffBffBBK.............',
      '.........KfBfKfBfBK.............',
      '..........KSsKKSsK..............',
      '..........KSsKKSsK..............',
      '..........KEsKKEsK..............',
      '..........KSsKKSsK..............',
      '..........KFfKKFfK..............',
      '..........KfBKKfBK..............',
      '..........KfBBKfBBK.............',
      '..........KKKKKKKKK.............',
      '................................',
    ],
  },
};
