import type { SpriteDef } from '../sprite';

export const BARD_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    R: 'red',
    C: 'cyan',
    U: 'blue',
    N: 'navy',
    B: 'darkBrown',
    S: 'skin',
    s: 'skinShade',
    Y: 'gold',
    b: 'darkBrown',
    p: 'deepBrown',
    F: 'tan',
    f: 'brown',
  },
  frames: {
    idle: [
      '................................',
      '......KK........................',
      '.....KRRK.KKKKKK................',
      '......KRRKCUUUUUNK..............',
      '.......KKUUUUUUUUNK.............',
      '........KNNBSSSSsK..............',
      '.........KBSSSKSsK..............',
      '.........KBSSSSSSSK.............',
      '.........KBSSSSSsKK.............',
      '..........KBSSSsKbbK............',
      '...........KSSsKbBK.............',
      '........KKYYYYYbBYSS............',
      '........KCUUUUbBNNKK............',
      '........KFFFUbBNNNKSK...........',
      '.......KFFFFbBUUNNK.............',
      '......KFFFUFFUUNNNK.............',
      '......KFFFSSfUUNNNK.............',
      '.......KFFFfUUUUNNK.............',
      '........KFfbbYbbbbK.............',
      '.........KCUUUUUNNK.............',
      '.........KCUUUUNNNK.............',
      '.........KNNNNNNNNK.............',
      '..........KpbKKpbK..............',
      '................................',
      '..........KpbKKpbK..............',
      '..........KBbKKBbK..............',
      '..........KpbKKpbK..............',
      '..........KbBKKbBK..............',
      '..........KbBKKbBK..............',
      '..........KbBBKbBBK.............',
      '..........KKKKKKKKK.............',
      '................................',
    ],
    attack: [
      '................................',
      '......KK........................',
      '.....KRRK.KKKKKK................',
      '......KRRKCUUUUUNK..............',
      '.......KKUUUUUUUUNK.............',
      '........KNNBSSSSsK..............',
      '.........KBSSSKSsK..............',
      '.........KBSSSSSSSK.............',
      '.........KBSSSSSsKK.............',
      '..........KBSSSsKbbK............',
      '...........KSSsKbBK.............',
      '........KKYYYYYbBYK.............',
      '........KCUUUUbBNNKKKKKKK.......',
      '........KFFFUbBNNNUUUSSK........',
      '.......KFFFFbBUUNNNNNssK........',
      '......KFFFUFFUUNNNKKKKKK........',
      '......KFFFSSfUUNNNK.............',
      '.......KFFFfUUUUNNK.............',
      '........KFfbbYbbbbK.............',
      '.........KCUUUUUNNK.............',
      '.........KCUUUUNNNK.............',
      '.........KNNNNNNNNK.............',
      '..........KpbKKpbK..............',
      '................................',
      '..........KpbKKpbK..............',
      '..........KBbKKBbK..............',
      '..........KpbKKpbK..............',
      '..........KbBKKbBK..............',
      '..........KbBKKbBK..............',
      '..........KbBBKbBBK.............',
      '..........KKKKKKKKK.............',
      '................................',
    ],
  },
};
