import type { SpriteDef } from '../sprite';

export const BEAR_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    T: 'tan',
    B: 'brown',
    b: 'darkBrown',
    d: 'deepBrown',
    W: 'white',
    R: 'darkRed',
    E: 'sand',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '....................KK..........',
      '..............KKK..KbbK.........',
      '...........KKKTTTKKbTTbK........',
      '........KKKTTTTBBTTbBBBBKK......',
      '......KKTTTBBBBBBBBTBBBBBBK.....',
      '.....KTTBBBBBBBBBBBBTBBBKBBKK...',
      '....KTBBBBBBBBBBBBBBBTBBBBBEEK..',
      '...KTBBBBBBBBBBBBBBBBBBBBBEEEEK.',
      '...KTBBBBBBBBBBBBBBBBBBBBbEEEEK.',
      '...KBBBBBBBBBBBBBBBBBBBBbbbbbK..',
      '...KBBBBBBBBBBBBBBBBBBBBbbbKK...',
      '...KBBBBBBBBBBBBBBBBBBBbbbbK....',
      '...KbBBBBBBBBBBBBBBBBBbbbbbK....',
      '...KbbBBBBBBBBBBBBBBBbbbbbbK....',
      '...KbbbbBBBBBBBBBBBbbbbbbbbK....',
      '...KbbbbbbbbbbbbbbbbbbbbbbbK....',
      '...KbBBBbKKKKKKKKKbBBBBbbbK.....',
      '...KbBBBbK.......KbBBBBbbK......',
      '...KbBBBbK.......KbBBBBbK.......',
      '...KbBBBbK.......KbBBBBbK.......',
      '...KbBBBbK.......KbBBBBbK.......',
      '...KbBBBbK.......KbBBBBbK.......',
      '...KbBBBbK.......KbBBBBbK.......',
      '...KdddddK.......KddddddK.......',
      '....KKKKK.........KKKKKK........',
      '................................',
    ],
    attack: [
      '....................KK..K.K.K...',
      '...................KbbKKWKWKWK..',
      '..................KbTTbKBBBBK...',
      '.................KbBBBBTBBBbK...',
      '................KTBBBBKBBBbK....',
      '...............KTBBBBBBEEEK.....',
      '..............KTBBBBBBEERRK.....',
      '.............KTBBBBBBBbEEEK.....',
      '............KTBBBBBBBBbbKK......',
      '...........KTBBBBBBBBBbBBbKKK...',
      '..........KTBBBBBBBBBBbBBBbWWK..',
      '..........KBBBBBBBBBBBbbKKKKK...',
      '.........KTBBBBBBBBBBbbK........',
      '.........KBBBBBBBBBBBbbK........',
      '.........KBBBBBBBBBBbbbK........',
      '.........KBBBBBBBBBBbbbK........',
      '.........KbBBBBBBBBBbbbK........',
      '.........KbBBBBBBBBbbbbK........',
      '.........KbbBBBBBBBbbbbK........',
      '.........KbbbBBBBBbbbbbK........',
      '..........KbbbbbbbbbbbK.........',
      '..........KbBBBbKbBBBbK.........',
      '..........KbBBBbKbBBBbK.........',
      '..........KbBBBbKbBBBbK.........',
      '..........KbBBBbKbBBBbK.........',
      '..........KbBBBbKbBBBbK.........',
      '..........KbBBBbKbBBBbK.........',
      '..........KbBBBbKbBBBbK.........',
      '..........KbBBBbKbBBBbK.........',
      '.........KdddddKdddddK..........',
      '..........KKKKK.KKKKK...........',
      '................................',
    ],
  },
};
