import type { SpriteDef } from '../sprite';

export const BLOOD_COUNTESS_SPRITE: SpriteDef = {
  width: 48,
  height: 48,
  legend: {
    K: 'black',
    W: 'white',
    L: 'lightGray',
    M: 'gray',
    H: 'hotRed',
    R: 'red',
    r: 'darkRed',
    e: 'deepBrown',
    n: 'night',
    a: 'darkSlate',
    A: 'slate',
    p: 'plum',
    m: 'magenta',
    o: 'gold',
    Y: 'yellow',
    P: 'pink',
  },
  frames: {
    idle: [
      '.....................KKKK.......................',
      '....................KaAAaK......................',
      '...................KaAAnnaK.....................',
      '...................KaAnnnnK.....................',
      '.................KKaaannnnK..KK.................',
      '....KKKKK...K...KPaAAAannnnKKPPK..K....KKK......',
      '..KKmmmeeK.KPK..KaAnnnnnnnnnKPRK.KPK..KmemKKK...',
      '.KmmppppeKKKPPK.KoroHoKoKnnnPrRKKPRKKKeeppmmmK..',
      '.KpppppppeeKPrPKPooooooonnnnPrrPPRKKmmeppppppK..',
      '.KppppppppemKPrPaLLLLLLaannnnrrrrRKmeepppppppK..',
      '.KpppppppppeeRraLLLLLLLMannnnrrrrRmpeppppppppK..',
      '.KppppppppppeRrLHHLHHLMMaannnrrrrReepppppppppK..',
      '.KpppppppppppPLLLLLLLLMMaannnrrrrReppppppppppK..',
      '.KpooooopppppPrLLLLLLLMaannnrrrrPppppppppppppK..',
      '.KoHHHHHopppppPrRRLLLMMaannrrrrrRppppppppppppK..',
      '.KYoooooYpppppPrLLLLMMaannrrrrrrRpppppppppeepK..',
      '..KYooooepppppPrrMMMMaanrrrrrrrrRpppppeeeepKpK..',
      '...KYooppeeeepPrrrLLMnLLLLrrrrrrRppeeeeppppKK...',
      '....KopKppppeeRrPPRPPLLLLLrrrrrreeepppppppK.....',
      '...KLLLLpppppppPRRRRRooooooorrrrrppppppKppK.....',
      '..KLLLLLKppppppPRRRRRnnHHnnrrrrrrpppppK.KpK.....',
      '..KWMLLMKppppppPRRRRRnnHHPnnrrrrepppppK..K......',
      '..KWKWKKapppeeeRRRRRannnnnnnnrrpeeeeepK.........',
      '...K.K.KanneeKPRRRRRannPPPnnnKpppKKKeeeK........',
      '.......KannRRPRRRRRRannnnnnnnKppK...KKK.........',
      '......KannnRRRRRRRRRannRRRnnnKppK...............',
      '......KannnRRRRRRRRRannnnnnnK.KpK...............',
      '......KannnKKPrrKKKKannRRRnnKK.K................',
      '......KanKK..KKK.KPooooHHoooooK.................',
      '.......KK.......KProoooHHooooorK................',
      '...............KPrrrRnaannnRRrrrK...............',
      '...............KPrrrRnaannnRRrerK...............',
      '..............KPrrrrnaaannnRRRrerK..............',
      '.............KPrrrrrnaaannnnRRrerrK.............',
      '.............KPrrrrrnaannnnnRRreerrK............',
      '............KPrrrrrnnaannnnnRRrrerrK............',
      '...........KPrrrrrrnaaannnnnRRRreerrK...........',
      '...........KPrrrrrrnaaannnnnnRRreerrrK..........',
      '..........KPrrrrrrnnaaannnnnnRRrreerrK..........',
      '..........KPrrrrrrnaaaannnnnnRRRreerrrK.........',
      '.........KPrrrrrrrnaaaannnnnnnRRreeerrrK........',
      '........KPrrrrrrrnnaaannnnnnnnRRrreerrrrK.......',
      '........KPrrrrrrrnnaaannnnnnnnRRRreeerrrK.......',
      '.......KPrrrrrrrrnaaaannnnnnnnnRRreeerrrrK......',
      '......KPrrrrrrrrnnaaaannnnnnnnnRRrreeerrrrK.....',
      '......KooooooooooooooooooooooooooooooooooooK....',
      '.......KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.....',
      '................................................',
    ],
    attack: [
      '.....................KKKK.......................',
      '....................KaAAaK......................',
      '...................KaAAnnaK.....................',
      '....KKKK...........KaAnnnnK............KKK......',
      '..KKmmmeK........KKaaannnnK..KK.......KmemKKK...',
      '.KmmppppeKK.K...KPaAAAannnnKKPPK..K.KKmeppmmmK..',
      '.KppppppeemKPK..KaAnnnnnnnnnKPRK.KPKmmeepppppK..',
      '.KppppppppemRPK.KoroHoKoKnnnPrRKKPRmpepppppppK..',
      '.KppppppppeeRrPKPooooooonnnnPrrPPRmpeepppppppK..',
      '.KppppppppppePrPaLLLLLLaannnnrrrrRpepppppppppK..',
      '.KppppppppppeRraLLLLLLLMannnnrrrrReepppppppppK..',
      '.KpppppppppppRrLHHLHHLMMaannnrrrrReppppppppppK..',
      '.KpppppppppppRLLLLLLLLMMaannnrrrrRpppppppppppK..',
      '.KpppppppppppRrLLLLLLLMaannnRrrrPppppppppppppK..',
      '.KppppppppppppPrRRLLLMMaannRrrrrRppppppppppppK..',
      '.KpKeeepppppppHrLLLLMMaannRrrrrrRpppppppppeepK..',
      '..KKppeeepHHHHHrrMMMMaanRRrrrrrrRpppppeeeepKpK..',
      '...KppppHHHHHHRrrrLLMnLLLLrrrrrrRppeeeLLLWpKK...',
      '....KpHHHHHpeeRrPPRPPLLLLLrrrrrrrPPRRRLLLpK.....',
      '....KHHPHppppapPRRRRRooooooorrrrrrrrrrLLMWK.....',
      '...KHPPKeppppannRRRRRnnHHnnrrrrrrrrrrrMMKpK.....',
      '..KKPPPeeeeLLLeeeeeeeeeeeennrrrrrrrpppKK.K......',
      '.KPPPPPPePLLLLLPPPPPPPPPPPnnnrrpeeeeepK.........',
      'KWWrrrHHeHWLLLMHHHHHHHHHHHnnnKpppKKKeeeK........',
      '.KHHrrrrerLLLLMrrrrrrrrrrrnnnKppK...KKK.........',
      '..KKHrreeeWMMMeeeeeeeeeeeennnKppK...............',
      '...KRHrKeKKKanKKKKKnannnnnnnK.KpK...............',
      '...KRKKrK...KK....KKannRRRnnKK.K................',
      '...KRRRKK........KPooooHHoooooK.................',
      '....KRRRRKK.....KProoooHHoooooPK................',
      '...KKKRRRRRKKK.KPrrrRnaannnRRrrPK...............',
      '..KPHKKKRRRRRRKKrrrrRnaannnRRrerK...............',
      '..KHHK..KKRRRRRPrrrrnaaannnRRRRePK..............',
      '...KK....KKKKKRrrrrrnaaannnnRRrerPK.............',
      '........KPHK.KrrrrrrnaannnnnRRreerPK............',
      '........KHHKKPrrrrrnnaannnnnRRrRerrK............',
      '.........KKKPrrrrrrnaaannnnnRRRreerPK...........',
      '...........KPrrrrrrnaaannnnnnRRreerrPK..........',
      '..........KPrrrrrrnnaaannnnnnRRrReerrK..........',
      '..........KPrrrrrrnaaaannnnnnRRRreerrPK.........',
      '.........KPrrrrrrrnaaaannnnnnnRRreeerrPK........',
      '........KPrrrrrrrnnaaannnnnnnnRRrReerrrPK.......',
      '........KPrrrrrrrnnaaannnnnnnnRRRreeerrrK.......',
      '.......KPrrrrrrrrnaaaannnnnnnnnRRreeerrrPK......',
      '......KPrrrrrrrrnnaaaannnnnnnnnRRrReeerrrPK.....',
      '......KooooooooooooooooooooooooooooooooooooK....',
      '.......KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.....',
      '................................................',
    ],
  },
};
