import type { SpriteDef } from '../sprite';

export const BOAR_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    B: 'brown',
    b: 'rust',
    d: 'darkBrown',
    D: 'deepBrown',
    P: 'pink',
    p: 'skinShade',
    W: 'white',
    N: 'night',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '..............KKKK..............',
      '............KKDDDDKK............',
      '..........KKDDDDDDDDKK..........',
      '........KKDDDbbbbbbDDdK.........',
      '......KKDDbbBBBBBBBBbbdK........',
      '.....KDDbBBBBBBBBBBBBBBdK.......',
      '....KdbBBBBBBBBBBBBBBBBBdK......',
      '...KdbBBBBBBBBBBBBBBBBBBBdK.....',
      '...KdBBBBBBBBBBBBBBBBBBKBBdKK...',
      '...KdBBBBBBBBBBBBBBBBBBBBBBWWK..',
      '...KddBBBBBBBBBBBBBBBBBBBBBWPPK.',
      '....KdddBBBBBBBBBBBBBBBBBBBPPpK.',
      '.....KddddddBBBBBBBBBBBBdddKKK..',
      '.....KDDDKKKKKddddddKKDDDKK.....',
      '.....KdBdK....KKKKKK.KdBBdK.....',
      '.....KdBdK...........KdBBdK.....',
      '.....KdBdK...........KdBBdK.....',
      '.....KdBdK...........KdBBdK.....',
      '.....KNNNK...........KNNNNK.....',
      '......KKK.............KKKK......',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '.................KKK............',
      '...............KKDDDKK..........',
      '.............KKDDDDDDDKK........',
      '...........KKDDDbbbbbDDdK.......',
      '.........KKDDbbBBBBBBbbDdK......',
      '.......KKDDbBBBBBBBBBBBBBdK.....',
      '......KDDbBBBBBBBBBBBBBBBBdK....',
      '.....KdbBBBBBBBBBBBBBBBBBBBdK...',
      '....KdBBBBBBBBBBBBBBBBBBBBBBdK..',
      '....KdBBBBBBBBBBBBBBBBBBBBBBBdK.',
      '....KddBBBBBBBBBBBBBBBBBBBKBBBWK',
      '.....KddBBBBBBBBBBBBBBBBBBBBBWWK',
      '......KdddBBBBBBBBBBBBBBBBBBBPPK',
      '...KKK.KddddddBBBBBBBBBBBddPPpK.',
      '..KDDDK.KKKKdddddddKKKKDDDKKKK..',
      '.KdBdK......KKKKKKK....KdBBdK...',
      'KdBdK...................KdBBdK..',
      'dBdK.....................KdBBdK.',
      'dBdK.....................KdBBdK.',
      'NNNK.....................KNNNNK.',
      'KKK.......................KKKK..',
      '................................',
    ],
  },
};
