import type { SpriteDef } from '../sprite';

export const BONE_MAGE_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    W: 'white',
    L: 'lightGray',
    M: 'gray',
    H: 'hotRed',
    r: 'darkRed',
    A: 'slate',
    a: 'darkSlate',
    n: 'night',
    C: 'cyan',
    B: 'blue',
    b: 'navy',
    p: 'plum',
  },
  frames: {
    idle: [
      '..K.K.K.....KKKK.K..............',
      '.KLKCKMK..KKAAaaKnK.............',
      '.KLCWCMK.KAAAaaaannK............',
      '.KLCCBMKKAAaaaaaannK............',
      '.KMBBbMKKAWWWWWWLnanK...........',
      '..KWLMK.KaWWWWWLMnaanK..........',
      '...KLMK..KHKWHKLMnaanK..........',
      '...KLMK...KKWKKLMnaannK.........',
      '...KLMK..KWWKWLMMnaannK.........',
      '...KLMK...KKWKWKMnaannK.........',
      '...KLMK..KKLWLWMnaaannK.........',
      '...KLMK.KaAaLMaaaaannK..........',
      '..KWLMKKAAaanLWnaaannK..........',
      '..KWLWLAAAaanWLWnaaKnnK.........',
      '..KLMLMAaaaanKKKnaaKnnK.........',
      '...KLMAaaannLWLnaaKannK.........',
      '...KLMaaannAnKnaaaKannK.........',
      '...KLMnnnAaaaaaaaaKannK.........',
      '...KLMKKarrrrrLrrrrrrnnK........',
      '...KLMKKAAaaaKaaaaaKannK........',
      '...KLMKAAaaaaKaaaaaKannK........',
      '...KLMKAAaaaKaaaaaaaKannK.......',
      '..KWLMAAaaaaKaaaaaaaKannK.......',
      '...KLMAAaaaKaaaaaaaaKaannK......',
      '...KLMAaaaaKaaaaaaaaKaanK.......',
      '...KLMAaaaKaaaaaaaaaKaannK......',
      '...KLMaaaaKaaaaaaaaaKaannK......',
      '...KLMaaaKaaaaaaaaaaKaanKnK.....',
      '...KLMKaaKnbKaaaanbKaKnbnK......',
      '...KLMKKbKKbKKKbKKKbKKbKK.......',
      '....KK..K..K...K...K..K.........',
      '................................',
    ],
    attack: [
      '.....K.K.K......KKKK.K..........',
      '....KLKCKMK...KKAAaaKnK.........',
      '....KLCWCMK..KAAAaaaannK........',
      '....KLCCBMK.KAAaaaaaannK........',
      '....KMBBbMK.KAWWWWWWLnanK.......',
      '....KKWLMK..KaWWWWWLMnaanK......',
      '..KKpKKLMK...KHKWHKLMnaanK......',
      '.KbBpKKLMK....KKWKKLMnaannK.....',
      'KbCCBK.KLMK..KWWKWLMMnaannK.....',
      'KCWWCbKKLMK...KKWKWKMnaannK.....',
      'KCWWCBpKLMK..KKLWLWMnaaannK.....',
      'KbCCBpKKLMKKKaAaLMaaaaannK......',
      '.KbpKK.KKLAAaAaanLWnaaannK......',
      '..KK..KWLWLAaaaanWLWnaaKnnK.....',
      '......KLMLMaanaanKKKnaaKnnK.....',
      '.......KKLMaaannLWLnaaKannK.....',
      '........KnLMannAnKnaaaKannK.....',
      '.........KLMnAaaaaaaaaKannK.....',
      '.........KLMarrrrrLrrrrrrnnK....',
      '.........KLMAAaaaKaaaaaKannK....',
      '..........KLMaaaaKaaaaaKannK....',
      '..........KLMaaaKaaaaaaaKannK...',
      '.........KWLMaaaKaaaaaaaKannK...',
      '.........KALMaaKaaaaaaaaKaannK..',
      '........KAAaLMaKaaaaaaaaKaanK...',
      '........KAAaLMKaaaaaaaaaKaannK..',
      '.......KAAaaLMKaaaaaaaaaKaannK..',
      '.......KAAaaLMaaaaaaaaaaKaanKnK.',
      '.......KAbKaaLMbKaaaanbKaKnbnK..',
      '.......KbK.KbLMbKKKbKKKbKKbKK...',
      '........K...KKKK...K...K..K.....',
      '................................',
    ],
  },
};
