import type { SpriteDef } from '../sprite';

export const BONE_GOLEM_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    W: 'white',
    S: 'sand',
    G: 'gray',
    A: 'slate',
    R: 'hotRed',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '...................K......K.....',
      '.............K....KWK....KWK....',
      '............KWK...KWGK..KWGK....',
      '.....KKKKK.KWGK..KWSGK..KWGK....',
      '....KWWWWWKKWSGKKKWSGKKKWSGK....',
      '...KWSSSSSGWWWWWWWWWWWWWWGK.....',
      '..KWSSSSSSGWSSSSSSSSSSSSSSGK....',
      '..KWKKSKKSGWSSSSSSSSSSSSSSGGK...',
      '..KSKRSKRSGSSSSSSSSSSSSSSGGGK...',
      '..KSSSKSSGGGGGGGGGGGGGGGGGGAK...',
      '...KSWWWWGGAAAAAAASGAAAKSGAK....',
      '...KGAAAAGGWSSSSSSSGSSGKSGAK....',
      '....KSSSGSGKAAAAAASGAAKKSGAK....',
      '.....KKKWSGKWSSSSSSGSGKKSGAK....',
      '.....KKKWSGKKAAAAASGAAKKSGGAK...',
      '....KWWWWSK.KWSSSSSGSGKSSSGAK...',
      '...KWSSSSSGK.KAAAASGAKSGGGGGAK..',
      '..KWSSSSSSGKKWSSSSSSSGAAGGGGAK..',
      '.KWSSSSSSGGKWSSSAAASSSGGGGGGAK..',
      '.KAAASSSSGGKGGGAKKKAGGGAGGGGAK..',
      '.KWSSSSSSGGKWSGK..KSGASGGGGAAK..',
      '.KAAASSSSGGKWSGK..KSGAKAAAAAK...',
      '.KWSSSSSGGKKWSGK..KSGAKKKKKK....',
      '..KGGGGGGK.KWSGK..KSGAK.........',
      '...KKKKKK.KKWSGK..KSGAKKK.......',
      '.........KWWWWWWK.KSSSSSSK......',
      '.........KWGGGGGK.KSAAAAAK......',
      '..........KKKKKK...KKKKKK.......',
      '................................',
      '................................',
    ],
    attack: [
      '................................',
      '..KKKKKK........................',
      '.KWWWWWSKK.........K......K.....',
      'KWSSSSSSGGK..K....KWK....KWK....',
      'KAAASSSSSGK.KWK...KWGK..KWGK....',
      'KWSSSSSSGGKKWGK..KWSGK..KWGK....',
      'KAAASSSSGGKKWSGKKKWSGKKKWSGK....',
      'KWSSSSSSGGKWWWWWWWWWWWWWWGK.....',
      '.KGGSSGWWWWWSSSSSSSSSSSSSSGK....',
      '..KKKKWSSSSSGSSSSSSSSSSSSSGGK...',
      '....KWSSSSSSGSSSSSSSSSSSSGGGK...',
      '....KWKKSKKSGGGGGGGGGGGGGGGAK...',
      '....KSKRSKRSGAAAAASGAAAKSGAK....',
      '....KSSSKSSGGSSSSSSGSSGKSGAK....',
      '.....KSWWWWGAAAAAASGAAKKSGGAK...',
      '.....KGAAAAGWSSSSSSGSGKSSSGAK...',
      '......KSSSGKKAAAAASGAASGGGGGAK..',
      '.......KKAK.KWSSSSSGSGAAGGGGAK..',
      '.........K...KAAAASGAKSGGGGGAK..',
      '............KWSSSSSSSGAAGGGGAK..',
      '...........KWSSSAAASSSGGGGGAAK..',
      '...........KGGGAKKKAGGGAAAAAK...',
      '...........KWSGK..KSGAKKKKKK....',
      '...........KWSGK..KSGAK.........',
      '...........KWSGK..KSGAK.........',
      '...........KWSGK..KSGAK.........',
      '..........KKWSGK..KSGAKKK.......',
      '.........KWWWWWWK.KSSSSSSK......',
      '.........KWGGGGGK.KSAAAAAK......',
      '..........KKKKKK...KKKKKK.......',
      '................................',
      '................................',
    ],
  },
};
