import type { SpriteDef } from '../sprite';

export const BONE_DRAGON_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    W: 'white',
    S: 'sand',
    t: 'tan',
    d: 'brown',
    n: 'night',
    a: 'darkSlate',
    Q: 'pink',
    m: 'magenta',
    P: 'plum',
    N: 'night',
  },
  frames: {
    idle: [
      '....................K...........',
      '.............K.....KWKKKKKKKKK..',
      '...........KKSK..K.KWSSSSSSSStK.',
      '.........KKSStK.KtKKWSSSaaaaaK..',
      '....KKKKKSStKK.KntnKWSaSSaaaaK..',
      '..KKWWWWWWStK..KtnnWSnSaaSaaaK..',
      '.KWWSSSKKSStK.KntnnWSnSaaaSSK...',
      'KWSSSSSQKSSStKKntnnWSnnSaaaaSK..',
      'KSKSSSSStSSStKKtnnWSnnnSaaaaaSK.',
      'KtttttttttSSdKKtnnWSnnnnSannnnSK',
      '.KWKWKWKWttdStKnnnWSnnnnSannnKK.',
      '..KSSSSSSStdSStKnWSnnnnnnSaaK...',
      '...KttttttdKWSStKWSnnnnnnSaK....',
      '....KKKKKKK.KWSSWWWWWWWWStSKK...',
      '.............KSSSSSSSSSSSdWStK..',
      '.............KStnnStnnStndKSStK.',
      '.............KStnnStnnStndStStK.',
      '............KWSStnnStnnSdStKStK.',
      '............KSSStnnStnntStK.KStK',
      '.............KSStnnStntStK..KStK',
      '..............KSStKttKStdK..KStK',
      '..............KStdKKK.KStK.KStK.',
      '.............KStKK....KStKKStK..',
      '.............KStK......KStKWtK..',
      '............KStK.......KStKKWK..',
      '..........KKKStK.....KKKStK.K...',
      '.........KWSSSStK...KWSSSStK....',
      '.........KWKWKWK....KWKWKWK.....',
      '..........K.K.K......K.K.K......',
      '................................',
      '................................',
      '................................',
    ],
    attack: [
      '....................K...........',
      '...................KWKKKKKKKKK..',
      '.................K.KWSSSSSSSStK.',
      '................KtKSWSSSaaaaaK..',
      '...............KnSStWSaSSaaaaK..',
      '..........KKKKKSStnWSnSaaSaaaK..',
      '...K....KKWWWWWWStnWSnSaaaSSK...',
      '.KKNK..KWWSSSKKSStnWSnnSaaaaSK..',
      'KNPNNKKWSSSSSQKSSStSnnnSaaaaaSK.',
      '.KPPPNNSKSSSSStSSStSnnnnSannnnSK',
      'KNPPPPPtttttttttSSdSnnnnSannnKK.',
      'KNPmmPPPWNWNWKWttdStnnnnnSaaK...',
      '.KPmmmmmmmmPNNnStdSStnnnnSaK....',
      'KNPmmmmmmQQQmnSStdWSStWWStSKK...',
      'KNPmmmmPPPPWSSSStSSWSSSSSdWStK..',
      'KNPmPPPNNNNtttttdnStWSStndKSStK.',
      '.KPPPPNKKKKKKKStnnStnnStndStStK.',
      'KNPPNNK.....KWSStnnStnnSdStKStK.',
      'KNPNKK......KSSStnnStnntStK.KStK',
      '.KNK.........KSStnnStntStK..KStK',
      '..K...........KSStKttKStdK..KStK',
      '..............KStdKKK.KStK.KStK.',
      '.............KStKK....KStKKStK..',
      '.............KStK......KStKWtK..',
      '............KStK.......KStKKWK..',
      '..........KKKStK.....KKKStK.K...',
      '.........KWSSSStK...KWSSSStK....',
      '.........KWKWKWK....KWKWKWK.....',
      '..........K.K.K......K.K.K......',
      '................................',
      '................................',
      '................................',
    ],
  },
};
