import type { SpriteDef } from '../sprite';

export const CHIMERA_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    S: 'sand',
    T: 'tan',
    B: 'brown',
    d: 'darkBrown',
    e: 'deepBrown',
    u: 'gold',
    o: 'orangeBrown',
    R: 'rust',
    W: 'white',
    L: 'lightGray',
    M: 'gray',
    A: 'slate',
    H: 'darkBrown',
    h: 'sand',
    G: 'green',
    g: 'midGreen',
    k: 'darkGreen',
    Y: 'yellow',
    r: 'red',
    O: 'orange',
    w: 'white',
    x: 'darkRed',
  },
  frames: {
    idle: [
      '.................KKK............',
      '................KhhhK...........',
      '...............KhhHHhK..........',
      '..............KLhHKKhHK..KKKK...',
      '.............KLLLMAAKKHKKgGGgK..',
      '............KLYeLMMAAKKKgGGYGgK.',
      '.......KKKKKLLLLLMMAK.KgGGGGGGgK',
      '......KuoRoRALLLMMAK...KkkgGGGgK',
      '.....KuooooRoRWLMMAK....KKKKSGgK',
      '....KuoTTTTooRoWMMMAK......KSGgK',
      '...KuoTTTTTTooRKLMMAK......KSGgK',
      '..KRTTYeTTTTooRoLMMAAK.....KSGgK',
      '.KTTTTTTTTTSoooRLMMAAKKKKKKKSGgK',
      'KSTTTTTTTTSoooRRLMMAASSSSSBKSGgK',
      'KeTSSSTTTSooooRoTTTTTTTTSSTBSGgK',
      '.KSSSSSTTooooooRTTTTTTTSTTTTBKK.',
      '..KddSTToooooRoRTTTTTTSTTTTTBK..',
      '...KooooooooRoRRTTTTTTTTTTTBBK..',
      '....KRooooooRRRTTTTTTTTTTTBBBK..',
      '.....KRoRooRoRTTTTTTTTBTTTBBdK..',
      '......KKKKBBTTTTTTTTTBBTTTBBdKK.',
      '.....KSTTTBBBBBdBBBBBBSTTTTBKBdK',
      '.....KTTTTBKBBBdBBBBBBTTTTBBKBdK',
      '.....KTTTTBKBBBdKKKKKKKTTTBKKBdK',
      '.....KTTTBBKBBddK.....KTTTBKKBdK',
      '.....KTTTBBKBBddK.....KTTTBKKBdK',
      '.....KTTTBBKBBddK.....KTTTBKKBdK',
      '....KSTTTBBKBBddK....KSTTTBKBBdK',
      '....KSTTTBBKBBddK....KSTTTBKBBdK',
      '.....KKKKKK.KKKK......KKKKK.KKK.',
      '................................',
      '................................',
    ],
    attack: [
      '...................KKK..........',
      '..................KhhhK.........',
      '.................KhhHHhK........',
      '................KLhHKKhHKKKK....',
      '...............KLLLMAAKKgGGgK...',
      '..............KLYeLMMAAgGYGGgK..',
      '...........KKKLLLLLMMAKwGGGGGgK.',
      '..........KuoRoReLMMAK.KxxKgGGgK',
      '.........KuooooRoRMMAKKwkkgGGGgK',
      '........KuoTTTTooRoMMAKKKKKKSGgK',
      '.......KuoTTTTTTooRMMAK....KSGgK',
      '..K...KdTTYeTTTTooRoMAAK...KSGgK',
      '.KrK.KSTTTTTTTTSoooRMAAKKKKKSGgK',
      'KrOrKSTTTTTTTTSoooRRMAASSSSSSGgK',
      'KOYOreSSSTTTTSooooRoTTTTTTSSSGgK',
      'KYYYOOwTwTTTSooooooRTTTTTSTTSGgK',
      'KYwwYYOYOxxTSoooooRoTTTTSTTTTTBK',
      'KwwwwYYOxxxTooooooRRTTTTTTTTTBBK',
      'KYwwYYwSwSSTooooRoRTTTTTTTTTBBBK',
      'KOYYOOrSSSSoooRooRTTTTTTBTTTBBdK',
      'KrOOrKKKKRooooRoRTTTTTTBBTTTBBdK',
      '.KrKK..KSTTTBBBBdBBBBBBBTTTTBdK.',
      '..K....KSTTBKBBBdBBBBBBBTTTTBK..',
      '......KSTTTBKBBdKKKKKKKKKTTTBK..',
      '......KSTTBKBBBdK.......KTTTBK..',
      '.....KSTTTBKBBdK.........KTTTBK.',
      '.....KSTTBKBBddK.........KTTTBK.',
      '....KSTTTBKBddK.........KSTTTBK.',
      '....KSSTTBKBddK.........KSTTTBK.',
      '.....KKKKK.KKK...........KKKKK..',
      '................................',
      '................................',
    ],
  },
};
