import type { SpriteDef } from '../sprite';

export const CLERIC_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    W: 'white',
    E: 'sand',
    T: 'tan',
    V: 'navy',
    U: 'blue',
    S: 'skin',
    s: 'skinShade',
    G: 'gold',
    O: 'orange',
    B: 'brown',
    b: 'darkBrown',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '........................KKK.....',
      '........................KGK.....',
      '...........KKKKKK.....KKKGKKK...',
      '..........KBBBBBBK....KGGWGGK...',
      '.........KbBBBBBBBK...KKKGKKK...',
      '.........KbGGGGGGGK.....KGK.....',
      '.........KbBSSSSSSK.....KGK.....',
      '.........KbSSSSKSsK.....KOK.....',
      '.........KbSSSSSSsK.....KBK.....',
      '..........KbSSSSsK......KBK.....',
      '...........KKSSSKK......KBK.....',
      '........KWEEEUVVEEETK...KBK.....',
      '........KWEEEUVVEETKEK..KBK.....',
      '........KWEEEUVVEETKEEK.KBK.....',
      '........KWEEEUVVEETKEEEKKBK.....',
      '........KWEEEUVVEETKTEEKSSSK....',
      '........KWEEEUVVEETKKKKKSSSK....',
      '.......KWEEEEUVVEEETK...KBK.....',
      '.......KWEEEEUVVEEETK...KBK.....',
      '.......KWEEEEUVVEEETTK..KBK.....',
      '......KWEEEEEUVVEEETTK..KBK.....',
      '......KWEEEEEUVVEEETTK..KBK.....',
      '......KWEEEEEUVVEEETTTK.KBK.....',
      '......KWEEEEEUVVEEETTTK.KBK.....',
      '......KWEEEEEUVVEEETTTK.KBK.....',
      '......KGGGGGGGGGGGGGGGK.KBK.....',
      '......KKKbbKKKKKKbbKKK..KKK.....',
      '........KbbK....KbbK............',
      '........KKKK....KKKK............',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '................................',
      '...........KKKKKK...............',
      '..........KBBBBBBK..............',
      '.........KbBBBBBBBK.............',
      '.........KbGGGGGGGK.............',
      '.........KbBSSSSSSK.............',
      '.........KbSSSSKSsK.............',
      '.........KbSSSSSSsK.............',
      '..........KbSSSSsK..............',
      '...........KKSSSKK..............',
      '........KWEEEUVVEEETK...........',
      '........KWEEEUVVEETKEK..........',
      '........KWEEEUVVEETKEK..........',
      '........KWEEEUVVEETKEK..........',
      '........KWEEEUVVEETKSSK.........',
      '........KWEEEUVVEETKSSK.........',
      '.......KWEEEEUVVEEETKBK....KKK..',
      '.......KWEEEEUVVEEETKKBK...KGK..',
      '.......KWEEEEUVVEEETTKKBKKKKGKKK',
      '......KWEEEEEUVVEEETTK..OGGGWGGK',
      '......KWEEEEEUVVEEETTK..KKKKGKKK',
      '......KWEEEEEUVVEEETTTK....KGK..',
      '......KWEEEEEUVVEEETTTK....KKK..',
      '......KWEEEEEUVVEEETTTK.........',
      '......KGGGGGGGGGGGGGGGK.........',
      '......KKKbbKKKKKKbbKKK..........',
      '........KbbK....KbbK............',
      '........KKKK....KKKK............',
      '................................',
    ],
  },
};
