import type { SpriteDef } from '../sprite';

export const CULTIST_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    P: 'magenta',
    p: 'plum',
    d: 'deepBrown',
    n: 'night',
    R: 'red',
    r: 'darkRed',
    H: 'hotRed',
    S: 'skin',
    s: 'skinShade',
    L: 'lightGray',
    M: 'gray',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '..............KKKK..............',
      '............KKPPppK.............',
      '...........KPPPpppdK............',
      '..........KPPppppppdK...........',
      '.........KPPpppppppddK..........',
      '........KPPpppppppddnK..........',
      '........KpnnnnnpppddnK..........',
      '.........KKHKHKppddnKnK.........',
      '..KK......KKKKKppddnKnK.........',
      '.KHRK.....KKKKpppdnKKdnK........',
      'KHnPrK...KPPpppppppddnK.........',
      'KrnnrKKKKPPPpppppppdnK..........',
      '.KrrKKPPppKPpppppppdnK..........',
      '..KSspppddPpppppppppdnK.........',
      '.KSSKddnKKPpppppppppdnK.........',
      '..KK.KKK.KPpppppppppdnK.........',
      '.........KRRRRRRRRRRrdnK........',
      '.........KrrrrrrrrrrdsSK........',
      '.........KPRrPdppdpddnLK........',
      '........KPpRrPdppdppddLK........',
      '........KPprpPdpppdpddMK........',
      '........KPpprdppppddddnK........',
      '.......KPpppPdppppdpdddnK.......',
      '.......KPpppPdppppdpdddnK.......',
      '.......KPppPdpppppdpdddnK.......',
      '......KrRRRRRrrrrrrrrrrdK.......',
      '.......KKnndKKKnnKKKKKKK........',
      '.........KKK...KK...............',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '..............KKKK..............',
      '............KKPPppK.............',
      '..K........KPPPpppdK............',
      '.KHK.K....KPPppppppdK...........',
      'KHHRKrK..KPPpppppppddK..........',
      'HnPnRK..KPPpppppppddnK..........',
      'HnnnrRK.KpnnnnnpppddnK..........',
      'RnnnrKKKKKKHKHKppddnKnK.........',
      'KrrrKSsPPPpKKKKppddnKnK.........',
      '.KKKSSpppddKKKpppdnKKdnK........',
      '....KKKKddPPpppppppddnK.........',
      '........KKKPpppppppdnK..........',
      '..........KPpppppppdnK..........',
      '.........KPpppppppppdnK.........',
      '.........KPpppppppppdnK.........',
      '.........KPpppppppppdnK.........',
      '.........KRRRRRRRRRRrdnK........',
      '.........KrrrrrrrrrrdsSK........',
      '.........KPRrPdppdpddnLK........',
      '........KPpRrPdppdppddLK........',
      '........KPprpPdpppdpddMK........',
      '........KPpprdppppddddnK........',
      '.......KPpppPdppppdpdddnK.......',
      '.......KPpppPdppppdpdddnK.......',
      '.......KPppPdpppppdpdddnK.......',
      '......KrRRRRRrrrrrrrrrrdK.......',
      '.......KKnndKKKnnKKKKKKK........',
      '.........KKK...KK...............',
      '................................',
    ],
  },
};
