import type { SpriteDef } from '../sprite';

export const DARK_PRIEST_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    A: 'slate',
    a: 'darkSlate',
    n: 'night',
    P: 'magenta',
    p: 'plum',
    L: 'lightGray',
    M: 'gray',
    S: 'slate',
    T: 'sand',
    t: 'tan',
    G: 'green',
    g: 'midGreen',
  },
  frames: {
    idle: [
      '.................K..............',
      '................KpK.............',
      '...............KPTpK............',
      '..............KPPTppK...........',
      '..............KPTTTpK...........',
      '.......KKKK...KPPTppK...........',
      '......KLLMgK.KppppppK...........',
      '.....KgLLLMgK.KLLLMnK...........',
      '.....KgGnGMgK.KGnGMnK...........',
      '.....KgLLMSgK.KLLLMnK...........',
      '.....KggnSggK.KnLnMKK...........',
      '......KggggK...KLMaanKK.........',
      '.......KTtK.KKKAaPpannnK........',
      '.......KTtKKAAaaaPpannnK........',
      '......KLLLKAAaaaaPpaannnK.......',
      '......KLMMMAaaaanPpaannnK.......',
      '.......KTtKAaaanaPpaannnK.......',
      '.......KTtKPPppaaPpaannnnK......',
      '.......KTtKKKKAaaPpaannnnK......',
      '.......KTtK..KAaaPpaannnnK......',
      '.......KTtK..KAaaPpaannnnK......',
      '.......KTtK.KAaaaPpaaannnnK.....',
      '.......KTtK.KAaaaPpnaannnnK.....',
      '.......KTtK.KAaaaPpnaannnnK.....',
      '.......KTtK.KAaaaPpnaannnnnK....',
      '.......KTtK.KAaaaPpnaannnnnK....',
      '.......KTtKKAaaaaPpnaannnnnK....',
      '.......KTtKKPPPPPPpnppnpppppK...',
      '.......KTtKKPPpppPPpppppppppK...',
      '.......KTtK.KKKKKKKKKKKKKKKK....',
      '........KK......................',
      '................................',
    ],
    attack: [
      '.......K.........K..............',
      '......KGK.......KpK.............',
      '......KKKK.....KPTpK............',
      '.....KggggK...KPPTppK...........',
      '....KgLLMggK..KPTTTpK...........',
      '.KKKggLLLMggKKKPPTppK...........',
      'KgGKgGGnGMGgGgppppppK...........',
      '.KKKgGLLMSGgKKKLLLMnK...........',
      '...KggGnSGggK.KGnGMnK...........',
      '....KggGGggKKKKLLLMnK...........',
      '.....KggggpAAaKnLnMKK...........',
      '.....KLLLLPAaaaKLMaanKK.........',
      '.....KLMMMPAaaaaaPpannnK........',
      '......KTtKKnAaanaPpannnK........',
      '......KTtK.KKKKAaPpaannnK.......',
      '......KTtK...KAaaPpaannnK.......',
      '......KTtK...KAaaPpaannnK.......',
      '......KTtK...KAaaPpaannnnK......',
      '......KTtK...KAaaPpaannnnK......',
      '......KTtK...KAaaPpaannnnK......',
      '......KTtK...KAaaPpaannnnK......',
      '......KTtK..KAaaaPpaaannnnK.....',
      '......KTtK..KAaaaPpnaannnnK.....',
      '......KTtK..KAaaaPpnaannnnK.....',
      '......KTtK..KAaaaPpnaannnnnK....',
      '......KTtK..KAaaaPpnaannnnnK....',
      '......KTtK.KAaaaaPpnaannnnnK....',
      '.......KK..KPPPPPPpnppnpppppK...',
      '...........KPPpppPPpppppppppK...',
      '............KKKKKKKKKKKKKKKK....',
      '................................',
      '................................',
    ],
  },
};
