import type { SpriteDef } from '../sprite';

export const DEATH_KNIGHT_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    N: 'night',
    a: 'darkSlate',
    M: 'gray',
    L: 'lightGray',
    W: 'white',
    C: 'cyan',
    B: 'blue',
    S: 'sand',
    t: 'tan',
    P: 'plum',
    p: 'deepBrown',
  },
  frames: {
    idle: [
      '....K...K...........K...........',
      '...KWK.KSK.........KSK..........',
      '..KWLMKKSSK.......KSSK..........',
      '..KWLMK.KtKKKKKKKKKtK...........',
      '..KWCMK.KttMMMMMMNttK...........',
      '..KWCMK..KKMaaaaaNKK............',
      '..KWLMK...KMaaaaaNK.............',
      '..KWLMK...KKCCCKaNK.K...........',
      '..KWLMK..KMMaaaaaNKKMK..........',
      '..KWCMK.KKMNNNNNNNKKMK..........',
      '..KWCMKKMMMMNNNNNMMMMNKKK.......',
      '..KWLMKKMaaaNMMMMMaaaNPPpK......',
      '..KWLMKKMaaaNaCaaMaaaNPPpK......',
      '..KWLMKKNNNNNCWCaNNNNNPPpK......',
      '.KKWLMKKNNNMaaCaaNpPPpPPpK......',
      'KMMMMMMNMMNNNNNNNNpPPpPPpK......',
      '.KMaaaNNNNNMMMMMMNpPPpPPpK......',
      '.KNNNNNKKKKMaaaaaNpPPpPPpK......',
      '..KKMKK...KNNNNNNNpPPpPPpK......',
      '....K....KMMMMNMMMNPPpPPpK......',
      '.........KNNNNNNNNNPPpPPpK......',
      '.........KMMMNKKaaNPPpPPpK......',
      '.........KMaaNKKaaNPPpPPpK......',
      '.........KNNNNKKNNNPPpPPpK......',
      '.........KMMMNKKMMNPPpPPpK......',
      '.........KMaaNKKaaNPPpPPpK......',
      '.........KMaaNKKaaNPPKKPpK......',
      '........KKNNNNKKNNNPPKKPpK......',
      '.......KMMMMMNKKaaaNPK.KK.......',
      '.......KNNNNNNKKNNNNK...........',
      '........KKKKKK..KKKK............',
      '................................',
    ],
    attack: [
      '...........K...........K........',
      '..........KSK.........KSK.......',
      '........KKKSSK.......KSSK.......',
      '......KKBBKKtKKKKKKKKKtK........',
      '.....KBBBK.KttMMMMMMNttK........',
      '....KBBBK...KKMaaaaaNKK.........',
      '...KBBBK.....KMaaaaaNK..........',
      '...KCBBK.....KKCCCKaNK.K........',
      '..KCBBK.....KMMaaaaaNKKMK.......',
      '..KCBBK....KKMNNNNNNNKKMK.......',
      '.KCBBBK...KMMMMNNNNNMMMMNKKK....',
      '.KCBBBK...KMaaaNMMMMMaaaNPPpK...',
      '.KCBBBBK..KMaaaNaCaaMaaaNPPpK...',
      '.KCCBBBBK.KNNNNNCWCaNNNNNPPpK...',
      '.KCCBBBBMKKNNNMaaCaaNpPPpPPpK...',
      '.KWWWWWWMMMMMNNNNNNNNpPPpPPpK...',
      'KLLCLCLLMMaaaNMMMMMMNpPPpPPpK...',
      '.KMMMMMMMNNNNNMaaaaaNpPPpPPpK...',
      '..KKKKKKNKKKKNNNNNNNNpPPpPPpK...',
      '........K...KMMMMNMMMNPPpPPpK...',
      '............KNNNNNNNNNPPpPPpK...',
      '............KMMMNKKaaNPPpPPpK...',
      '............KMaaNKKaaNPPpPPpK...',
      '............KNNNNKKNNNPPpPPpK...',
      '............KMMMNKKMMNPPpPPpK...',
      '............KMaaNKKaaNPPpPPpK...',
      '............KMaaNKKaaNPPKKPpK...',
      '...........KKNNNNKKNNNPPKKPpK...',
      '..........KMMMMMNKKaaaNPK.KK....',
      '..........KNNNNNNKKNNNNK........',
      '...........KKKKKK..KKKK.........',
      '................................',
    ],
  },
};
