import type { SpriteDef } from '../sprite';

export const DEMON_LORD_SPRITE: SpriteDef = {
  width: 48,
  height: 48,
  legend: {
    K: 'black',
    W: 'white',
    L: 'lightGray',
    M: 'gray',
    A: 'slate',
    a: 'darkSlate',
    n: 'night',
    R: 'red',
    r: 'darkRed',
    P: 'pink',
    e: 'deepBrown',
    Y: 'yellow',
    o: 'gold',
    O: 'orange',
    T: 'sand',
    t: 'tan',
    x: 'brown',
    b: 'darkBrown',
    H: 'hotRed',
  },
  frames: {
    idle: [
      '.........KK...KK................KK..............',
      '........KOOK.KTTK..............KTTK.............',
      '..KKK..KOOOOKOTTK..............KTtK........KKKK.',
      '.KPPPKKKOooOOOTTK.....KKKKKKKKKTttK.....KKKePPPK',
      '.KPRrPPPooLoOOTxTKKKKKPPPPrxxxxbbK.....KeePrrPRK',
      '.KeeeOrroLLMMOKTxTTTTPRRRRPrrbbbbK....KerrreeeK.',
      '.KeeeOOOLLLMMOOTxxxxPRRRRRRPrrbbK....KerrreeeeK.',
      '.KeeeeOoLLLMMoOOTxxeeeePReeeerKK....KPrreeeeeeK.',
      '.KeeeeOoLWLMMoOOKKTeYYePRYYerrK....KPrreeeeeeeK.',
      '.KeeeeOoLWAMMoOOKKKPRRPRRRRrrrK...KPrreeeeeeeeK.',
      '.KeeeOOoLWAMMoOrPPKPRRrPRRRrrK...KPrreeeeeeeeeK.',
      '.KeeOOOoLWAMMoOerrPKeWeeeWerrK..KMrreeeeeeeeeeK.',
      '.KeeOOooLWAMMoOOerLPeeWeeWrrK..KPMreeMeeeeeeeeK.',
      '.KeeeOooLWAMMoOOeeLrPePPPrrrK.KPrMeeeMeeeeeeeeK.',
      '.KeeeOooLWAMMoOOaaLaPPeeeePrrKPrrMMnnMneeeeeeeK.',
      '.KeeeeooLWAMMoOAAAAAaPPPPPRrrrPraaaaaaaneeeeeeK.',
      '..KeeeOoLWAMMoOAAAAAaPRRRRRPPPRraaaaaaaneeeeeK..',
      '..KeeOOoLWAMMoPPPAAaaPRRRRRRRRRrnaaaaanneeeeeK..',
      '..KeKOOoLWAMMPRRRPPPaPRRRRRRRRRrnnnnnnnneeeeeK..',
      '...KKOOOLWAMMRRRRRRaPRRRRRRRRRRrrnnnnnnrreeKeK..',
      '..KPPPOOLWAMRRRRRRRPRRRRRRRRReeerrrrrrrerrrrrK..',
      '...KKKeOLWAMRRRRRRRRrrrrrrPeeeerrrrrrrreeeKKrrK.',
      '.....KKeLWAMRRRRRRPRPPPPPPRPPPPrrrraaaaaaeK.KK..',
      '....KaaKLHHnnnnRRRrPRRRRRRrPRRRrrrrnnnnneK......',
      '....KAAAAHHnnnnRRrePRRRRRRrPRRRrrrrnnnnnrK......',
      '....KaaaaaannRRRrKKPRRrrrrreeeerrrKnnnnnrrK.....',
      '.....KKRRRRRrRRKK..KPRPPPPrPPPPrrKKrrrrKKK......',
      '......KPRRRRrRrK...KPRRRRRrPRRRrrKKrrrrK........',
      '......KRRRRrrKK....KPRRRRooooPRrrKKPPPPPK.......',
      '.......KKeeeK......KnnnnnoOOonnnnnKrrrrrK.......',
      '........KeeeK......KnnnnnoOOonnnnnKrrrrrK.......',
      '.......KoooooK.....KrAAAaooooaaaeKKrrrrrK.......',
      '.......KoooooK.....KrrAAaeeeaaaeeK.KKKKK........',
      '........KKKKK......KrrAAaeeeaaaeeK..............',
      '...................KrrAAaeeeaaaeeK..............',
      '...................KrrAAaeeeaaaeeK..............',
      '...................KrrrAaaeaaaeeeK..............',
      '...................KrrrAaaeaaaeeeKK.............',
      '..................KAAAAAAAeKaaaaaaaK............',
      '..................KaaaaaaKeKnnnnnnK.............',
      '..................KaaaaaaKeKnnnnnnK.............',
      '...................KaaaaaKKKnnnnnK..............',
      '...................KaaaaaK.KnnnnnK..............',
      '..................KKaaaaaK.KnnnnnKKK............',
      '.................KaaaaaaaaKKnnnnnnnnK...........',
      '.................KnnnnnnnnKKnnnnnnnnK...........',
      '..................KKKKKKKK..KKKKKKKK............',
      '................................................',
    ],
    attack: [
      '..............KK................KK..............',
      '.............KTTK..............KTTK.............',
      '.............KTTK..............KTtK.............',
      '..KKK........KTTK.....KKKKKKKKKTttK........KKKK.',
      '.KPPPKKKK....KTxTKKKKKPPPPrxxxxbbK......KKKePPPK',
      '.KPRrPPPeK....KTxTTTTPRRRRPrrbbbbK.....KeePrrPRK',
      '.KeeeerrrPKK..KTxxxxPRRRRRRPrrbbK.....KerrreeeK.',
      '.KeeeeeerrPPKK.KTxxeeeeRReeeerKK.....KPrreeeeeK.',
      '.KeeeeeeeerrPPKKKKTeYYeRRYYerrK....KKPrreeeeeeK.',
      '.KeeeeeeeeeerrPPK.KPRRPRRRRrrrK...KPPrreeeeeeeK.',
      '.KeeeeeeeeeeerrrPKKPRRrRRRRrrK...KPrreeeeeeeeeK.',
      '.KeeeeeeeeeeeeLrrPPKeWeeeWerrK..KMrreeeeeeeeeeK.',
      '.KeeeeeeeeeeeeLerrLPeeWeeWrrK..KPMreeMeeeeeeeeK.',
      '.KeeeeeeeeeeeeLeerLrPeRPPrrrK.KPrMeeeMeeeeeeeeK.',
      '.KeeeeeeeeeeeeLLaALARPeeeePrrKPrrMMnnMneeeeeeeK.',
      '.KeeeeeeeeeeeAAAAAAAARPPPPRrrrRrAaaaaaaneeeeeeK.',
      '..KeeeeeeeePPAAAAAAAaRRRRRRPPPRraaaaaaaneeeeeK..',
      '..KeeeeeeePAAaAAAAAaaRRRRRRRRRRrnaaaaanneeeeeK..',
      '..KeKeeRRRrenaaaaaaaaRRRRRRRRRRrnnnnnnnneeeeeK..',
      '...KKKPRRRrennaaaaaaPRRRRRRRRRRrrnnnnnnrreeKeK..',
      '..KPPPRRRrrennRRRRPPRRRRRRRRReeerrrrrrrerrrrrK..',
      '...KKKerrrRnnnRreePRrrrrrrReeeerrrrrrrreeeKKrrK.',
      '....KAaaKKKrrreeeePRPPPPPPRPPPPrrrrAAAAaaeK.KK..',
      '....KaaaAAAAeeeKKerPRRRRRRrRRRRrrrrnnnnneK......',
      '...KOOOLaaaaaaKKPrePRRRRRRrRRRRrrrrnnnnnrK......',
      '...KOooMMLWaaaKPrKKPRRrrrrreeeerrrKnnnnnrrK.....',
      '..KOOooMMLWKKKPKK..KPRPPPPrPPPPrrKKrrrrKKK......',
      '..KOOoLMMWLKKPrK...KPRRRRRrRRRRrrKKrrrrK........',
      '..KOooLMLWLK.KK....KPRRRRooooRRrrKKPPPPPK.......',
      '..KOooMMLWK........KnnnnnoOOonnnnnKrrrrrK.......',
      '..KOooMMLLK....KK..KnnnnnoOOonnnnnKrrrrrK.......',
      '.KOOoLMLWLK...KYOK.KrAAAaooooaaaeKKrrrrrK.......',
      '.KOOoLMLWK....KOOK.KrrAAaeeeaaaeeK.KKKKK........',
      '.KOooMMLWK...KKKK..KrrAAaeeeaaaeeK..............',
      '.KOooMLWOOKKKOOK...KrrAAaeeeaaaeeK..............',
      '.KOooMLWoooOOOOK...KrrAAaeeeaaaeeK..............',
      '.KOoMMLWooooooOK...KrrrAaaeaaaeeeK..............',
      'KOooMLLoYYoooooK...KrrrAaaeaaaeeeKK.............',
      'KOooMLWYYYYYoooOK.KAAAAAAAeKaaaaaAAK............',
      'KOOoMLWWWWYYYoooOKKaaaaaaKeKnnnnnnK.............',
      '.KKMLLYWWWYYYooOOOKaaaaaaKeKnnnnnnK.............',
      '..KMLLYWWWYYoooKKK.KaaaaaKKKnnnnnK..............',
      '..KLLoooYYooooK....KaaaaaK.KnnnnnK..............',
      '...KLOOKoooOOK....KKaaaaaK.KnnnnnKKK............',
      '....KKK.KKKOOK...KAAaaaaaAKKnnnnnnnnK...........',
      '...........KK....KnnnnnnnnKKnnnnnnnnK...........',
      '..................KKKKKKKK..KKKKKKKK............',
      '................................................',
    ],
  },
};
