import type { SpriteDef } from '../sprite';

export const DRUID_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    E: 'sand',
    F: 'tan',
    b: 'darkBrown',
    B: 'brown',
    T: 'tan',
    p: 'deepBrown',
    G: 'green',
    g: 'midGreen',
    d: 'darkGreen',
    S: 'skin',
    s: 'skinShade',
  },
  frames: {
    idle: [
      '.......KEK.KEKK.K...............',
      '........KEKEKKFKFK..............',
      '.........KEK..KFK.....KKK.......',
      '.........KEK...K.....KGgGK......',
      '..........KbbbbbbK..KGgGgGK.....',
      '.........KbBBSSSSsK.KgGpGgK.....',
      '.........KbBSSSKSsK..KgpgK......',
      '.........KbBSSSSSSSK..KpK.......',
      '.........KbBSSSSSsK...KbK.......',
      '.........KbBbbbbbK....KpK.......',
      '........KKKbBbbbK.....KbK.......',
      '.......KGgKGgKGgK.....KpK.......',
      '.......KggdggdggdK....KbK.......',
      '........KgdBgdBgdBpK..KpK.......',
      '........KTBBBBBBpBBpK.KbK.......',
      '........KTBBBBBBpKBBpKKpK.......',
      '.......KTBBBBBBBBpKBpSSbS.......',
      '.......KTBBBBBBBppKKKsKpK.......',
      '.......KTBBBBBBBppK..KKbK.......',
      '.......KggggggggggK...KpK.......',
      '......KTTBBbBBBBBppK..KbK.......',
      '......KTTBBbBBBBBppK..KpK.......',
      '......KTTBBbBBbBBppK..KbK.......',
      '......KTTBBbBBbBBppK..KpK.......',
      '......KTTBBbBBbBpppK..KbK.......',
      '.....KTTBBBbBBbBBpppK.KpK.......',
      '.....KTTBBBbBBbBBpppK.KbK.......',
      '.....Kg.g.g.g.g.g.g.g.KpK.......',
      '......KKKKbbKKKbbKKKK.KbK.......',
      '.........KbbK.KbbK.....K........',
      '.........KKKK.KKKK..............',
      '................................',
    ],
    attack: [
      '.......KEK.KEKK.K...............',
      '........KEKEKKFKFK..............',
      '.........KEK..KFK.......KKK.....',
      '.........KEK...K.......KGgGK....',
      '..........KbbbbbbK....KGgGgGK...',
      '.........KbBBSSSSsK...KgGpGgK...',
      '.........KbBSSSKSsK....KgpgK....',
      '.........KbBSSSSSSSK....KpK.....',
      '.........KbBSSSSSsK.....KbK.....',
      '.........KbBbbbbbK......KpK.....',
      '........KKKbBbbbK.......KbK.....',
      '.......KGgKGgKGgK.......KpK.....',
      '.......KggdggdggdK......KbK.....',
      '........KgdBgdBgdBpK....KpK.....',
      '........KTBBBBBBpBBpK...KbK.....',
      '........KTBBBBBBpKBBpK..KpK.....',
      '.......KTBBBBBBBBpKBpBSSSbS.....',
      '.......KTBBBBBBBppKKKs.sKpK.....',
      '.......KTBBBBBBBppK..K.KKbK.....',
      '.......KggggggggggK.....KpK.....',
      '......KTTBBbBBBBBppK....KbK.....',
      '......KTTBBbBBBBBppK....KpK.....',
      '......KTTBBbBBbBBppK....KbK.....',
      '......KTTBBbBBbBBppK....KpK.....',
      '......KTTBBbBBbBpppK....KbK.....',
      '.....KTTBBBbBBbBBpppK...KpK.....',
      '.....KTTBBBbBBbBBpppK...KbK.....',
      '.....Kg.g.g.g.g.g.g.g...KpK.....',
      '......KKKKbbKKKbbKKKK...KbK.....',
      '.........KbbK.KbbK.......K......',
      '.........KKKK.KKKK..............',
      '................................',
    ],
  },
};
