import type { SpriteDef } from '../sprite';

export const ELDER_WYRM_SPRITE: SpriteDef = {
  width: 48,
  height: 48,
  legend: {
    K: 'black',
    R: 'red',
    r: 'darkRed',
    e: 'deepBrown',
    O: 'orange',
    o: 'gold',
    Y: 'yellow',
    W: 'white',
    T: 'sand',
    t: 'tan',
    x: 'orangeBrown',
    u: 'rust',
    b: 'darkBrown',
  },
  frames: {
    idle: [
      '....................KKK.........................',
      '...................KrrtK.........KK.............',
      '................KKKbrrK.........KTRK............',
      '.............KKKbrrrrrK.........KReeKKKK........',
      '...........KKrrrrbbrrrK........KROeeeeeeKKKK....',
      '..........KrrbbbbrrerrrK...KK..KROreeuuueeeeKK..',
      '..........KbbbbbreererrK..KTTKKRORrereuuuuuueeK.',
      '...........KbeereeerbrrK..KTWKKROuruereruuuuKK..',
      '...........KeereeerebrrK.KTTK.KORurrerrerrruK...',
      '..........KbereeeerebrrKKTTK.KRORuuruerrerrrK...',
      '.........KbrreeeereebrrTTTK..KROuuurreuurerrK...',
      '........KbrbeeeeerebbrTTWK...KORuuurreuuureruK..',
      '........KrbbeeeereebbTTWTK..KROuuuurrreuuureuK..',
      '.........KKbeeeereeTTWWTK...KORuuuurrreuurrueK..',
      '...........KbeereeTTWTTrK..KRttuuuurrrreurruueK.',
      '............KbbreTTWTbTrKKKttttuuuurrrrerrruueeK',
      '............KbrbROOOOTTttttttRuuuuurrrrrerruKKK.',
      '.........KKKKOOOORRRRRtttttRORuuuuurrrrrerrK....',
      '........KOOOORRRRRRRRRttttTORuuuuuuurrrreruK....',
      '.......KORRRReeeeeRRRRRrrTTORuuuuuuurrrrueuK....',
      '......KRRRRRRRWYYeRRRRROTTTRuuuuuuuurrruueuK....',
      '......KReeRRRRRRRRRRRRRTTTRRuuTuuuTuruuuuueK....',
      '......KRRRRRRRRRRrRRRTTtROTKKTTuuTTuuTTuuueK....',
      '......KRRRRRRRRRWRRrrrTTRRRKKTTtOTTtTTTTuuueK...',
      '......KeeeeeeeeeeeeRRRRRRRRRORRRRRrOOTTtTTeeK...',
      '.......KrWrrrWrrrrrrRRrRRRrRRRrRRRRRRrOOTTTK....',
      '........KorrrrrrrrrrrRRrRRRrRRRrRRRRRRRrTTtK....',
      '.........KooooooooooRRRRRRRRRRRRRRRRRRRRrOK.....',
      '..........KKKKKKrrrrRRRRrRRRrRRRrRRRORRRrrK.....',
      '...............KRORRrrrrRrRRRrRRRrOORRRRRrK.....',
      '...............KRORRRRRRRRRRRRRRRORRRRRRRRRK....',
      '...............KORrRRRRreRrRRRrRORrRRRrRRRRrK...',
      '..............KRORRrRRRreRRrRRRrORRrRRRrRRrRK...',
      '..............KORRRRRRRrerRRRRRRORRRRRRRRRrRK...',
      '..............KORRRRRRRrerrrrrrrORRRrRRRrRrrRK..',
      '..............KORRRrrRrrerrrrrrrRRRRRrRRRrrrRK..',
      '..............KORRrRRRrYerrrrrrrRRRRRRRRRRrrrRK.',
      '..............KORRRRRRroeYYYrrrrRRrRRRrRRrrrrRK.',
      '..............KORRRRRRroooooYYYYrRRrRRRrrrrrrrK.',
      '..............KORRRRRrooxooxooxoYYORRRRrrrrrrrK.',
      '..............KORRRRRrKKKooxooxooRORrRRrrrrrRK..',
      '..............KRRRRRrRK..KKKKKKKOORRRrRrrrrRrK..',
      '.............KRRRRRRrK.KKTTKKKKKrORRRRrrrrRreK..',
      '............KRRRRRRRrKKTTTWRRRRRRORRRRrRrRreK...',
      '...........KRRRRRRRRRTTTTtTrrrrrRRRRRRrrreeK....',
      '...........KTRTRTrrrrrKKTTteeeeeRRRRrrrrerK.....',
      '...........KWKWKWKKKKK..KKTKKKKWKWKWKKKKKK......',
      '............K.K.K.........K....K.K.K............',
    ],
    attack: [
      '....................KKK.........................',
      '...................KrrtK.........KK.............',
      '................KKKbrrK.........KTRK............',
      '.............KKKbrrrrrK.........KReeKKKK........',
      '...........KKrrrrbbrrrK........KROeeeeeeKKKK....',
      '..........KrrbbbbrrerrrK.......KROreeuuueeeeKK..',
      '..........KbbbbbreererrK......KRORrereuuuuuueeK.',
      '...........KbeereeerbrrK......KROuruereruuuuKK..',
      '...........KeereeerebrrK......KORurrerrerrruK...',
      '..........KbereeeerebrrK.....KRORuuruerrerrrK...',
      '.........KbrreeeereebrrK.....KROuuurreuurerrK...',
      '........KbrbeeeeerebbrrK.....KORuuurreuuureruK..',
      '........KrbbeeeereebbbrrK...KROuuuurrreuuureuK..',
      '.........KKbeeeereebbbrrK...KORuuuurrreuurrueK..',
      '...........KbeereeebbbrrK..KRORuuuurrrreurruueK.',
      '............KbbreebbbbrrK..KROuuuuurrrrerrruueeK',
      '............KbrbbebbbbrrK..KOTTuuuurrrrrerruKKK.',
      '.............KrbbbbbbbrrK.KRTTWuuuurrrrrerrK....',
      '..............KKbbbbbbrrKKTTTuuuuuuurrrreruK....',
      '................KKKbbbbTWWTORuuuuuuurrrrueuK....',
      '..................KTTTWWTTRRuuuuuuuurrruueuK....',
      '............KKKKKKTTWWTTTTRRuuTuuuTuruuuuueK....',
      '........KKKKOOOOOTTWTTTrTTTKKTTuuTTuuTTuuueK....',
      '......KKOOOORRRRRRRRTTTTTTTKKtttOTTtTTTTuuueK...',
      '.....KORRRRRRRRRRRRRRRttttttttttRRrOOTTtTTeeK...',
      '....KORRRRRRReeeeeRRRRttttttRRRRRRRRRrOOTTTK....',
      '...KRReeRRRRRRWYYeRRRRRttRRRRRRRRRRRRRRrTTtK....',
      '...KRRRRRRRRRRRRRRRRRRRTTRRRrRRRrRRRRRRRrOK.....',
      '..KKORRRRRRRRRRRRRRRRTTTTrRRRrRRRrRRORRRrrK.....',
      '.KROOYYYYrrrrrrrrrerRRTtrrrRRRRRRROORRRRRrK.....',
      '.KOOoYWYYWOOWOeeeeerrRTTRRRRRRrRRORRRRrRRRRK....',
      'KOOoYYYYOOOOeeeeerrrrrRrRRreRRRrORRRRRRrRRRrK...',
      'KOoYWYOOOOeeeerrrrrrreRRRRreRRRRORRRRRRRRRrRK...',
      'KOoWWOOOeeeerrWrrrrreRRRrRreRRRRORRRrRRRrRrRK...',
      'KRoWYOeeeerrrrrrroreRrRRRrrerrrrORRRRrRRRrrrRK..',
      'KOoWYeeerrWrrrrooreRRRrrRrrerrrrRRRRRRRRRRrrRK..',
      'KOoYYerrrrrooooreeORRrRRRrrerrrrRRrRRRrRRRrrrRK.',
      'KOoYYrWrooorreeeKKORRRRRRrYerrrrRRRrRRRrRrrrrRK.',
      'KOoYYroorreeeKKK.KORRRRRRrooYYYYrRRRRRRRrrrrrrK.',
      'KRooYYooOeeKK....KORrRRRrooxooxoYYORrRRrrrrrrrK.',
      'KOOoYYYoOOOK.....KORRrRRrooxooxooRORRrRrrrrrRK..',
      '.KOooYYooOOOKK...KRRRRRrRRRKKKKKOORRRRRrrrrRrK..',
      '.KOOooYYooOOORK.KRrRRRRrTTTKKKKKrORRRRrrrrRreK..',
      '.KOOOoooooOOOK.KRRRrRRRrTTWRRRRRRORRRRrRrRreK...',
      '..KOOOOooOOORKKRRRRRRRRRTtTrrrrrRRRRRRrrreeK....',
      '...KOOOOOOOKK.KTRTRTrrrrrTteeeeeRRRRrrrrerK.....',
      '...KRKKKKKK...KWKWKWKKKKKKTKKKKWKWKWKKKKKK......',
      '....K..........K.K.K......K....K.K.K............',
    ],
  },
};
