import type { SpriteDef } from '../sprite';

export const FROST_WOLF_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    W: 'white',
    L: 'lightGray',
    M: 'gray',
    C: 'cyan',
    B: 'blue',
    K: 'black',
    R: 'red',
    r: 'darkRed',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '........K..K....................',
      '.......KWKKWK...................',
      '......KWLKWLMK..................',
      '......KWLWLLMK..................',
      '.....KWLLLLLLMK.................',
      '..KKKWLLLLLLLMK.....K.....K.....',
      '.KWWLLCKLLLLLLMK...KCK...KCK....',
      '.KLLLLLLLLLLLLMKKKKCBCKKKCBCKK..',
      '.KMMMMMLLLLLLLLWWWWCBCWWWCBCWWK.',
      '..KKKMMWWLLLLLLLLLLLLLLLLLLLLWWK',
      '.....KMWWWWLLLLLLLLLLLLLLLLLMWLK',
      '.....KMWWWWLLLLLLLLLLLLLLLLLMWLK',
      '.....KMWWWWLLLLLLLLLLLLLLLLMKWLK',
      '.....KWWWWLLLLLLLLLLLLLLLLLMKLMK',
      '......KWWMMLLLLLLLLLLLLLLLMLKLMK',
      '......KMMMMMMLLLLLLLLLLMMMMLKMMK',
      '.......KMMKMMMMMMMMMMMMMMLMK.KK.',
      '.......KLMKKKLMKKKKKKLMKKLMK....',
      '.......KLMK.KLMK....KLMKKLMK....',
      '.......KLMK.KLMK....KLMKKLMK....',
      '......KCLMKKCLMK...KCLMKCLMK....',
      '......KBBBKKBBBK...KBBBKBBBK....',
      '.......KKK..KKK.....KKK.KKK.....',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '.........K..K...................',
      '........KWKKWK..................',
      '.......KWLKWLMK.................',
      '.......KWLWLLMK.................',
      '..KKKKKWLLLLLLMK................',
      '.KWWWWLLLLLLLLMK....K.....K.....',
      '.KLLLLLLCKLLLLMK...KCK...KCK....',
      '.KWrWrrLLLLLLLMKKKKCBCKKKCBCKK..',
      '..KrRRRRLLLLLLLWWWWCBCWWWCBCWWK.',
      '.KWrWrMMWWLLLLLLLLLLLLLLLLLLLWWK',
      '.KMMMMMWWWWLLLLLLLLLLLLLLLLLMWLK',
      '..KKKKMWWWWLLLLLLLLLLLLLLLLLMWLK',
      '.....KMWWWWLLLLLLLLLLLLLLLLMKWLK',
      '.....KWWWWLLLLLLLLLLLLLLLLLMKLMK',
      '......KWWMMLLLLLLLLLLLLLLLMLKLMK',
      '.....KLMMMMMLLLLLLLLLLLMMMMLKMMK',
      '....KLMKKMMMMMMMMMMMMMMMKKLMKKK.',
      '...KLMK..KKKKLMKKKKKLMKK.KLMK...',
      '..KLMK.....KLMK.....KLMK..KLMK..',
      '.KLMK.....KLMK.......KLMK..KLMK.',
      'KCLMK....KCLMK.......KCLMKKCLMK.',
      'KBBBK....KBBBK.......KBBBKKBBBK.',
      '.KKK......KKK.........KKK..KKK..',
      '................................',
    ],
  },
};
