import type { SpriteDef } from '../sprite';

export const FROST_GIANT_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    W: 'white',
    L: 'lightGray',
    M: 'gray',
    A: 'slate',
    D: 'darkSlate',
    C: 'cyan',
    B: 'blue',
    N: 'navy',
    E: 'cyan',
    h: 'darkRed',
    d: 'darkBrown',
    b: 'brown',
    e: 'deepBrown',
    x: 'deepBrown',
  },
  frames: {
    idle: [
      '........KKKKK...................',
      '.......KWWWWLKKK.......K........',
      '......KLLLWWWWLMK.....KWK.......',
      '.....KLLMMMWWWLLMK...KWCBK......',
      '....KLMMMMMMWWLLMK...KWCBK.K....',
      '...KKDEDDEDMMWLLAK..KWCCBBKWK...',
      '..KWKMMMLMMAMWLMAK..KWCCBBKWBK..',
      '.KWCBLMMMMMAWWLMAK.KWCCCBBWCBNK.',
      '.KWCBWWWWWWWWWLAKKKKWCCCBBWCBNK.',
      'KWCCBBWBAAWWWWLAMMMWCCCBBNCCBNK.',
      'KWCCBWCBNWWWWWLALMNNCCBBNNBBNNK.',
      'KNCBBNBNNWWWWLALLLANNNNNNNNNNADK',
      '.KNNNNNNWLWWLALLMMMMMMMAADMMAADK',
      '.KLMMAAAWLWLAAAAAAMMAMMAADMMAADK',
      '.KLMMAAKCMCMMMMMMAMMMMAAADMMAADK',
      '.KWCCBNKMMMMMMMMMAMMMAAAADCBBNNK',
      '.KCCBBNKKMMMMMMMMAMMAAAAKKCBBNNK',
      '.KWCBNNKKAMMMMMMMAMAAAADKKBBNNNK',
      'KLLMMAAKKddddddddddddddddKMMAADK',
      'KLMMMAAKbbbbbbbbbbbbbbbbbLMMMADK',
      'KMMMAADKbebbbbbebbbbbbebbLMMMADK',
      '.KKbdKKKbbbbbbbbbbbbbbbbdMMAADDK',
      '..KbdK.KbKbbebbbbKbbbebdKKDDDDK.',
      '.KWWCBK.KMMMAAKKMMMAADKK..KKKK..',
      'KWCCCBWKKLMMAAKKMMMAADK.........',
      'KCWCCBBNKLMMAAKKMMAAADK.........',
      'KWCCCBBNKLMMAAKKMMAAADK.........',
      'KCCCBBNNKWWLLMKWWWLLMAK.........',
      'KWCBBNNNKWLLMMAWLLLMMAK.........',
      '.KNBNNKKKAAAAAKAAAAAAAK.........',
      '..KKKK...KKKKK.KKKKKKK..........',
      '................................',
    ],
    attack: [
      '..K..K..........................',
      '.KWKKWK....KKKKK.......K........',
      '.KWCWCBK..KWWWWLKKK...KWK.......',
      'KWCCCCBWKKLLLWWWWLMK.KWCBK......',
      'KWCCCBBNKDDMMMWWWLLMKKWCBK.K....',
      'KCCCBBNNDMMMMDMWWLLMKWCCBBKWK...',
      'KNCBBNNNDEDDEDMMWLLAKWCCBBKWBK..',
      '.KNNNNNKMMMLMMAMWLMAWCCCBBWCBNK.',
      '..KbdKKKLMMMMMAWWLMAWCCCBBWCBNK.',
      '.KLLLMALWWWWWWWWWLAWCCCBBNCCBNK.',
      'KLLMMMAAWxWxWxWWWLANCCBBNNBBNNK.',
      'KLMMMAADWxhhhxWWWLANNNNNNNNNNADK',
      'KWCCBNNKLxhhhxWWLAMMMMMAADMMAADK',
      'KCCCBBNKLMxxxWWLAAMMAMMAADMMAADK',
      'KWCCBNNLAMMWLWLAMAMMMMAAADMMAADK',
      '.KLMMMMMAMMCMCMMMAMMMAAAADCBBNNK',
      '.KMMMMMAAMMMMMMMMAMMAAAAKKCBBNNK',
      '..KAAAAAKAMMMMMMMAMAAAADKKBBNNNK',
      '...KKKKKKddddddddddddddddKMMAADK',
      '.......KbbbbbbbbbbbbbbbbbLMMMADK',
      '.......KbebbbbbebbbbbbebbLMMMADK',
      '.......KbbbbbbbbbbbbbbbbdMMAADDK',
      '.......KbKbbebbbbKbbbebdKKDDDDK.',
      '........KMMMAAKKMMMAADKK..KKKK..',
      '........KLMMAAKKMMMAADK.........',
      '........KLMMAAKKMMAAADK.........',
      '........KLMMAAKKMMAAADK.........',
      '........KWWLLMKWWWLLMAK.........',
      '........KWLLMMAWLLLMMAK.........',
      '........KAAAAAKAAAAAAAK.........',
      '.........KKKKK.KKKKKKK..........',
      '................................',
    ],
  },
};
