import type { SpriteDef } from '../sprite';

export const GARGOYLE_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    N: 'night',
    L: 'lightGray',
    G: 'gray',
    A: 'slate',
    D: 'darkSlate',
    W: 'white',
    Y: 'yellow',
  },
  frames: {
    idle: [
      '................................',
      '........................K.......',
      '.......................KLK......',
      '.............K........KLGK......',
      '............KLK......KLGGGK.....',
      '...........KLGKK....KLGDGGGK....',
      '..........KLGKKGK..KLGDDGGDGK...',
      '.........KLGKKGAK.KLGDDGDGDGNK..',
      '......KKKLGKKGAK.KLGDDDGDDGDGNK.',
      '.....KLLLGGGAKK.KLGDDDDGDDGDDGK.',
      '....KLLLLGGGAK..KLGDDDDGDDDGKK..',
      '...KLAYYAGGGAKKKLGDDDDDGDDDGK...',
      '..KLLGGGGGGGALLLGDDDDDDGDDDGNK..',
      '..KGKWKKGGGALGGGADDDDDDGDDDDGK..',
      '...KGGGGGALLGGGGGADDDDDGDDDDGK..',
      '....KAAAAKLGGGGGGGADDDGDDNKKK...',
      '.....KKKLLAGGGDGGGADDDGDNK......',
      '.......KLGAGGGGDGGGADDGNK...K...',
      '.......KLGAGGGGDGGGGAKGNK..KLK..',
      '......KLGGAGGGGGLLLLGAKK..KLGAK.',
      '......KLGGAGGGGLLGGGGGAK.KLGGGAK',
      '......KLGAGGGGLGGGGGDGGAK.KGAKK.',
      '......KLGAAGGGLGGGGGGDGAK.KGAK..',
      '......KLGAKAGGLGGGGGGGGAK.KGAK..',
      '.....KLGGAKKAALGGGGGGGAAKKGAK...',
      '....KLGGGAK.KLGGGGGAAALLGGAK....',
      '...KLGGGGAK.KLGGGGGGAKAAAAK.....',
      '...KGAAAAAK.KGGAAAAAAKKKKK......',
      '..KLKLKLKK.KLKLKKKKKK...........',
      '...K.K.K....K.K.................',
      '................................',
      '................................',
    ],
    attack: [
      '................................',
      '..................K.......K.....',
      '.................KLK....KKLK....',
      '................KLGGK..KNLGGK...',
      '...............KLGGGGKKNLGNGK...',
      '..............KLGDGDGGNLGGNGGK..',
      '.............KLGDDGDDGGGNGNGGNK.',
      '............KLGDDDGDDGDGNGNGNGK.',
      '.........K..KLGDDGDDDNGNGNNNGK..',
      '........KLKKLGDDDGDDDDGNGNNNGK..',
      '........KLGKLGDDDGDDDDDGGNNNGK..',
      '........KLLGLGDDDGDDNNNNGNKKK...',
      '....KKKKLLGGLGDDDGDNNNNGNK...K..',
      '...KLLLLGGGALKDDDGNKKKNGK...KLK.',
      '..KLAYYAGGGLLKKKDGK...KK..KKLGAK',
      '.KLLGGGGGGGLLLLLLLLKKKKK.KLGGGAK',
      '.KGKWKKGGGALGGGGGGGGDGLLKGAKAKK.',
      '..KGGGGGGALGGGGGGGGGDGGGAAK.K...',
      '...KAAAAKGGGGGDGGGGGGGGGGGAK....',
      '....KKLLLLAGGGGDGGGGGGLLLGAK....',
      '...KLLLGGGAAAGGGGGGGLGGGGGAK....',
      '..KLGGGAAKKKKKAAAAAAALGGGGAK....',
      '.KLGGAKKK.....KKKKKKKAGGGGGAK...',
      'KLKLKLK..............KKAAAAGAK..',
      '.K.K.K.................KKLKLK...',
      '.........................K.K....',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
};
