import type { SpriteDef } from '../sprite';

export const GHOST_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    W: 'white',
    L: 'lightGray',
    M: 'gray',
    A: 'slate',
    C: 'cyan',
    B: 'blue',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '............KKKKKK..............',
      '..........KKWWWWWLKK............',
      '.........KWWWWWWWWLLK...........',
      '........KWWWWWWWWWWLLK..........',
      '.......KWWWWWWWWWWWLLMK.........',
      '.......KWKKWWWKKWWWWLMK.........',
      '.......KWKCWWWKCWWWWLMK.........',
      '.......KWLLWWWLLWWWWLLMK........',
      '.......KWWWKKKWWWWWWLLMK........',
      '.....KKWWWWAKAWWWWWWLLMK........',
      '...KKWWWWWWWWWWWWWWWLLMK........',
      '..KWWWWLWWWWWWWWWWWWLLMK........',
      '..KLMKKWWWWWWWWWWWWWLLMK........',
      '...KK..KWWWWWWWWWWWWWLLMK.......',
      '.......KWWWWWWWWWWWWWLLMMK......',
      '.......KWWWWWWWWWWWWWWLLMK......',
      '........KWWWWWWWWWWWWWLLMMK.....',
      '........KWWWWWWWWWWWWWWLLMAK....',
      '........KWWWLKWWWLKWWLMKMMAK....',
      '.........KWWLKKWWLKKWLMKKMAK....',
      '..........KWLK.KWLK.KLMK.KAK....',
      '...........KLK..KLK..KMK..K.....',
      '............K....K....K.........',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '..........KKKKKK................',
      '........KKWWWWWLKK..............',
      '.......KWWWWWWWWLLK.............',
      '......KWWWWWWWWWWLLK............',
      '.....KWWWWWWWWWWWLLMK...........',
      '.....KWKKWWWKKWWWWLMK...........',
      '.....KWKCWWWKCWWWWLMK...........',
      '.....KWLLWWWLLWWWWLLMK..........',
      '.K...KWWKKKKWWWWWWLLMK..........',
      'KCKKKWWWKKKKWWWWWWLLMK..........',
      'CKWWWWWWAKKAWWWWWWLLMK..........',
      'KBLLMMWWWWWWWWWWWWLLMK..........',
      'CKKKKWWWWWWWWWWWWWLLMKK.........',
      'K....KKWWWWWWWWWWWWWLLMK........',
      '......KWWWWWWWWWWWWWLLMMK.......',
      '......KWWWWWWWWWWWWWWLLMK.......',
      '.......KWWWWWWWWWWWWWLLMMKK.....',
      '........KWWWWWWWWWWWWWWLLMAK....',
      '.........KWWWLKWWWLKWWLMKMMAK...',
      '..........KWWLKKWWLKKWLMKKMAK...',
      '...........KWLK.KWLK.KLMK.KAK...',
      '............KLK..KLK..KMK..K....',
      '.............K....K....K........',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
};
