import type { SpriteDef } from '../sprite';

export const GHOUL_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    M: 'gray',
    L: 'lightGray',
    A: 'slate',
    a: 'darkSlate',
    Y: 'yellow',
    r: 'darkRed',
    W: 'white',
    b: 'darkBrown',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '......KKKKKKK...................',
      '.....KLLLLLLMK..................',
      '.....KLaaaaaAK.KKKKKKK..........',
      '.....KLYMMYMAKKMLLLLLMK.........',
      '.....KLMMMMMAKKMMMMMMAAK........',
      '.....KMWrWrMAMKMMMMMMAAK........',
      '.....KMrWrrMAMLLMMMMMMAK........',
      '......KKKKKMMMMMMMMMMMAK........',
      '...........KMMMMMMMMMMK.........',
      '...........KMMMMMMMMMMAK........',
      '............KMMaaaaAAAAK........',
      '...........KMMMMMMMAAKAAK.......',
      '..........KMMMaaaaaAAKAAK.......',
      '.........KMMKMMMMMMAAKKAAK......',
      '.........KMMKMMMMMMAAKKAAK......',
      '........KMMKKbbbbbbbbKKWKWK.....',
      '......KKMMK.KbbbbbbbbK.K.K......',
      '.....KWKKK...KMMKKKAAK..........',
      '......KWWK..KMMK..KAAK..........',
      '.......KK...KMMK...KAAK.........',
      '...........KMMK....KAAK.........',
      '..........KKMMK....KAAK.........',
      '.........KAAAAK...KaaaaK........',
      '..........KKKK.....KKKK.........',
      '................................',
    ],
    attack: [
      '................................',
      '......KK.K......................',
      '.....KWWKWK.....................',
      '....KWKKKK......................',
      '.....KKMMK......................',
      '......KMMK......................',
      '.......KMMK.....................',
      '...KKKKKMMK.....................',
      '..KLLLLLLMMK....................',
      '..KLaaaaaMMKKKKKKKK.............',
      '..KLYMMYMAMMMLLLLLMK............',
      '..KLMMMMMAMMMMMMMMAAK...........',
      '..KMWrWrWAMMMMMMMMAAK...........',
      '..KMrrrrrAMMMMMMMMMAK...........',
      '...KrWrWrMMMMMMMMMMAK...........',
      '....KKKKKMMMMMMMMMMK............',
      '........KMMMMMMMMMMAK...........',
      '.........KMaaaaaAAAAK...........',
      '.........KMMMMMMAAKAAK..........',
      '.........KMaaaaaAAKAAK..........',
      '.........KMMMMMMAAKKAAK.........',
      '.........KMMMMMMAAKKAAK.........',
      '.........KbbbbbbbbKKWKWK........',
      '.........KbbbbbbbbK.K.K.........',
      '..........KMMKKKAAK.............',
      '.........KMMK..KAAK.............',
      '.........KMMK...KAAK............',
      '........KMMK....KAAK............',
      '.......KKMMK....KAAK............',
      '......KAAAAK...KaaaaK...........',
      '.......KKKK.....KKKK............',
      '................................',
    ],
  },
};
