import type { SpriteDef } from '../sprite';

export const GNOLL_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    n: 'night',
    T: 'tan',
    B: 'brown',
    b: 'darkBrown',
    e: 'deepBrown',
    K: 'black',
    W: 'white',
    R: 'red',
    s: 'skinShade',
    L: 'lightGray',
    M: 'gray',
    u: 'rust',
    O: 'gold',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '...........K..K.................',
      '..........KbKKbK................',
      '.........KbTbbTbK...............',
      '........KbTTbTTTbK..............',
      '.....KKKTTTTTTTTbeK.............',
      '...KKTTTTTKTTTTTbeeK............',
      '..KTTTTTTTTTTTTTbeeeK...........',
      '.KnTTTTTTTTTTTTbbeeeK...........',
      '..KWsWsWTTTTTTbbeeeeK...........',
      '..KKssssTTTTTbbbeeeeeK..........',
      '.KLLKKKKKTTBTTTbbeeeeeK.........',
      'KLMMLK.KTTTTTTBTTbeeeeK.........',
      'KLMMuKKTTBTTTTTTTTbeeK..........',
      '.KLKuKTTTTTTBTTTTTbbeK..........',
      '..KKuTTTbKTTTTBTTTbbbK..........',
      '...KuTTbKKTTTTTTTTbbbK..........',
      '...KsTbK.KeeeOeeeeebbK..........',
      '...KuKK..KTTBTTTTBTbK...........',
      '...KuK...KbTTTTTTTbK............',
      '....K....KbTTbKbTTbK............',
      '.........KbTTbKKbTTbK...........',
      '........KbTTbK..KbTTbK..........',
      '........KbTbK....KbTbK..........',
      '........KbTbK....KbTbK..........',
      '.......KbTbK....KbTbK...........',
      '......KeeebK...KeeebK...........',
      '.....KeeeebK..KeeeebK...........',
      '......KKKKK....KKKKK............',
      '................................',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '..........K..K..................',
      '.........KbKKbK.................',
      '........KbTbbTbK................',
      '.......KbTTbTTTbK...............',
      '....KKKTTTTTTTTbeK..............',
      '..KKTTTTTKTTTTTbeeK.............',
      '.KTTTTTTTTTTTTTbeeeK............',
      'KnTTTTTTTTTTTTbbeeeK............',
      '.KWRWRWKTTTTTbbeeeeKK...........',
      '..KRRRKKTTTTTbbbeeeeeK..........',
      '.KWRWRWTTBTTTTbbeeeeeK..........',
      'KKKKKKKTTTTTTBTTbeeeeK..........',
      'LLKKKTTTBTTTTTTTTbeeK...........',
      'LMuuuTTTTTTBTTTTTbbeK...........',
      'LMLsKuuTbKTTTTBTTTbbbK..........',
      'KLKK.KKKKTTTTTTTTbbbK...........',
      '.K......KeeeOeeeeebbK...........',
      '........KTTBTTTTBTbK............',
      '........KbTTTTTTTbK.............',
      '.......KbTTbKKbTTbK.............',
      '......KbTTbK..KbTTbK............',
      '.....KbTbKK....KbTTbK...........',
      '....KbTbK.......KbTbK...........',
      '...KbTbK........KbTbK...........',
      '..KeeebK.......KeeebK...........',
      '.KeeeebK......KeeeebK...........',
      '..KKKKK........KKKKK............',
      '................................',
      '................................',
    ],
  },
};
