import type { SpriteDef } from '../sprite';

export const GOBLIN_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    G: 'green',
    g: 'midGreen',
    d: 'darkGreen',
    t: 'deepTeal',
    Y: 'yellow',
    W: 'white',
    r: 'darkRed',
    O: 'orangeBrown',
    B: 'brown',
    b: 'darkBrown',
    n: 'deepBrown',
    L: 'lightGray',
    o: 'gold',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '.............KKKKK..............',
      '............KGGGggKK............',
      '...........KGGGGgggdK...........',
      '.....KK...KGGGGgggggdK.....KK...',
      '....KGgKK.KGGGggggggddKKKKKgdK..',
      '....KgGGgKKGGgggggggdddggggdK...',
      '.....KgdGGGttgggttggdddgddKK....',
      '......KKKKGgYYgggYYgddtKKK......',
      '.........KGgKYgggKYgddtK........',
      '.........KGggggGgggggdtK........',
      '.........KgggggdggggddtK........',
      '..........KgdWWtWWtddtK.........',
      '..........KdgtWrrrWtdtK.........',
      '..........KKggddddKKKKK.........',
      '........KKGGgOOBBBbggddK........',
      '..KKKKKKgGgdOOBBBBbbgddK........',
      '.KWLLLLnGGgKOBBBBBbbKgdK........',
      '..KKKKKngdKKnnnonnnnKgdK........',
      '.......KKK.KOBBBBbbnKGdK........',
      '...........KBBbBBbnKKddK........',
      '...........KGgbbbbgdKKK.........',
      '...........KGdKKKgdK............',
      '..........KKgdK..KgdK...........',
      '.........KGgdK..KGgdK...........',
      '..........KKK....KKK............',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '...........KKKKK................',
      '..........KGGGggKK..............',
      '.........KGGGGgggdK.............',
      '...KK...KGGGGgggggdK.....KK.....',
      '..KGgKK.KGGGggggggddKKKKKgdK....',
      '..KgGGgKKGGgggggggdddggggdK.....',
      '...KgdGGGttgggttggdddgddKK......',
      '....KKKKGgYYgggYYgddtKKK........',
      '.......KGgKYgggKYgddtK..........',
      '.......KGggggGgggggdtK..........',
      '.......KgggggdggggddtK..........',
      '........KgdWWtWWtddtK...........',
      '........KdtrrrrrrtdtK...........',
      'KKKKKKKKGdgWrrrWtdtddK..........',
      'WLLLLnGGGgggddddbbgddK..........',
      'KKKKKngdddOOBBBBbbKgdK..........',
      '.....KKKKKnnnonnnnKGdK..........',
      '.........KOBBBBbbnKddK..........',
      '........KGBBbBBbnK.KK...........',
      '.......KGgbbbbbgdK..............',
      '......KGdKKKKKKKgdK.............',
      '....KKgdK.......KgdK............',
      '...KGgdK........KGgdK...........',
      '....KKK..........KKK............',
      '................................',
    ],
  },
};
