import type { SpriteDef } from '../sprite';

export const GOBLIN_KING_SPRITE: SpriteDef = {
  width: 48,
  height: 48,
  legend: {
    B: 'brown',
    C: 'cyan',
    G: 'green',
    K: 'black',
    L: 'lightGray',
    M: 'gray',
    O: 'orange',
    R: 'red',
    W: 'white',
    Y: 'yellow',
    b: 'darkBrown',
    c: 'blue',
    d: 'darkGreen',
    e: 'deepBrown',
    g: 'midGreen',
    o: 'gold',
    r: 'darkRed',
    t: 'deepTeal',
    x: 'orangeBrown',
  },
  frames: {
    idle: [
      '...............K................................',
      '..............KYK....K..........................',
      '..............KYOK..KYK....K....................',
      '..............KYoOKKYoOK..KYK...................',
      '..............KYooOYYoOKKKYOK...................',
      '..............KYoooooooOYYoOK...................',
      '......K.......KYRroYoooooooOK..........K........',
      '.....KGKK....KGxxxxxCcoYRooOK........KKdK.......',
      '.....KGGgKK.KGGGGGGGxxxxxroOdK.....KKddgK.......',
      '......KGGggKKGGGGGGggggggxxxddK..KKddggdK.......',
      '.......KgGGggGGGGGggggggggdddddKKddgggdK........',
      '.....K..KddgGGGtttttggttttgdddddgggddKK.........',
      '...KKYKK.KddGGKYYYdggKYYYddddtddddKKK...........',
      '..KYYoOOKKKGGgKKYYdggKKYYgddddtKKK..............',
      '.KYooooOOGGGGgdgggggGggggggdddtK................',
      '.KYoRRroOGGggdggggggggggggggddtK................',
      'KYYoRrroOxtgddgdggggggggggggddtK................',
      '.KYoorroOdddgtWWtWWtWWtWWtggdtK.................',
      '.KOooooOxKKKdtWrrrrrrrrrrWtddtK.................',
      '..KOOxxxK..KddtWtWttWtttWtddtKKKKKKKK...........',
      '...KKxOK....KddddddddddddddtWWWWWMRReK..........',
      '....KoOK....KWWWWWWWWWWWWWWWWWWWWWWWWMK.........',
      '.....KoOK..KMWGWtWWWWWWWWWWWKWWWWWWWWMMK........',
      '.....KoOK..KRGGGtWWWWWKWWWWWWWWWWWKWMMtK........',
      '.....KYOK..KGGggtMWKMMWMMKWMMMWKMMMMMgtK........',
      '......KoOKKRGgggtGMMGGMMGGMMggMMddMGgggtK.......',
      '......KoOKKGGgggtGGGGGGGGGGggggggddGgggtK.......',
      '......KoOKKGgggttGGGGGGGGGGgggggggddtgggtK......',
      '.......KoOGGgggtGGGGGGGGGGGGggggggddtgggtK......',
      '.......KoGGGggttGGGGGGGGGGGggggggggddtgggtK.....',
      '.......KGGggGttgGGGGGGGGGGGggggggggddtgggtK.....',
      '......KGdddddtgggGGGGGGGGGggggggggdddtgggtK.....',
      '.......KGggtttgggggGGGGGggggggggggdddtGggtK.....',
      '........KtttrGdgggggggggdtgggggggdddttoooooK....',
      '........KRoOrrGdggggggggggggggggddddtrOOOOOK....',
      '.......KRRoOrrGddggggggYYYoggggddddttrGggtK.....',
      '.......KRrYOrrrYYYYYYYYoxxoOYYYYYYYxrrGGGGtK....',
      '.......KRrroOrrYooooooYxRrxOooooooxxrrGGggGK....',
      '......KRRrroOrrrxxxxxxxOOOxxxxxxxxxrrGGgggttK...',
      '......KRrrroOrrrxBBBBBBBBbBBBBBBbeerrrGggttK....',
      '......KRrrrroOrrrxBBBBBBBbBBBBBbberrrrrttteK....',
      '.....KRRrrrxxrrrrxbbbbbbbbbbbbbbeerrrrrreeeK....',
      '.....KRrrrrrrrrrrGeeeeeeebeeeeeeerrrrrrreeeK....',
      '.....KReeeeeeeeeeGgggteeeeeeGgggteeeeeeeeeeK....',
      '....KRReeeeeeeeGGGGGGteeeeGGGGGGteeeeeeeeeeeK...',
      '....KLLLLLLLLLLGgggggtLLLLGgggggtLLLLLLLLLLLK...',
      '.....KKKKKKKKKKtttttttKKKKtttttttKKKKKKKKKKK....',
      '...............KKKKKKK....KKKKKKK...............',
    ],
    attack: [
      '................................................',
      '.............K..................................',
      '............KYK....K............................',
      '............KYOK..KYK....K......................',
      '............KYoOKKYoOK..KYK.....................',
      '............KYooOYYoOKKKYOK.............KK......',
      '............KYoooooooOYYoOK............KGGK.....',
      '....K.......KYRroYoooooooOK..........KKGGgGK....',
      '...KGKK....KGxxxxxCcoYRooOK........KKddddddtK...',
      '...KGGgKK.KGGGGGGGxxxxxroOdK.....KKddgGggggtK...',
      '....KGGggKKGGGGGGggggggxxxddK..KKddggddddddtK...',
      '.....KgGGggGGGGGggggggggdddddKKddgggdKGGgttK....',
      '......KddgGGGGtttggggtttgdddddgggddKKKGgtttK....',
      '.......KddGtKYYYtggtKYYYdddtddddKKK..KGggtK.....',
      '.......KKGGgdKKYdggdKKYgddddtKKK.....KoooooK....',
      '......KGGGGgdgggggGggggggdddtK.......KOOOOOK....',
      '.....KGGGggdggggggggggggggddtK.......KGggtK.....',
      '....KGGgtgdtKKKKKKKKKKKKKgddtK......KGGggtK.....',
      '.....KddddtKWWKWWKWWKWWKKtdtK......KGGgggtK.....',
      '......KKKKtKKKrrrrrrrrKKKtdtKKKKKKKKGgggttK.....',
      '.........KdtKrrRRRRRrrrKtdtWWWWWWMRGGgggtK......',
      '.....K...KddtKWWKKKKWWKtddtWWWWWWWWWWMgttK......',
      '...KKYKK..KdddttttttttdddtWWKWWWWWWWWMMtK.......',
      '..KYYoOOK..KRMWWWWWWWWKWWWWWWWWWWWKWMMttK.......',
      '.KYooooOOK.KRrGGGGtKMMWMMKWMMMWKMMMMMgtK........',
      '.KYoRRroOKKRRrrGggtMGGMMGGMMggMMddMggttK........',
      'KYYoRrroOxYYrrGGGgtGGGGGGGGggggggddGtteK........',
      '.KYoorroOxooYGGggGtGGGGGGGGgggggggddteeK........',
      '.KOooooOxKxxGGgggttGGGGGGGGGggggggddteeK........',
      '..KOOxxxKKRrrGggtttGGGGGGGGggggggggddteeK.......',
      '...KKxKK.KRrrGtttttGGGGGGGGggggggggddteeK.......',
      '.....K..KRRrrGgggGGGGGGGGGggggggggdddteeK.......',
      '........KRrrrGgggggGGGGGggggggggggdddteeK.......',
      '........KRrrrGdgggggggggdtgggggggdddtteeeK......',
      '........KRrrrrGdggggggggggggggggddddtreeeK......',
      '.......KRRrrrrGddggggggYYYoggggddddttreeeK......',
      '.......KRrrrrrrYYYYYYYYoxxoOYYYYYYYxrreeeK......',
      '.......KRrrrrrrYooooooYxRrxOooooooxxrrreeeK.....',
      '......KRRrrrrrrrxxxxxxxOOOxxxxxxxxxrrrreeeK.....',
      '......KRrrrrrrrrxBBBBBBBBbBBBBBBbeerrrreeeK.....',
      '......KRrrrrrrrrrxBBBBBBBbBBBBBbberrrrrreeeK....',
      '.....KRRrrrrrrrrrxbbbbbbbbbbbbbbeerrrrrreeeK....',
      '.....KRrrrrrrrrrrGeeeeeeebeeeeeeerrrrrrreeeK....',
      '.....KReeeeeeeeeeGgggteeeeeeGgggteeeeeeeeeeK....',
      '....KRReeeeeeeeGGGGGGteeeeGGGGGGteeeeeeeeeeeK...',
      '....KLLLLLLLLLLGgggggtLLLLGgggggtLLLLLLLLLLLK...',
      '.....KKKKKKKKKKtttttttKKKKtttttttKKKKKKKKKKK....',
      '...............KKKKKKK....KKKKKKK...............',
    ],
  },
};
