import type { SpriteDef } from '../sprite';

export const HARPY_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    u: 'rust',
    r: 'darkRed',
    S: 'skin',
    s: 'skinShade',
    K: 'black',
    R: 'red',
    T: 'tan',
    B: 'brown',
    b: 'darkBrown',
    e: 'deepBrown',
    Y: 'yellow',
    G: 'gold',
    W: 'white',
  },
  frames: {
    idle: [
      '................................',
      '..KK........................KK..',
      '.KTTK......................KTTK.',
      '.KTTTK....................KTTTK.',
      '.KTTBbK......KKKK........KbBTTK.',
      'KTTTBBbK...KKuuuuK......KbBBTTTK',
      'KbTTTBBbK.KuuuuuuuK....KbBBTTTbK',
      '.KKbTTBbKKuuuuuuuurK...KbBTTbKK.',
      '.KTTTBBBbKuuSSSuuurrK.KbBBBTTTK.',
      '.KbTTTBBbKSKSSKsuurrK.KbBBTTTbK.',
      '..KKbTTBbKSSSSSsuurrK.KbBTTbKK..',
      '..KTTTBBbKKSRRSsuurrK.KbBBTTTK..',
      '..KbTTTBBbKKSSsuurrrKKbBBTTTbK..',
      '...KKbTTBBbKKssuurrrKbBBTTbKK...',
      '....KTTTBBBBBTTTTBBbBBBBTTTK....',
      '.....KKbTBBBBTTTTTBbBBBTbKK.....',
      '.......KKKKKBTTBTTBbKKKKK.......',
      '...........KBBTTTBBbK...........',
      '............KBTBBTbK............',
      '............KbBBBBbK............',
      '............KbBBBbbK............',
      '............KebBBbeK............',
      '............KbBbKbBK............',
      '.............KYKKYK.............',
      '.............KYKKYK.............',
      '.............KYKKYK.............',
      '..........KKKKYKKYKKK...........',
      '.........KYYYYYKYYYYYK..........',
      '........KWKWKWK.KWKWKWK.........',
      '.........K.K.K...K.K.K..........',
      '................................',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '..........................KKK...',
      '........................KKbBTK..',
      '......................KKbBTTTTK.',
      '.....................KbBBBBTTTTK',
      '....................KbBBBBBTTTTK',
      '........KKKKK......KbBBBbbbbKKK.',
      '.......KuuuuuKK...KbBBBBBTTTTK..',
      '......KuuuuuuurK.KbBBBBBBBTTTTK.',
      '.....KuuSSSuuurrKKbBBBBbbbbKKK..',
      '....KSKSSKsuurrKKbBBBBBBTTTTK...',
      '....KSSSSSsuurrKKbBBBBBBBTTTTK..',
      '.....KSRRSsuurrKbBBBBBbbbbKKK...',
      '......KSSsuurrKKbBBBBBBTTTTK....',
      '.......KssuurrKKbBBBBBBTTTTK....',
      '.......KBTTTTTBBBBBBBBBbbKK.....',
      '.......KBTTTTBBBBBBBbbTTTK......',
      '........KBTTBBBBbbbbTTTTK.......',
      '.........KbBBBBBBbbbbbKK........',
      '..........KbBbbbbbeKKK..........',
      '.........KYGKKYGKKK.............',
      '........KYGKKYGK................',
      '.......KYGKKYGK.................',
      '...KKKKYGKKYGKKK................',
      '..KYYYYYGKKYYYYGK...............',
      '.KWKWKWKKKWKWKWK................',
      '..K.K.K...K.K.K.................',
      '................................',
      '................................',
      '................................',
    ],
  },
};
