import type { SpriteDef } from '../sprite';

export const HYDRA_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    G: 'green',
    g: 'midGreen',
    k: 'darkGreen',
    t: 'deepTeal',
    S: 'sand',
    T: 'tan',
    r: 'hotRed',
    w: 'white',
    x: 'darkRed',
  },
  frames: {
    idle: [
      '...............K.K..............',
      '.............KKkKkK.............',
      '...........KKkGGGkkK............',
      '..........KgGGGrGgkK............',
      '.........KGGGGGGggkK............',
      '.........KwSSSSSgkkK............',
      '........K.KKSSSkkKK.............',
      '......KKkKkKKKKSGgkK............',
      '....KKkGGGkkK..KSGgkK...........',
      '...KgGGGrGgkK...KSGgkK..........',
      '..KGGGGGGggkK....KSGgkK.........',
      '..KwSSSSSgkkKK...KSGgkK...K.....',
      '...KKSSSkkSGgkK...KSGgkK.KkKK...',
      '.....KKKKKKSGgkK..KSGgkK..KgkK..',
      '......K.K..KSGgkK.KSGgkK...KgkK.',
      '....KKkKkK..KSGgkKKSGgkKK.KKGgkK',
      '..KKkGGGkkK.KSGgkKSGgktKtKtGGgkK',
      '.KgGGGrGgkK..KSGgkGGGGgggkkkgktK',
      'KGGGGGGggkKK..KGGGGgGGGgkggkkktK',
      'KwSSSSSgkkgkKKGGGgGGGgggkgggktK.',
      '.KKSSSkkKSGgkSGGGGGgGggkggkkktK.',
      '...KKKKK.KSGgkSGGgGGgggkggkktK..',
      '..........KSGgkSGGgggkggkkkttK..',
      '...........KKTSSSSgggkggkkkttK..',
      '............KGTTSSSSSSgkkkktK...',
      '............KGgTTTSSSSSkkttkK...',
      '...........KGGgkkKKKKKKGggkkK...',
      '...........KGggkkK....KggkktK...',
      '..........KwGwgwkK...KwGwgwtK...',
      '...........KKKKKK.....KKKKKK....',
      '................................',
      '................................',
    ],
    attack: [
      '................................',
      '.........K.K....................',
      '.......KKkKkK...................',
      '.....KKkGGGkkKKKK...............',
      '....KgGGGrGgkKGGkKK.............',
      '...KGGGGGGggkGGgGgkK............',
      '...KwKwKxxxgkggggggkK...........',
      '....K.KKxxxkkSSSSSggkK..........',
      '...KwKwKSSgkKKKKKKSGgkK.........',
      '...KSSSSSkkK......KSGgkK........',
      '....KKKKKKK.......KSGgkK........',
      '....KKkKkK........KSGgkK..K.....',
      '..KKkGGGkkKKK.....KSGgkK.KkKK...',
      '.KgGGGrGgkGGkK....KSGgkK..KgkK..',
      'KGGGGGGggkggGkK...KSGgkK...KgkK.',
      'KwKwKxxxgkSggGkK..KSGgkKK.KKGgkK',
      '.K.KKxxxkkKSSggkKKSGgktKtKtGGgkK',
      'KwKwKSSgkK.KKSggkGGGGGgggkkkgktK',
      'KSSSSSkkK....KKGGGGgGGGgkggkkktK',
      '.KKKKKKKK....KGGGgGGGgggkgggktK.',
      '....KKkKkKKKKSGGGGGgGggkggkkktK.',
      '..KKkGGGkkGGGkSGGgGGgggkggkktK..',
      '.KgGGGrGgkggggSSGGgggkggkkkttK..',
      'KGGGGGGggkSSSSSSSSgggkggkkkttK..',
      'KwKwKxxxgkKKKGTTSSSSSSgkkkktK...',
      '.K.KKxxxkkK.KGgTTTSSSSSkkttkK...',
      'KwKwKSSgkK.KGGgkkKKKKKKGggkkK...',
      'KSSSSSkkK..KGggkkK....KggkktK...',
      '.KKKKKKK..KwGwgwkK...KwGwgwtK...',
      '...........KKKKKK.....KKKKKK....',
      '................................',
      '................................',
    ],
  },
};
