import type { SpriteDef } from '../sprite';

export const ICE_QUEEN_SPRITE: SpriteDef = {
  width: 48,
  height: 48,
  legend: {
    K: 'black',
    W: 'white',
    L: 'lightGray',
    M: 'gray',
    A: 'slate',
    a: 'darkSlate',
    n: 'night',
    N: 'navy',
    B: 'blue',
    C: 'cyan',
    P: 'pink',
    p: 'magenta',
  },
  frames: {
    idle: [
      '......................K.........................',
      '..............K......KCK........................',
      '....K........KCK...KKWBK.K......................',
      '...KCK......KCWCK.KCWWBKKCK.....................',
      '..KCWCK..K...KCK..KBWWBCBBK.....................',
      '...KCK..KCK...K..KWBWWBBWBKKK...................',
      '....K..KWBCK....KKWBCWBBWBCCCK..................',
      '......KCWBBCK..KCWWBCWBBCBBCWK..................',
      '.....KCWWBBBCK.KWWWWWWWCWWWWWLK.................',
      '....KCCCWNNNNK.KLLBLLLCCLLMBMMK.................',
      '.....KCCCNNNK...KWWWWWWWWWLLLLLK................',
      '......KCCNNK....KWLLLLLMWWLLLLLLK...............',
      '.......KCNK.....KnnLnnLMWCLLLCMMK...............',
      '........KKK.....KCnLCnLMWCLWLCMMLK..............',
      '........KLMK...KLLLLLLLMWCLWLLCMMK..............',
      '........KLMK...KLLLLLLMMWCLWLLCMMK..............',
      '........KLMK...KLLLLLLMWWCLLWLCMMLK.............',
      '........KCCK...KWpPLLMMWCLLLWLCMMMK.............',
      '........KLMK..KCLMLLMMWWCLLLWLLCMMK.............',
      '........KLMK.KLWWLLWMMWWCLLLWLLCMMMK............',
      '........KLMK.KLLLLLBWWWLBNMLLWLLCMMK............',
      '........KLMK.KLWLLLBBWWBBNMMLWLLCMMK............',
      '........KLMKKLWLLBCBBWCCBNNNLLWLMCMMK...........',
      '........KCCKKLWLLBCBBCCNBNNNaLWLLCMMK...........',
      '........KLMLLWLLLBCBBBBBBNNNaLLWLMCMMK..........',
      '........KLMLLWLLLBCBBBBBBNNNaaLWLLCMMK..........',
      '........KLMLWLLMKKBCBWCCBNNNaaaLWLMCMK..........',
      '........KWWLWMMK.KWWWCCCWWWLLaaLWLMCMMK.........',
      '.......KWWWWMMMKKBLLLCCCLLLLLaaaLWLMCMK.........',
      '........KWWLMMMKKBBCBCCBNBNNNaaanWLMCMK.........',
      '........KLMMMMMBBBBCBNBBNBNNNaaaanLLMMMK........',
      '........KLMCCCCBBBCBNBBBNBNNNNaaannAnnK.........',
      '........KLMCKKKBBBCBNBBBNBNNNNaaannnAnK.........',
      '........KLMK..KBBCBWNBBBNBNNNNNaannnAnK.........',
      '........KLMK.KBBBCWBLBBBNBBNNNNaaannAnnK........',
      '........KCCK.KBBBCBLBBBBNBBNNNNNaannnAnK........',
      '........KLMKKBBBCBBNBBBBNBBNNNNNaannnAnK........',
      '........KLMBBBBBCBBNBBWNBBBNNNNNaaannnAnK.......',
      '........KLMBBBBBCBBNBWBLBBBNNNNLNaannnAnK.......',
      '........KLMBBBBCBBNBBBWNBBBBNNNNNaannnnAnK......',
      '........KLMBBBBCBBNBBBBNBBBBNNNNNNannnnAnK......',
      '........KCCBBBCBWBNBBBBNBBBWNNNNNNaannnnnnK.....',
      '........KLMBBBCWBBNBBBBNBBWBLNNNNNNannnnnnK.....',
      '........KLMBBBCBBNBBBBBNBBBWNNNNNNNannnnnnK.....',
      '........KCBBLCBLBNLBBLBNLBBLBNLNNLNaannnnnnK....',
      '.......KWWWWWWWWWWWWWWWWWWWWWWWWWWWWnnnnKKK.....',
      '.......KCLCLCLCLCLCLCLCLCLCLCLCLCLCLKKKK........',
      '........KKKKKKKKKKKKKKKKKKKKKKKKKKKK............',
    ],
    attack: [
      '........................K.......................',
      '.......................KCK......................',
      '.....................KKWBK.K....................',
      '....................KCWWBKKCK...................',
      '....................KBWWBCBBK...................',
      '...................KWBWWBBWBKKK.................',
      '..................KKWBCWBBWBCCCK................',
      '.................KCWWBCWBBCBBCWK................',
      '.................KWWWWWWWCWWWWWLK...............',
      '.................KLLBLLLCCLLMBMMK...............',
      '..................KWWWWWWWWWLLLLLK..............',
      '...........K......KWLLLLLMWWLLLLLLK.............',
      '..........KCK.....KnnLnnLMWCLLLCMMLK............',
      '.........KCWCK....KCnLCnLMWCLWLCMMMK............',
      '......K...KCK....KLLLLLLLMWCLWLLCMMMK...........',
      '.....KCK...K.....KLLLLLLMMWCLWLLCMMMLK..........',
      '..KK.KCK.KK......KLLLLLLMWWCLLWLCMMMMK..........',
      '.KWCKKWKKWCK.....KWpPLLMMWCLLLWLCMMMMMK.........',
      '.KCCKKWKKCCK....KCLMLLMMWWCLLLWLLCMMMMK.........',
      '..KKKCCK.KK.KKKKLLWLLWMMWWCLLLWLLCMMMMMK........',
      '...KCWBKKKKKLLLWWWWLLBWWWLBNMLLWLLCMMMMK........',
      '..KKWWBBWWCWWWWLLLLLLBBWWBBNMMLWLLMCMMMK........',
      '.KCCCWNNNWCLWLLLLLLBCBBWCCBNNNLLWLMCMMMMK.......',
      '..KKCCNNWWCLLWWLLLLBCBBCCNBNNNaLLWLMCMMMK.......',
      '....KCNNWLCLLLLMMLLBCBBBBBBNNNaLLWLLMCMMMK......',
      '.....KWKKKKKLMMMMLLBCBBBBBBNNNaaLLWLMCMMMK......',
      '..KK.KWK.KKKLMMMMKKKBCBWCCBNNNaaaLLWLMCMMMK.....',
      '.KWCKKWKKWCKLMAMLK.KWWWCCCWWWLLaaaLLWLMCMMMK....',
      '.KCCKKCKKCCKKMMALKKBLLLCCCLLLLLaaanLWLMCMMMK....',
      '..KK.KCK.KK.KMMMKKBBBCBCCBNBNNNaaannnWLMCMMMK...',
      '......K.....KCCMKKBBCBBNBBNBNNNaaannnALLMMMMMK..',
      '....K........KKCCBBBCBNBBBNBNNNNaaannnAnnnKKK...',
      '...KCK.........KBBBCBBNBBBNBNNNNaaannnAnnnK.....',
      '..KCWCK........KBBBCBLBBBBNBNNNNNaannnnAnnK.....',
      '...KCK........KBBBCBWNWBBBNBBNNNNaannnnAnnnK....',
      '....K.........KBBBCBBLBBBBNBBNNNNNannnnnAnnK....',
      '.............KBBBCBBNBBBBBNBBNNNNNaannnnAnnK....',
      '............KBBBBCBBNBBBWNBBBNNNNNaannnnnAnnK...',
      '............KBBBCBBBNBBWBLBBBNNNNLNannnnnAnnK...',
      '...........KBBBBCBBNBBBBWNBBBBNNNNNannnnnnAnnK..',
      '..........KBBBBCBWBNBBBBBNBBBBNNNNNNannnnnAnnK..',
      '..........KBBBBCWBLBBBBBBNBBBWNNNNNNannnnnnnnnK.',
      '.........KBBBBCBBWNBBBBBBNBBWBLNNNNNNnnnnnnnnnK.',
      '.........KBBBBCBBBNBBBBBBNBBBWNNNNNNNnnnnnnnnnK.',
      '........KBLBBLBBLNBLBBLBBLBBLBBLNNLNNLnnnnnnnnnK',
      '.......KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWnnnnKKKKK.',
      '.......KLCLCLCLCLCLCLCLCLCLCLCLCLCLCLCKKKK......',
      '........KKKKKKKKKKKKKKKKKKKKKKKKKKKKKK..........',
    ],
  },
};
