import type { SpriteDef } from '../sprite';

export const KNIGHT_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    H: 'lightGray',
    A: 'slate',
    M: 'darkSlate',
    N: 'night',
    V: 'navy',
    U: 'blue',
    G: 'gold',
    B: 'brown',
    b: 'darkBrown',
    W: 'white',
    L: 'lightGray',
  },
  frames: {
    idle: [
      '................................',
      '.......................KK.......',
      '..............KKK.....KWLK......',
      '.............KUVVK....KWLK......',
      '.............KVVNK....KWLK......',
      '............KKKVKKKK..KWLK......',
      '...........KAHAAMMMNK.KWLK......',
      '..........KAAAAAAMMMNKKWLK......',
      '..........KAAAAAMMMMNKKWLK......',
      '..........KAAAMKKKKKKKKWLK......',
      '..........KAAAMMNMKMNKKWLK......',
      '..........KMAAMMNMKMNKKWLK......',
      '..........KMMMMNNNNNNKKWLK......',
      '...........KNMMMNKKKKKKWLK......',
      '....KKKKKKKKHAVVVVAMK.KWLK......',
      '....KGNUUNGKAVVGGVVMK.KWLK......',
      '....KGNUUNGKMVGGGGVAKGGGGGGK....',
      '....KGUUUUGKMVVGGVVAAKAHMK......',
      '....KGNUUNGKbBBGBBbK..KbbK......',
      '....KGNUUNGKNVVVVVNK..KGGK......',
      '....KGNNNNGKNVVVVVNK...KK.......',
      '.....KGNNGKKNVVVVVNK............',
      '......KGGK.KKKKKKKKK............',
      '.......KK...KNMKKNMK............',
      '............KNMKKNMK............',
      '............KAHKKAHK............',
      '............KMAKKMAK............',
      '............KMAKKMAK............',
      '............KNMKKNMK............',
      '............KNMMKNMMK...........',
      '............KKKKKKKKK...........',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '..............KKK...............',
      '.............KUVVK..............',
      '.............KVVNK..............',
      '............KKKVKKKK............',
      '...........KAHAAMMMNK...........',
      '..........KAAAAAAMMMNK..........',
      '..........KAAAAAMMMMNK..........',
      '..........KAAAMKKKKKKK..........',
      '..........KAAAMMNMKMNK..........',
      '..........KMAAMMNMKMNK..........',
      '..........KMMMMNNNNNNK..........',
      '...........KNMMMNKKKKK..........',
      '....KKKKKKKKHAVVVVAMK.KK........',
      '....KGNUUNGKAVVGGVVMK.KGKKKKKKKK',
      '....KGNUUNGKMVGGGGVAAAHGWWWWWWWK',
      '....KGUUUUGKMVVGGVVAAMAGLLLLLLK.',
      '....KGNUUNGKbBBGBBbK.KKGKKKKKK..',
      '....KGNUUNGKNVVVVVNK...K........',
      '....KGNNNNGKNVVVVVNK............',
      '.....KGNNGKKNVVVVVNK............',
      '......KGGK.KKKKKKKKK............',
      '.......KK...KNMKKNMK............',
      '............KNMKKNMK............',
      '............KAHKKAHK............',
      '............KMAKKMAK............',
      '............KMAKKMAK............',
      '............KNMKKNMK............',
      '............KNMMKNMMK...........',
      '............KKKKKKKKK...........',
      '................................',
    ],
  },
};
