import type { SpriteDef } from '../sprite';

export const LICH_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    W: 'white',
    L: 'lightGray',
    M: 'gray',
    C: 'cyan',
    B: 'blue',
    Y: 'yellow',
    O: 'gold',
    o: 'orangeBrown',
    A: 'darkSlate',
    a: 'night',
    m: 'magenta',
    P: 'plum',
    N: 'night',
    V: 'navy',
    b: 'brown',
    d: 'darkBrown',
    G: 'green',
    g: 'midGreen',
    t: 'deepTeal',
  },
  frames: {
    idle: [
      '.....K....K..K..K...............',
      '....KCK..KYKKYKKYK..............',
      '...KCWBK.KAKAYAKaK..............',
      '..KCWCBBKAAAAAaaaKK.............',
      '...KCBBKKOOOCOOOoKmK............',
      '....KBK.KWWWWWLLMmPK............',
      '...KOYOKKWKKWKKLMmPNK...........',
      '...KbdK.KWCKWCKMMmPNK...........',
      '...KbdK.KLWWKWWMMmPNKKK.........',
      '...KbdK..KWKWKWMKmPNVNNK........',
      '...KbdK.KKKLMLMKKPNNVVNNK.......',
      '...KbdKKmmNNNNNOPNNNVVVNNK......',
      '...KbdKmmPONNNOPPPNNNVVNNK......',
      '...KbdmmPPOOCOoPPPNNNVVVNNK.....',
      '..KWWWOmPPPCWBPPPPPNNNVVNNK.....',
      '..KLbLOmPPPOBoPPPPPNNNVVVNNK....',
      '..KMbMOmPPPOYOPPPPPNNNVVVNNK....',
      '...KbOOmPPPOYOPPNPPPNNNVVNNK....',
      '...KbdOOmPPKOPPPPNPPNNNVVVNNK...',
      '...KbdmmOPPKOPPPPNPPNNNVVVNNK...',
      '...KbdmmPPPKOPPPPNPPPNNNVVNNK...',
      '...KbdmmPPPKOPPPPNPPPNNNVVVNNK..',
      '...KbdmmPPPKOPPPPNPPPNNNVVVNNK..',
      '...KbdmPPPPKOPPPPNPPPPNNNVVNNK..',
      '...KbdmPPPPKOPPPPNPPPPNNNVVNNK..',
      '...KbdmPPPPKOPPPPNPPPPNNNVVNNK..',
      '...KbdOOOOOOOOOOOOOOOOOoooVNNK..',
      '...KbdPKmPKPPPKPPNKNNNKNNNVNK...',
      '...KbdK.KKKPKKKNKKKNKKKNNKKNK...',
      '...KddK....K...K...K...KK..K....',
      '....KK..........................',
      '................................',
    ],
    attack: [
      '............K..K..K.............',
      '...........KYKKYKKYK............',
      '...KKKKK...KAKAYAKaK............',
      '..KgGGGgK.KAAAAAaaaKK...........',
      '.KgGKKKGgKKOOOCOOOoKmK..........',
      'KgGKKCKKGtKWWWWWLLMmPK..........',
      'KGKKCWBKKGKWKKWKKLMmPNK.........',
      'KGKCWCBBKGKWCKWCKMMmPNK.........',
      'KGKKCBBKKgKLWWKWWMMmPNKKK.......',
      'KtGKKBKKGtKKWKWKWMKmPNVNNK......',
      '.KtGKOKgtKKKKLMLMKKPNNVVNNK.....',
      '..KtggGtKKmmmNNNNOPNNNVVVNNK....',
      '...KbdKKKmmmPNNNOPPPNNNVVNNK....',
      '...KWWWWOmmPPOCOoPPPNNNVVVNNK...',
      '...KLbLLOmPPPCWBPPPPPNNNVVNNK...',
      '...KMbMKOmPPPOBoPPPPPNNNVVVNNK..',
      '....KbdKOOmPPOYOPPPPPNNNVVVNNK..',
      '.....KbdKOOmPOYOPPNPPPNNNVVNNK..',
      '.....KbdKmmOPKOPPPPNPPNNNVVVNNK.',
      '.....KbdmmPPPKOPPPPNPPNNNVVVNNK.',
      '......KbdmPPPKOPPPPNPPPNNNVVNNK.',
      '......KbdmPPPKOPPPPNPPPNNNVVVNNK',
      '......KbdmPPPKOPPPPNPPPNNNVVVNNK',
      '......KmbdPPPKOPPPPNPPPPNNNVVNNK',
      '......KmbdPPPKOPPPPNPPPPNNNVVNNK',
      '......KmbdPPPKOPPPPNPPPPNNNVVNNK',
      '......KYObdOOOOOOOOOOOOOOoooVNNK',
      '......KPPbdPKPPPKPPNKNNNKNNNVNK.',
      '......KPKKbdKPKKKNKKKNKKKNNKKNK.',
      '.......K..KK.K...K...K...KK..K..',
      '................................',
      '................................',
    ],
  },
};
