import type { SpriteDef } from '../sprite';

export const MAGE_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    P: 'magenta',
    p: 'plum',
    S: 'skin',
    s: 'skinShade',
    W: 'white',
    B: 'brown',
    b: 'darkBrown',
    C: 'cyan',
    U: 'blue',
    G: 'gold',
    L: 'lightGray',
  },
  frames: {
    idle: [
      '................................',
      '.............KK.................',
      '............KPpK........KKK.....',
      '............KPpK.......KCCUK....',
      '...........KPPppK.....KCWCUK....',
      '...........KPPPpK.....KCCCUK....',
      '..........KPPPPppK.....KUUK.....',
      '.........KPPPPPPppK.....KbK.....',
      '........KGGGGGGGGGGK....KBK.....',
      '......KppppppppppppppK..KBK.....',
      '..........KLSSSSSK......KBK.....',
      '..........KLSSKSSK......KBK.....',
      '..........KLSSSSsK......KBK.....',
      '..........KLLWWWWK......KBK.....',
      '.........KPKWWWWWLK.....KBK.....',
      '........KPPPKWWWLKPK....KBK.....',
      '........KPPPPKWWKPPPK..KSBK.....',
      '........KPPPPKWLKpPK..KSSBK.....',
      '........KPPPKWLKPpPPpKSSKBK.....',
      '........KPpPKLKPPpKppKSKKBK.....',
      '........KPpPPGPPPpK.KKKKKBK.....',
      '........KPpPPGPPPpK.....KBK.....',
      '.......KPPpPPGPPPppK....KBK.....',
      '.......KPPpPPGPPPppK....KBK.....',
      '.......KPppPPGPPpppK....KBK.....',
      '......KPPppPPGPPppppK...KBK.....',
      '......KPPppPPGPPppppK...KbK.....',
      '......KGGGGGGGGGGGGGK...KbK.....',
      '.......KKKbbKKKbbKKK.....K......',
      '.........KbbK.KbbK..............',
      '.........KKKK.KKKK..............',
      '................................',
    ],
    attack: [
      '................................',
      '.............KK.................',
      '............KPpK................',
      '............KPpK................',
      '...........KPPppK...............',
      '...........KPPPpK...............',
      '..........KPPPPppK..............',
      '.........KPPPPPPppK........KKK..',
      '........KGGGGGGGGGGK......KCCUK.',
      '......KppppppppppppppK...KCWCUK.',
      '..........KLSSSSSK.......KCCCUK.',
      '..........KLSSKSSK........KUUK..',
      '..........KLSSSSsK.......KBK....',
      '..........KLLWWWWK......KBK.....',
      '.........KPKWWWWWLK....KBK......',
      '........KPPPKWWWLKPK..KBK.......',
      '........KPPPPKWWKPPPpKSSK.......',
      '........KPPPPKWLKpPPpKSSK.......',
      '........KPPPKWLKPpPPpKKKK.......',
      '........KPpPKLKPPpKKKK..........',
      '........KPpPPGPPPpK.............',
      '........KPpPPGPPPpK.............',
      '.......KPPpPPGPPPppK............',
      '.......KPPpPPGPPPppK............',
      '.......KPppPPGPPpppK............',
      '......KPPppPPGPPppppK...........',
      '......KPPppPPGPPppppK...........',
      '......KGGGGGGGGGGGGGK...........',
      '.......KKKbbKKKbbKKK............',
      '.........KbbK.KbbK..............',
      '.........KKKK.KKKK..............',
      '................................',
    ],
  },
};
