import type { SpriteDef } from '../sprite';

export const MEDUSA_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    g: 'darkGreen',
    G: 'midGreen',
    S: 'green',
    s: 'midGreen',
    Y: 'yellow',
    R: 'red',
    u: 'gold',
    H: 'yellow',
  },
  frames: {
    idle: [
      '................................',
      '..........K..K..K...............',
      '.........KgKKgKKgKK.............',
      '........KgGKgGKgGKgK............',
      '.......KgGgKGgGgGgGK............',
      '......KgGgGGGGGGGgGgK...........',
      '.....KgGKGGGGGGGGGgGK...........',
      '......KKKgSSSSSSGggKgK..........',
      '........KSYKSSYKsGgGgK..........',
      '........KSSSSSSSsGgKK...........',
      '.........KSRRSSssgK.............',
      '.........KKSSSssgK..............',
      '.......KKuuSSSSsuuK.............',
      '......KSSuuuGGGGuuuK............',
      '.....KSSsKGGGGGGGggK............',
      '....KSSKKKGGGGGGGggK............',
      '.....KK..KGGgGGgGggK............',
      '..........KgGGGGGggK............',
      '..........KgGGYGGggK............',
      '...........KgGGYGGggK...........',
      '............KgGGYGGggK..........',
      '.........KK..KgGGYGGgK..........',
      '........KggKKKgGGYGGgK..........',
      '.......KgGGgggGGYGGggK..........',
      '......KgGGGGGGGYGGGgK...........',
      '......KgGYYYYYYYGGgK............',
      '.......KggGGGGGGggK.............',
      '........KKKKKKKKKK..............',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
    attack: [
      '................................',
      '.........K..K..K................',
      '........KgKKgKKgKK..............',
      '...K...KgGKgGKgGKgK.............',
      '..KgK.KgGgKGgGgGgGK.............',
      '.KgGgKgGgGGGGGGGgGgK............',
      '..KgGKGKGGGGGGGGGgGK............',
      '...KK.KKgSSSSSSGggKgK...........',
      '.......KSHHSSHHsGgGgK...........',
      '.......KSSSSSSSsGgKK............',
      '........KSRRSSssgK..............',
      '.KKK....KKSSSssgK...............',
      'KSSsKKKKuuSSSSsuuK..............',
      '.KSSSSSuuuGGGGuuuK..............',
      '..KKKKKKKGGGGGGGggK.............',
      '........KGGGGGGGggK.............',
      '........KGGgGGgGggK.............',
      '.........KgGGGGGggK.............',
      '.........KgGGYGGggK.............',
      '..........KgGGYGGggK............',
      '...........KgGGYGGggK...........',
      '........KK..KgGGYGGgK...........',
      '.......KggKKKgGGYGGgK...........',
      '......KgGGgggGGYGGggK...........',
      '.....KgGGGGGGGYGGGgK............',
      '.....KgGYYYYYYYGGgK.............',
      '......KggGGGGGGggK..............',
      '.......KKKKKKKKKK...............',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
};
