import type { SpriteDef } from '../sprite';

export const MINOTAUR_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    W: 'white',
    S: 'sand',
    B: 'brown',
    b: 'darkBrown',
    e: 'deepBrown',
    T: 'tan',
    H: 'hotRed',
    R: 'red',
    r: 'darkRed',
    s: 'skinShade',
    G: 'gold',
    L: 'lightGray',
    M: 'gray',
    o: 'orangeBrown',
  },
  frames: {
    idle: [
      '...K.....................K......',
      '..KWK...................KWK.....',
      '..KSWK.................KWSK.....',
      '..KSSKK...............KKSSK.....',
      '...KSSSKKKKKKKKKKKKKKKSSSK......',
      '....KSSSSbbebbbbebbbSSSSK.......',
      '.....KKKKeBBBBBBBBBBeeKK........',
      '........KbeebBBBBbeebeK.........',
      '........KbHReBBBBeRHbbeKK.......',
      '........KbBBBBBBBBBBbBBeeK......',
      '.......KbBBBBBBBBbbBBBBBBeKK....',
      '..KKK.KTTTTTTTBBbBBBBBBBBbbeK...',
      '.KLMoKsTeTTTeTsbBBBBBBBBBBBbeK..',
      'KWLMoKssGsGsssbBBBBBBBBBBBBbbeK.',
      'KWLMoKKKKGKKbBTTTBBTTTBBBBBBbbeK',
      'KWLMoK.KbBBTTTTBTTTTBBBBBBBbbeK.',
      '.KLMoKKbBBBBTTTBBTTTBBBBBBbBbeK.',
      '..KKoKbBBbBBBBBBBBBBBBBBBbbBbeK.',
      '...KoBBBbbBTBTBTBBBBBBBbbbBBeK..',
      '..KBBBBbKbBTBTBTBBBBBBbbbKbBBeK.',
      '..KBBBbKKbBBBBBBBBBBBbbbKKbBBeK.',
      '...KoKK.KrrrrrrrrrrrrrrK.KbssK..',
      '...KoK..KrRRRRRRRRRRRRrK..KssK..',
      '...KoK...KbBBBrRrBBBbbK....KK...',
      '...KoK...KbBBBbKbBBBBbK.........',
      '...KoK...KbBBBbKKbBBBbK.........',
      '...KoK..KbBBBBbKKbBBBBbK........',
      '...KoK..KbBBBBbKKbBBBBbK........',
      '....K..KeeeeeeK.KeeeeeeK........',
      '.......KeeeeeeK.KeeeeeeK........',
      '........KKKKKK...KKKKKK.........',
      '................................',
    ],
    attack: [
      '................................',
      '..K.....................K.......',
      '.KWK...................KWK......',
      '.KSWK.................KWSK......',
      '.KSSKK...............KKSSK......',
      '..KSSSKKKKKKKKKKKKKKKSSSK.......',
      '...KSSSSbbebbbbebbbSSSSK........',
      '....KKKKeBBBBBBBBBBeeKK.........',
      '.......KbeebBBBBbeebeK..........',
      '.......KbHHeBBBBeHHbbeKK........',
      '.......KbBBBBBBBBBBbBBeeK.......',
      '......KbBBBBBBBBbbBBBBBBeKK.....',
      '.....KTTTTTTTBBbBBBBBBBBbbeK....',
      '....KsTeTTTeTsbBBBBBBBBBBBbeK...',
      '..K.KssGsGsssbBBBBBBBBBBBBbbeK..',
      '.KLK.KKKGKKbBTTTBBTTTBBBBBBbbeK.',
      'KWLMKKKKbBBBTTTTBTTTTBBBBBbbeK..',
      'KWLMooBBBBBBBBTTTBBTTTBBBBbBbeK.',
      'KWLMooBBBBBBBBBBBBBBBBBBBbbBBeK.',
      '.KLMKKKKKbBTBTBTBBBBBBbbbKbBBeK.',
      '.KLK....KbBBBBBBBBBBbbbKKKbBBeK.',
      '..K.....KrrrrrrrrrrrrrrK.KbssK..',
      '........KrRRRRRRRRRRRRrK..KssK..',
      '.......KbBBBBrRrBBBBbKK....KK...',
      '......KbBBBbKKKKKbBBBbK.........',
      '.....KbBBBbK.....KbBBBbK........',
      '....KbBBBbK......KbBBBbK........',
      '....KbBBBbK.......KbBBBbK.......',
      '...KeeeeeeK.......KeeeeeeK......',
      '...KeeeeeeK.......KeeeeeeK......',
      '....KKKKKK.........KKKKKK.......',
      '................................',
    ],
  },
};
