import type { SpriteDef } from '../sprite';

export const MUSHROOM_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    R: 'red',
    r: 'darkRed',
    O: 'orange',
    W: 'white',
    S: 'sand',
    s: 'tan',
    T: 'skinShade',
    G: 'green',
    g: 'midGreen',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '..........KKKKKKKKKKKK..........',
      '........KKRRRORRRRRRRRKK........',
      '.......KROOOOOOWWORRRRRRK.......',
      '......KROOOOOOOWWOORRRRRRK......',
      '.....KROOOOOOOOOOOOORRRRRRK.....',
      '....KRRROOOOOOOOOOORRWWRRRRK....',
      '....KRRRRWWOOOOOOORRRWWRRRRK....',
      '....KRRRRWWRRORRRRRRRRRRRRRK....',
      '....KRRRRRRRRRRRRRRRRRRRRRRK....',
      '....KRRRRRRRWWRRRRRWWRRRRRRK....',
      '....KrrrrrrrWWrrrrrWWrrrrrrK....',
      '....KrrrrrrrrrrrrrrrrrrrrrrK....',
      '.....KKKRRRRRRRRRRRRRRRRKKK.....',
      '........KKRRRRRRRRRRRRKK........',
      '..........KKTTSSSSssKK..........',
      '...........KTKSSSKssK...........',
      '...........KTTSSSSssK...........',
      '...........KTTSSSSssK...........',
      '...........KTTSKSSssK...........',
      '...........KTTSSSSssK...........',
      '...........KTTSSSSssK...........',
      '..........KKTTSSSSssKK..........',
      '.........KTTTTTTTTTTTTK.........',
      '.........KTTTTTTTTTTTTK.........',
      '..........KKKKKKKKKKKK..........',
    ],
    attack: [
      '................................',
      '................................',
      '........KK......................',
      '.......KGgK.....................',
      '........KK..............KK......',
      '......KK...............KGgK.....',
      '.....KGgK...............KK......',
      '......KK........................',
      '...........................KK...',
      '...KK.....KKKKKKKKKKKK....KGgK..',
      '..KGgK..KKOOOOOWWRRRRRKK...KK...',
      '...KK.KKOOOOOOOWWOORRRRRKK......',
      '.....KROOOOOOOOOOOOORRRRRRK.....',
      '.....KRROOOOOOOOOOORRWWRRRK.....',
      '..KKKRRRRWWOOOOOORRRRWWRRRRK....',
      '.KGgKRRRRWWRRRRRRRRRRRRRRRRK....',
      '..KKKRRRRRRRRRRRRRRRRRRRRRRK....',
      '.....KRRRRRRWWRRRRRWWRRRRRK.....',
      '....KrrrrrrrWWrrrrrWWrrrrrrK....',
      '....KrrrrrrrrrrrrrrrrrrrrrrK....',
      '.....KKKKKRRRRRRRRRRRRKKKKK.....',
      '..........KKTTSSSSssKK..........',
      '...........KTKSSSKssK...........',
      '...........KTTSSSSssK...........',
      '...........KTTSSSSssK...........',
      '...........KTTKKKSssK...........',
      '...........KTTSSSSssK...........',
      '...........KTTSSSSssK...........',
      '..........KKTTSSSSssKK..........',
      '.........KTTTTTTTTTTTTK.........',
      '.........KTTTTTTTTTTTTK.........',
      '..........KKKKKKKKKKKK..........',
    ],
  },
};
