import type { SpriteDef } from '../sprite';

export const NECROMANCER_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    T: 'deepTeal',
    t: 'darkGreen',
    n: 'night',
    G: 'green',
    g: 'midGreen',
    Y: 'yellow',
    W: 'white',
    L: 'lightGray',
    E: 'sand',
    b: 'deepBrown',
  },
  frames: {
    idle: [
      '................................',
      '.......................K........',
      '............KKK.......KGK.......',
      '...........KtTTK.....KGYGK......',
      '..........KtTTTTK....KgGgK......',
      '..........KtTTTTTnK..KWWWK......',
      '.........KtTTTKKKKnK.KWKWK......',
      '.........KtTTnKKKKnK.KWWWK......',
      '.........KtTTnKKGKnK..KLK.......',
      '.........KtTTnKKKKnK..KLK.......',
      '.........KtTTTTnnnK...KLK.......',
      '..........KtTTTnnnK...KLK.......',
      '.........KKtTTTTnnK...KLK.......',
      '........KtTTTTTTnTnK..KLK.......',
      '........KtTTTTTTnTTnK.KLK.......',
      '........KtTTTTTTnKTTnKKLK.......',
      '.......KtTTTTTTTTnKTnEELE.......',
      '.......KtTTTTTTTnnKKKEKLK.......',
      '.......KtTTtTTTTnnK..KKLK.......',
      '.......KttTtTTTTnnK...KLK.......',
      '......KttTTtTTTTTnnK..KLK.......',
      '......KttTTtTTtTTnnK..KLK.......',
      '......KttTTtTTtTTnnK..KLK.......',
      '......KttTTtTTtTTnnK..KLK.......',
      '......KttTTtTTtTnnnK..KLK.......',
      '.....KttTTTtTTtTTnnnK.KLK.......',
      '.....KttTTTtTTtTTnnnK.KLK.......',
      '.....KLLLLLLLLLLLLLLK..K........',
      '.......KKKbbKKKbbKKK............',
      '.........KbbK.KbbK..............',
      '.........KKKK.KKKK..............',
      '................................',
    ],
    attack: [
      '................................',
      '.........................K......',
      '............KKK.........KGK.....',
      '...........KtTTK.......KGYGK....',
      '..........KtTTTTK......KgGgK....',
      '..........KtTTTTTnK....KWWWK....',
      '.........KtTTTKKKKnK...KWKWK....',
      '.........KtTTnKKKKnK...KWWWK....',
      '.........KtTTnKKGKnK...KLKK.....',
      '.........KtTTnKKKKnK...KLK......',
      '.........KtTTTTnnnK....KLK......',
      '..........KtTTTnnnK....KLK......',
      '.........KKtTTTTnnK....KLK......',
      '........KtTTTTTTnTnK...KLK......',
      '........KtTTTTTTnTTnK.KLK.......',
      '........KtTTTTTTnKTTnKKLK.......',
      '.......KtTTTTTTTTnKTnEKEKE......',
      '.......KtTTTTTTTnnKKKEKLK.......',
      '.......KtTTtTTTTnnK..KKLK.......',
      '.......KttTtTTTTnnK...KLK.......',
      '......KttTTtTTTTTnnK..KLK.......',
      '......KttTTtTTtTTnnK..KLK.......',
      '......KttTTtTTtTTnnK..KLK.......',
      '......KttTTtTTtTTnnK..KLK.......',
      '......KttTTtTTtTnnnK..KLK.......',
      '.....KttTTTtTTtTTnnnK.KLK.......',
      '.....KttTTTtTTtTTnnnK.KLK.......',
      '.....KLLLLLLLLLLLLLLK..K........',
      '.......KKKbbKKKbbKKK............',
      '.........KbbK.KbbK..............',
      '.........KKKK.KKKK..............',
      '................................',
    ],
  },
};
