import type { SpriteDef } from '../sprite';

export const NIGHTMARE_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    A: 'slate',
    a: 'darkSlate',
    n: 'night',
    Y: 'yellow',
    O: 'orange',
    R: 'red',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '..........K.....................',
      '.......KKKRK.K..................',
      '......KAaRORKRK.................',
      '.....KAAaOYORORK................',
      '....KAYYaaYYOYORK...........K...',
      '...KAaaaaaaYYYORKK.........KRK..',
      '..KAaaaaanaaYYORKRK.......KRORK.',
      '.KAaaannAaaaaYYORORK......KOYORK',
      '.KRaannKAaaaanYOORK......KOYYORK',
      '.KnnnKK.KAaaaanORKKKK....KOYYORK',
      '..KKK...KAaaaanKKKAAAKKKKOYYORK.',
      '.........KAaaaAAAAAAaaaaOYYORKRK',
      '.........KAaaAAAAaaaaaaaaYOORORK',
      '..........KAAAAaaaaaaaaaaaRROKRK',
      '..........KAAaaaaaaaaaaannnRKRK.',
      '..........KaaaaaaaaaannnnnnnKK..',
      '...........KaaaaannnnaannnnK....',
      '..........KAnnnnnnnnnaannnnK....',
      '..........KAnKnnnnnnnaannnnK....',
      '..........KAnKnnKKnnnAanKnnK....',
      '..........KAnKnnK.KKKAanKnnK....',
      '..........KAnKnnK...KAanKnnK....',
      '..........KAnKnnK...KAanKnnK....',
      '..........KAnKnnK...KAanKnnK....',
      '..........KAnKnnK...KAanKnnKK...',
      '.........KRanRnnRK..KRanRRnKRK..',
      '.........KOYYOYYOK..KOYYOOYYOK..',
      '..........KKKKKKK....KKKKKKKK...',
      '................................',
      '................................',
    ],
    attack: [
      '......KKKK.KK...................',
      '.....KARORKORKK.................',
      '....KAAaOYOOYORK................',
      '...KAYYaYYYYORKRK...............',
      '..KAaaaaaYYYORORK...............',
      '.KAaaaaanaYYOORK................',
      'KAaaannaaaaYORKRK...............',
      'KRaannKAaaaaORKK................',
      'KnnnKKKAaaaanK..................',
      '.KKK...KAaaaanKK................',
      '.......KAaaaAAAAKKK.........K...',
      '......KnnAaAAAAaaaaKK......KRK..',
      '......KnnAAAAAaaaaaaaK....KRORK.',
      '....KKnnnKAaaaaaaaaaaaK..KROYORK',
      '...KRKnnKKKaaaaaaaaaaaaKKROYYOK.',
      '..KROYKnKAAAAAaaaaaaaaaaROYYYORK',
      '..KOYYKKKaaaaaaaaaaaaaaaOYYYORK.',
      '...KKK..KannnnnaaaannnnnYYOORKRK',
      '......KKaanKKKnnnnnnnnnnnOORROK.',
      '.....KRKanK...KnnnnnnnnnnKRKKRK.',
      '....KROYYnK....KKnnnaannnKK..K..',
      '....KOYYOK.......KKKaannnK......',
      '.....KRKRK........KAanKnnK......',
      '......K.K.........KAanKKnnK.....',
      '..................KAanKKnnK.....',
      '..................KAanKKnnnK....',
      '..................KAanK.KnnKK...',
      '..................KRanRKKRnKRK..',
      '..................KOYYOKKOYYOK..',
      '...................KKKK..KKKK...',
      '................................',
      '................................',
    ],
  },
};
