import type { SpriteDef } from '../sprite';

export const OGRE_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    S: 'sand',
    s: 'tan',
    B: 'brown',
    b: 'darkBrown',
    d: 'deepBrown',
    n: 'night',
    A: 'slate',
    a: 'darkSlate',
    L: 'lightGray',
    M: 'gray',
    W: 'white',
    R: 'red',
    r: 'darkRed',
    Y: 'gold',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '..............KK................',
      '.............KddKK..............',
      '........KKKKKSSsssKKKKK.........',
      '.....KKKSSSbSSsssssbssBKKK......',
      '....KSSSSssbSbbsbbBbsssssBKK....',
      '...KSSSSsssbsRbsRbBbssssssBBK...',
      '..KSSSsssssbSsBBBsBbsssssssBBK..',
      '.KSSsssssBbbsWKKKWBbssssssBBbK..',
      '.KSssssBbSSSbBsssBbsssbSsssBBbK.',
      '.KSssssBbSSdWdddWdsssBbsssssBbK.',
      '.KSsssBbbsBBWsssWsBBBsbssssBBbK.',
      'KSSsssBbbSSssssssssssBbSsssBBbK.',
      'KSSSssBbbSsssssssssssBbSssssBbK.',
      'KsBsBsBbbssssssBssssBBbsssssBbK.',
      'KbBbBbbbbsssssssssssBBbssssBBbK.',
      '.KKbdnKKbBsssssssssBBbbssssBBbK.',
      '..KbdnKKddddddddYdddddbSSssBBbK.',
      '..KbdnK.KAAaaaaaaaaaanKsBsBsBbK.',
      '.KbbdnK.KAaaaaaaaaaannKbBbBbbbK.',
      '.KbbddnKKSAaaaaaaaaanBKKKKKKKK..',
      'KLbbddnKKSsssAaaansssBbK........',
      'KbbLddnLKsssBaaaanssBBbK........',
      'KbbbddnnKsssBbaanbsssBbK........',
      'KLbbdddMKsSssBbKKsSssBbK........',
      'KbbbdMnnKsssBBbKKsssBBbK........',
      'KbLbddnnSSsssBbKSSsssBbK........',
      '.KdddnnKBBBBbbbKBBBBbbbK........',
      '..KKKKK.KKKKKKK.KKKKKKK.........',
      '................................',
    ],
    attack: [
      '..KKKKK.......KKKKKKKKKKKKKKK...',
      '.KSSssBKKKKKKKLbbbLbbbbLbbbbdK..',
      'KSSsssBbbbbbBbbbbbbbbbbbbbbdnK..',
      'KsBsBsbddddddbdddddddddddddnnK..',
      '.KSssBbKKKKKKKndnnMnnnnnMnnnnK..',
      '.KSssBbKKKKKKSSsssKKKKKKKKKKK...',
      '.KSsssBbSSSbSSsssssbssBKKK......',
      '.KSssssBsssbSbbsbbBbsssssBKK....',
      '.KSssssssssbsRbsRbBbssssssBBK...',
      '.KsssssssssbSsBBBsBbsssssssBBK..',
      '.KBsssssssBbsWKrKWBbssssssBBbK..',
      '..KKKBbbbSSSbBsssBbsssbSsssBBbK.',
      '.....KKKbSSdWdddWdsssBbsssssBbK.',
      '.......KbsBBWsssWsBBBsbssssBBbK.',
      '.......KbSSssssssssssBbSsssBBbK.',
      '.......KbSsssssssssssBbSssssBbK.',
      '.......KbssssssBssssBBbsssssBbK.',
      '.......KbsssssssssssBBbssssBBbK.',
      '.......KbBsssssssssBBbbssssBBbK.',
      '.......KddddddddYdddddbSSssBBbK.',
      '........KAAaaaaaaaaaanKsBsBsBbK.',
      '........KAaaaaaaaaaannKbBbBbbbK.',
      '........KSAaaaaaaaaanBKKKKKKKK..',
      '........KSsssAaaansssBbK........',
      '........KsssBaaaanssBBbK........',
      '........KsssBbaanbsssBbK........',
      '........KsSssBbKKsSssBbK........',
      '........KsssBBbKKsssBBbK........',
      '.......KSSsssBbKSSsssBbK........',
      '.......KBBBBbbbKBBBBbbbK........',
      '........KKKKKKK.KKKKKKK.........',
      '................................',
    ],
  },
};
