import type { SpriteDef } from '../sprite';

export const ORC_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    g: 'midGreen',
    G: 'green',
    d: 'darkGreen',
    W: 'white',
    Y: 'gold',
    R: 'red',
    B: 'brown',
    b: 'darkBrown',
    L: 'lightGray',
    M: 'gray',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '...............KK...............',
      '..............KbbK..............',
      '.....KKK....KKKKKKKK............',
      'KKK..KBK...KGggggggdK...........',
      'KWLKKKBK..KGggggggggdK..........',
      'KWLMMKBK..KgKKggKKggdK..........',
      'KLLMMKBK..KgRgggRgggdK..........',
      'KLLKKKBK..KggdggggggdK..........',
      'KKK..KBK..KgWgggWgggdK..........',
      '.....KBK..KgWKKKWgggdK..........',
      '.....KBK..KgggggggggdK..........',
      '.....KBK...KggggggddK...........',
      '.....KBKGggggggggggBBgggdK......',
      '.....KBKGgggggggggBBggggdK......',
      '.....KBKGggggggggBBggggKdK......',
      '...KKKBKgggKggggBBgggggKdK......',
      '...KGggggggKgggBBggggggKdK......',
      '...KGggggK.KggBBgggggggKdK......',
      '...KgggdgK.KbBBBBBYBBBBKdK......',
      '...KKKKKKK.KbBBBBBBBBbKGGK......',
      '.....KBK...KbBBBBBBBBbKKKK......',
      '.....KBK...KggggKKggggK.........',
      '.....KBK...KggggKKggggK.........',
      '.....KBK...KdgggKKdgggK.........',
      '.....KKK...KbbbbKKbbbbK.........',
      '...........KbBBBKKbBBBK.........',
      '..........KbBBBBKbBBBBK.........',
      '..........KKKKKKKKKKKKK.........',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '.....KKK........................',
      'KKK..KBK.......KK...............',
      'KWLKKKBK......KbbK..............',
      'KWLMMKBK....KKKKKKKK............',
      'KLLMMKBK...KGggggggdK...........',
      'KLLKKKBK..KGggggggggdK..........',
      'KKK..KBK..KgKKggKKggdK..........',
      '.....KBK..KgRgggRgggdK..........',
      '.....KBK..KggdggggggdK..........',
      '.....KBK..KgWgggWgggdK..........',
      '.....KBK..KgWRRRWgggdK..........',
      '.....KBK..KgggKKKgggdK..........',
      '.....KBK...KggggggddK...........',
      '...KKKBKGggggggggggBBgggdK......',
      '...KGggggggKggggggBBggggdK......',
      '...KGggggK.KgggggBBggggKdK......',
      '...KgggdgK.KggggBBgggggKdK......',
      '...KKKKKKK.KgggBBggggggKdK......',
      '.....KBK...KggBBgggggggKdK......',
      '.....KBK...KbBBBBBYBBBBKdK......',
      '.....KBK...KbBBBBBBBBbKGGK......',
      '.....KKK...KbBBBBBBBBbKKKK......',
      '...........KggggKKggggK.........',
      '...........KggggKKggggK.........',
      '...........KdgggKKdgggK.........',
      '...........KbbbbKKbbbbK.........',
      '...........KbBBBKKbBBBK.........',
      '..........KbBBBBKbBBBBK.........',
      '..........KKKKKKKKKKKKK.........',
      '................................',
    ],
  },
};
