import type { SpriteDef } from '../sprite';

export const PALADIN_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    W: 'white',
    L: 'lightGray',
    M: 'gray',
    A: 'slate',
    G: 'gold',
    g: 'orange',
    V: 'navy',
    N: 'night',
    S: 'skin',
    s: 'skinShade',
    H: 'brown',
    b: 'darkBrown',
  },
  frames: {
    idle: [
      '................................',
      '............KKK.................',
      '...........KGGgK...KKKKK........',
      '...........KGggK..KWLLLMK.......',
      '..........KWLLLLMKKWLLLMK.......',
      '.........KWLLLLLMAKLLLMAK.......',
      '.........KWLLLGGGGGMMMAAK.......',
      '.........KLLLMSSKSSKKHKK........',
      '.........KLLLMsSSSSSKHK.........',
      '.........KLLLMsSSSsKKbK.........',
      '.........KMLLMMSSsK.KHK.........',
      '..........KMMMMMMAK.KHK.........',
      '........KWLLLLLLLMAKKbK.........',
      '......KVKLLLLGLLLMAAKHK.........',
      '.....KVNKLLGGGGGLMAMKHK.........',
      '.....KVNKLLLLGLLMMAMKbK.........',
      '.....KVNKLLLLGLLMMAMLHL.........',
      '....KVVNKLLLLGLMMAAMMHM.........',
      '....KVVNKGGGGGGGggAMKbK.........',
      '....KVVNNKLLLLLMMAK..K..........',
      '...KVVVNNKLLLLMMAAK.............',
      '...KVVVNNKWLLLMMAAK.............',
      '...KVVNNNKMMMMAAAAK.............',
      '...KVVNNNKKLMKKLMK..............',
      '....KVNNNKKLMKKLMK..............',
      '....KKKKKKKWMKKWMK..............',
      '..........KLMKKLMK..............',
      '..........KMAKKMAK..............',
      '..........KMAKKMAK..............',
      '..........KMAAKMAAK.............',
      '..........KKKKKKKKK.............',
      '................................',
    ],
    attack: [
      '................................',
      '............KKK.................',
      '...........KGGgK................',
      '...........KGggK................',
      '..........KWLLLLMK..............',
      '.........KWLLLLLMAK.............',
      '.........KWLLLGGGGGK............',
      '.........KLLLMSSKSSK............',
      '.........KLLLMsSSSSSK...........',
      '.........KLLLMsSSSsK............',
      '.........KMLLMMSSsK.............',
      '..........KMMMMMMAK.............',
      '........KWLLLLLLLMAK............',
      '......KVKLLLLGLLLMAAK.......KKKK',
      '.....KVNKLLGGGGGLMAMK......KMLWW',
      '.....KVNKLLLLGLLMMLMKKKKKKKKMLLL',
      '.....KVNKLLLLGLLbHHbHHbHHbHHMLLL',
      '....KVVNKLLLLGLMMAMMKKKKKKKKAMLL',
      '....KVVNKGGGGGGGggAMK......KAAMM',
      '....KVVNNKLLLLLMMAK.........KKKK',
      '...KVVVNNKLLLLMMAAK.............',
      '...KVVVNNKWLLLMMAAK.............',
      '...KVVNNNKMMMMAAAAK.............',
      '...KVVNNNKKLMKKLMK..............',
      '....KVNNNKKLMKKLMK..............',
      '....KKKKKKKWMKKWMK..............',
      '..........KLMKKLMK..............',
      '..........KMAKKMAK..............',
      '..........KMAKKMAK..............',
      '..........KMAAKMAAK.............',
      '..........KKKKKKKKK.............',
      '................................',
    ],
  },
};
