import type { SpriteDef } from '../sprite';

export const PLAGUE_LORD_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    G: 'midGreen',
    g: 'darkGreen',
    d: 'deepTeal',
    V: 'green',
    B: 'brown',
    r: 'darkBrown',
    e: 'deepBrown',
    S: 'sand',
    T: 'tan',
    Y: 'yellow',
    O: 'gold',
    o: 'orangeBrown',
    M: 'gray',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '..................KKKK..........',
      '................KKTTTrKKK.......',
      '........KKK....KTTBBBBTrrK......',
      '......KKeeeK..KTBBBVVBBrrrK.....',
      '.....KeerrreKKTBBBVYVGBBrrK.....',
      '....KerrrrreeTBBBBVVGgBBrrrK....',
      '....KrrSSSSreBBBBBBGgBBBrrrrK...',
      '...KKrSSKYKSeBBBBBBBBBBrrrrrK...',
      '..KSSSSSKKKSeBBBBBBBBBrrVVrrK...',
      '.KSSSSSSTTTreBBBBBBBBBrVYVgrK...',
      'KSTTTTTTrreeeBBBBBBBBrrrGgrrK...',
      '.KrrrKKKreeBBBBBBrrrrrrrrrrrK...',
      '..KYK.KGGggBBrrrrrrrrrrrrrrdK...',
      '.KYVKKGGGBBBrrrrrrrrrrrrrrdKK...',
      'KYVKKGGGBBBrrggrrrrrrrrrrKdddK..',
      'KVGKKGGGrrBrggggrgKKgggggddddK..',
      '.KVGKGGGrrgggggggggggggrgddddK..',
      '..KYVGGMgggggggdgggggggggddddK..',
      '...KVGGMgggggggdgggggggggddddK..',
      '...KGGOOgggggggdgggggggggddddK..',
      '...KGOOOoggggggdggggdggggddddK..',
      '...KOYOYoogggggdggggdggggddddK..',
      '...KoOOOorgggggdggggdgggddddK...',
      '....KororggggggdggggdgggddddK...',
      '....KGGGgggggggdggggdgggddddK...',
      '.....KGGgggggggdggggdgggddddK...',
      '.....KGGKKggKKggKKggKKggKKddK...',
      '.....KGK.KgK.KgK.KgK.KgK.KdK....',
      '......K...K...K...K...K...K.....',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '..................KKKK..........',
      '................KKTTTrKKK.......',
      '........KKK....KTTBBBBTrrK......',
      '......KKeeeK..KTBBBVVBBrrrK.....',
      '.....KeerrreKKTBBBVYVGBBrrK.....',
      '....KerrrrreeTBBBBVVGgBBrrrK....',
      '....KrrSSSSreBBBBBBGgBBBrrrrK...',
      '...KKrSSKYKSeBBBBBBBBBBrrrrrK...',
      '..KSSSSSKKKSeBBBBBBBBBrrVVrrK...',
      '.KSSSSSSTTTreBBBBBBBBBrVYVgrK...',
      'KSTTTTTTrreeeBBBBBBBBrrrGgrrK...',
      '.KrrrKKKreeBBBBBBrrrrrrrrrrrK...',
      '..KKKKKGGggBBrrrrrrrrrrrrrrdK...',
      '..KVVGGGGBBBrrrrrrrrrrrrrrdKK...',
      '.KYYYVGGBBrrrggrrrrrrrrrrKdddK..',
      'KGYYYVVMrrrgggggrgKKgggggddddK..',
      'KGVKKKMGggGVGggggggggggrgddddK..',
      'KGKOOKGGgGVVVGgdgggggggggddddK..',
      '.KOOOoKggGVVVGgdgggggggggddddK..',
      'KOYYYooKVGGVGGgdgggggggggddddK..',
      'KoOOOorKYVGGGggdggggdggggddddK..',
      '.KororKYYVVGgggdggggdggggddddK..',
      'KVKKKKYYYVVGgGgdggggdgggddddK...',
      'KVVVVGVVVVGGVVGdggggdgggddddK...',
      'KGVVGGGVVGGGVVGGggggdgggddddK...',
      '.KGGGKGGGGggGGGdggggdgggddddK...',
      '..KKKKGGKKggKGggKKggKKggKKddK...',
      '.....KGK.KgK.KgK.KgK.KgK.KdK....',
      '......K...K...K...K...K...K.....',
      '................................',
    ],
  },
};
