import type { SpriteDef } from '../sprite';

export const RANGER_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    G: 'green',
    g: 'midGreen',
    d: 'darkGreen',
    S: 'skin',
    s: 'skinShade',
    Y: 'gold',
    T: 'tan',
    B: 'brown',
    b: 'darkBrown',
    p: 'deepBrown',
    W: 'white',
    R: 'red',
    L: 'lightGray',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '...........KKKK.................',
      '..........KGGggKK...............',
      '..........KGggggdK..............',
      '..........KGgddddgK.............',
      '..........KGgdSKSSKK............',
      '......KKK.KGgdsSSSSbK...........',
      '......KWRKKGgdSSSsKLBK..........',
      '......KbbKKGgdSSsK.LKBK.........',
      '......KbbK.KggddK..LKBK.........',
      '......KbbKKgggYgdK.L.KBK........',
      '......KGdTTBBBBBbbBL.KBK........',
      '.....KGgdTBBBBBBbpBLKKBK........',
      '.....KGgdTBBBBBbbpBbbKBK........',
      '....KGggdTBBBBBbbpKBbSBS........',
      '....KGggdTBBBBBbppKLKsBs........',
      '....KGggdTbbbbYbbpKL.KBK........',
      '...KGgggdKTBBBBbppKL.KBK........',
      '...KGggdgKTBBBBbppKL.KBK........',
      '...KGggdgKBBBBbbppKL.KBK........',
      '...KGggdgKbbbbbpppKL.KBK........',
      '...KKKKKK.KpbKKpbK.LKBK.........',
      '..........KpbKKpbK.LKBK.........',
      '..........KBbKKBbK.LBK..........',
      '..........KpbKKpbKKbK...........',
      '..........KbBKKbBK.K............',
      '..........KbBKKbBK..............',
      '..........KbBBKbBBK.............',
      '..........KKKKKKKKK.............',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '...........KKKK.................',
      '..........KGGggKK...............',
      '..........KGggggdK..............',
      '..........KGgddddgK.............',
      '..........KGgdSKSSKK............',
      '......KKK.KGgdsSSSSbK...........',
      '......KWRKKGgdSSSsKLBK..........',
      '......KbbKKGgdSSsKL.KBK.........',
      '......KbbK.KggddK.L.KBK.........',
      '......KbbKKgggYgdL...KBK........',
      '......KGdTTBBBBBbLBK.KBK........',
      '.....KGgdTBBBBBBLpBbKKBK........',
      '.....KGgdTBBBBSbLpBBbSBSK.......',
      '....KGggdTBBBBSTTTTTTTTWLK......',
      '....KGggdTBBBBBLppKKKsBsK.......',
      '....KGggdTbbbbYbLpK..KBK........',
      '...KGgggdKTBBBBbLpK..KBK........',
      '...KGggdgKTBBBBbpLK..KBK........',
      '...KGggdgKBBBBbbpLK..KBK........',
      '...KGggdgKbbbbbpppL..KBK........',
      '...KKKKKK.KpbKKpbKL.KBK.........',
      '..........KpbKKpbK.LKBK.........',
      '..........KBbKKBbK.LBK..........',
      '..........KpbKKpbKKbK...........',
      '..........KbBKKbBK.K............',
      '..........KbBKKbBK..............',
      '..........KbBBKbBBK.............',
      '..........KKKKKKKKK.............',
      '................................',
    ],
  },
};
