import type { SpriteDef } from '../sprite';

export const RAT_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    H: 'lightGray',
    L: 'gray',
    M: 'slate',
    A: 'darkSlate',
    N: 'night',
    P: 'pink',
    p: 'skinShade',
    W: 'white',
    R: 'red',
    r: 'darkRed',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '.........KK.....................',
      '........KLMK....................',
      '.......KLPPAK...KKKK............',
      '.......KLPpAK.KKLLLLKK..........',
      '.....KKKMPpAKKLLHHMMLLK.........',
      '....KLLLMMAALLHLMMMMMMLK........',
      '...KLHLMMMMMLLMMMMMMMMMMK.......',
      '..KLMMMMMMMMMMMMMMMMMMMMAK......',
      '.KLMMRMMMMMMMMMMMMMMMMMMMAK.....',
      'KPMMMMMMMMAMMMMMMMMMMMMMAAK.....',
      '.KpMMMMMMAAMMMMMMMMMAMMAAAK.....',
      '..KAWMMMAAKAMMMMMMMAMMMAAAPK....',
      '...KKAAAKKKAAAMMMMMAMMAANNKPK.K.',
      '.....KKK...KAAAAAAAAAANNNK.KPKpK',
      '...........KNAKKKKKAANKKK...KppK',
      '..........KPPAK..KPANK.......KK.',
      '.........KPPKK..KPPKK...........',
      '..........KK.....KK.............',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '..........KKK...................',
      '.........KLMAK...KKKK...........',
      '........KLPPAK.KKLLLLKK.........',
      '......KKKMPpAKKLLHHMMLLK........',
      '....KKLLLMMAALLHLMMMMMMLK.......',
      '...KLLHLMMMMMLLMMMMMMMMMMK......',
      '..KLMMMMMMMMMMMMMMMMMMMMMAK.....',
      '.KLMMRMMMMMMMMMMMMMMMMMMMMAK....',
      'KPMMMMMMMMMAMMMMMMMMMMMMMAAK....',
      '.KWWMMMMMMAAMMMMMMMMMAMMAAAPK...',
      '..KrrrrMAAKKAMMMMMMMAMMMAANKPK..',
      '..KWrrMAAK.KAAAMMMMMAMMANNK.KPK.',
      '...KAAAAK.KKAAAAAAAAAANNNK...KPK',
      '....KKKKKKNAKKKKKKKKAANKK....KpK',
      '.......KPPAK........KKNPK....KpK',
      '......KPPKK...........KPPK....K.',
      '.......KK..............KK.......',
      '................................',
    ],
  },
};
