import type { SpriteDef } from '../sprite';

export const REAPER_SPRITE: SpriteDef = {
  width: 48,
  height: 48,
  legend: {
    K: 'black',
    W: 'white',
    L: 'lightGray',
    M: 'gray',
    A: 'slate',
    a: 'darkSlate',
    n: 'night',
    C: 'cyan',
    B: 'blue',
    N: 'navy',
    b: 'darkBrown',
    x: 'brown',
  },
  frames: {
    idle: [
      '.........................KKKKKKK................',
      '......................KKKnnnnnnnK...............',
      '.....................KnAnnnnnnnnnK..............',
      '..........KKKKK.....KAannnnnnnnnnnK.............',
      '........KKLLLLLK...KAannnnnnnnnnnnK.............',
      '.......KWWMMMaaK..KAannnnnnnnnnnnnnK............',
      '......KWLLMMMMMK.KAaKKKnnnnnnnnnnnnK............',
      '.....KWLLLLLLKK.KAaKKKKKKKnnnnnnnnnK............',
      '....KWLLLMMxbK..KAKLLLLMKKnnnnnnnnnnK...........',
      '...KWLLLMKKxbK...KWLLLLLMKnnnnnnnnnnK...........',
      '..KWLLLLK.KxbK..KWLLLLLLMKKnnnnnnnnnK...........',
      '..KWLLLMK.KxbK.KALKCLKCLMKKnnnnnnnnnK...........',
      '.KWLLLMK..KxbK.KALKKLKKLMKKnnnnnnnnnK...........',
      '.KWLLLK...KxbK.KAKLLLLLMKKKnnnnnnnnnK...........',
      '.KWLLMK...KxbK.KAKKWLWLMKKnnnnnnnnnnK...........',
      'KWLLLK....KxbK.KAKKLMLMKKKnnnnnnnnnnK...........',
      'KWLLMK....KxbK..KAKKKKKKKKnnnnnnnnnK............',
      'KWLLK.....KxbK...KKKKKKKKnnnnnnnnnK.............',
      'KWLLK.....KxbK..KAAnnnnnnnnnnnnnnnnK............',
      'KWLLK.....KxbK.KAaaaannnnnnnnnnnnnnK............',
      'KWMMK.....KxbKKAaaaannnnnnnnnnnnnnnK............',
      '.KKK......KxbKAaaaaannnnnnnnnnnnnnnnK...........',
      '.........KWLLKAaaaaannnannnnannnnnnnK...........',
      '.........KLMLLAaaanannnannnnannnnnnnnK..........',
      '.........KWLLAaannnannnannnnannnnnnnnK..........',
      '.........KLMLAnnnnaannnannnnannnnnnnnK..........',
      '..........KxbnnnnaaannnannnnannnnnnnnnK.........',
      '..........KxbKnnaaannnaannnnaannnnnnnnKKK.......',
      '..........KxbKKAaaannnaannnnaannnnnnnnnnnK......',
      '..........KxbKKAaaannnaannnnaannnnnnnnnnnnK.....',
      '..........KxbKKAaaannnaannnnaannnnnnnnnnnnAK....',
      '..........KxbKAaaaannnaannnnaannnnnnnnnnnnaAK...',
      '..........KxbKAaaaannnannnnnnannnnnnnnnnnKKKAK..',
      '..........KxbKAaaannnnannnnnnannnnnnnnnnK...K...',
      '..........KxbKAaaannnnannnnnnannnnnnnnnnK.......',
      '..........KxbKAaaannnnannnnnnannnnnnnnnnnK......',
      '..........KxbKAaaannnnannnnnnaannnnnnnnnnnKK....',
      '..........KxbKAaaannnaannnnnnaannnnnnnnnnnKAK...',
      '..........KxbKAaaannnaannnnnnaannnnnnnnnnnAaAK..',
      '..........KxbAaaaannnaannnnnnaannnnnnnnnnnaaaAK.',
      '..........KxbAaaannnnaannnnnnaannnnnnnnnnnaaaAK.',
      '..........KxbAaaannnnaannnnnnnnnnnnnnnnnnnaaKAK.',
      '..........KxbAaaannnnKnnnnnKnnnnnKKnnnnnKnaaKK..',
      '..........KxbAaaannnK.KnnnK.KnnnK..KnnnK.KKAK...',
      '..........KxbKKKKKnK...KnK...KnK....KnK....K....',
      '...........KK.....K.....K.....K......K..........',
      '................................................',
      '................................................',
    ],
    attack: [
      '.........................KKKKKKK................',
      '......................KKKnnnnnnnK...............',
      '...............KKK...KnAnnnnnnnnnK..............',
      '.............KKCCCK.KAannnnnnnnnnnK.............',
      '...........KKCCCCCKKAannnnnnnnnnnnK.............',
      '..........KCCCCCKKKAannnnnnnnnnnnnnK............',
      '.........KCWCKKK.KAaKKKnnnnnnnnnnnnK............',
      '........KWWCK...KAaKKKKKKKnnnnnnnnnK............',
      '.......KWWCK....KAKMMMMMKKnnnnnnnnnnK...........',
      '......KCWCKK.....KWWLLLLMKnnnnnnnnnnK...........',
      '.....KCWCKBBK...KWWWLLWLMKKnnnnnnnnnK...........',
      '.....KWCKBBK...KAMKCWKCWMKKnnnnnnnnnK...........',
      '....KCWCKBK....KAMKKMKKLMKKnnnnnnnnnK...........',
      '....KWCKBK.....KAKMWLWMMKKKnnnnnnnnnK...........',
      '...KCWKKBK.....KAKKWWWWMKKnnnnnnnnnnK...........',
      '...KWCKBKK.....KAKKLMLMKKKnnnnnnnnnnK...........',
      '...KWCKBKNK.....KAKKKKKKKKnnnnnnnnnK............',
      '..KCWKBBKNK......KKKKKKKKnnnnnnnnnK.............',
      '..KWCKBKKNK......KAAnnnnnnnnnnnnnnnK............',
      '..KWCKBKNNK.....KAaaaannnnnnaannnnnK............',
      '.KCWCKBKNK.....KAaaaaannnnnnaaaannnK............',
      '.KCWKBBKNK.....KAaaaaannnnnnaaaannnnK...........',
      '.KCWKBKKNK...KKAaaaaaanannnaaaannnnnK...........',
      '.KCWKBKKNK..KWLLMaaaaanannnaaaannnnnnK..........',
      '.KWLLLLKNKKKKLMLLaaaannannWLLMannnnnnK..........',
      '..KMMMMxxxxxxWLLMaaxxxxxxxLMLLxxxxnnnK..........',
      '..KMMMMLbbbbbLMLbAbbbbbbbbLLMbbbbbnnnnK.........',
      '..KMMMMMKKKKKKKAAaAnnnAAnnnnAAnnnnnnnnKKK.......',
      '..KWLLLMK.....KAaaannnaannnnaannnnnnnnnnnK......',
      '...KWLLLMK....KAaaannnaannnnaannnnnnnnnnnnK.....',
      '...KWLLLMK....KAaaannnaannnnaannnnnnnnnnnnAK....',
      '...KWLLLLMK..KAaaaannnaannnnaannnnnnnnnnnnaAK...',
      '....KWLLLMK..KAaaaannnannnnnnannnnnnnnnnnKKKAK..',
      '....KWLLLLMK.KAaaannnnannnnnnannnnnnnnnnK...K...',
      '.....KWLLLLMKKAaaannnnannnnnnannnnnnnnnnK.......',
      '.....KWLLLLLMKAaaannnnannnnnnannnnnnnnnnnK......',
      '......KWLLLLLMAaaannnnannnnnnaannnnnnnnnnnKK....',
      '.......KWLLLLLMaaannnaannnnnnaannnnnnnnnnnKAK...',
      '........KWLLLLLMMMnnnaannnnnnaannnnnnnnnnnAaAK..',
      '.........KWWLLLLLLMnnaannnnnnaannnnnnnnnnnaaaAK.',
      '..........KKWLLLLLMnnaannnnnnaannnnnnnnnnnaaaAK.',
      '............KALLLLMnnaannnnnnnnnnnnnnnnnnnaaKAK.',
      '............KAaaannnnKnnnnnKnnnnnKKnnnnnKnaaKK..',
      '............KAaaannnK.KnnnK.KnnnK..KnnnK.KKAK...',
      '.............KKKKKnK...KnK...KnK....KnK....K....',
      '..................K.....K.....K......K..........',
      '................................................',
      '................................................',
    ],
  },
};
