import type { SpriteDef } from '../sprite';

export const ROGUE_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    A: 'slate',
    H: 'darkSlate',
    N: 'night',
    S: 'skin',
    s: 'skinShade',
    R: 'red',
    r: 'darkRed',
    T: 'tan',
    B: 'brown',
    b: 'darkBrown',
    d: 'deepBrown',
    G: 'gold',
    W: 'white',
    L: 'lightGray',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '...........KKKK.................',
      '..........KAHHHKK...............',
      '..........KAHHHHHK..............',
      '..........KAHHNNNHK.............',
      '..........KAHNSKSSK.............',
      '..........KAHNsSSSSK............',
      '..........KAHNRRrrK.............',
      '..........KAHHRrrK..............',
      '...........KHHNNK...............',
      '........KRRrrrrrK...............',
      '.....KRrKTTBBBBBBbbK............',
      '.....KK.KbBBBBBBbdBbK...........',
      '........KTbBBBBbddBbK...........',
      '........KTBbbBBbddBbK...........',
      '........KTBBBGbbddBbK...........',
      '........KTBBBBBbddSsK...........',
      '.........KbbbGbbddSsK...........',
      '.........KTBBBBbdKGGGK..........',
      '.........KBBBBbdddKWK...........',
      '.........KbbbbddddKWK...........',
      '..........KHNKKHNKKLK...........',
      '..........KHNKKHNKKLK...........',
      '..........KANKKANK.K............',
      '..........KHNKKHNK..............',
      '..........KBbKKBbK..............',
      '..........KBbKKBbK..............',
      '..........KBBbKBBbK.............',
      '..........KKKKKKKKK.............',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '...........KKKK.................',
      '..........KAHHHKK...............',
      '..........KAHHHHHK..............',
      '..........KAHHNNNHK.............',
      '..........KAHNSKSSK.............',
      '..........KAHNsSSSSK............',
      '..........KAHNRRrrK.............',
      '..........KAHHRrrK..............',
      '...........KHHNNK...............',
      '........KRRrrrrrK...............',
      '.....KRrKTTBBBBBBbbK............',
      '.....KK.KbBBBBBBbdBbKKKKKK......',
      '........KTbBBBBbddBBBbSSGWWWLK..',
      '........KTBbbBBbddbbbbssGKKKKK..',
      '........KTBBBGbbddKKKKKKK.......',
      '........KTBBBBBbddK.............',
      '.........KbbbGbbddK.............',
      '.........KTBBBBbdK..............',
      '.........KBBBBbddK..............',
      '.........KbbbbdddK..............',
      '..........KHNKKHNK..............',
      '..........KHNKKHNK..............',
      '..........KANKKANK..............',
      '..........KHNKKHNK..............',
      '..........KBbKKBbK..............',
      '..........KBbKKBbK..............',
      '..........KBBbKBBbK.............',
      '..........KKKKKKKKK.............',
      '................................',
    ],
  },
};
