import type { SpriteDef } from '../sprite';

export const SHADE_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    N: 'night',
    P: 'plum',
    M: 'magenta',
    Q: 'pink',
    W: 'white',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '...............KKK..............',
      '.............KKPPPK.............',
      '............KPPMMPPK............',
      '...........KPMMNNNPPK...........',
      '..........KPMNNNNNNPPK..........',
      '.........KPMNKKKKNNNPK..........',
      '........KPMNKKKKKKNNPK..........',
      '........KPMKWQKWQKNNNPK.........',
      '........KPMKKKKKKKNNNPK.........',
      '........KPMNKKKKKNNNNPK.........',
      '.........KPMNNKKNNNNNNPK........',
      '..KK.....KPNNNNNNNNNNNNPK.......',
      '.KQMKKKKKPMNNNNNNNNNNNNPK.......',
      'KQMMMPPPPMNNNNNNNNNNNNNPK.......',
      '.KQMMKKKPNNNNPPNNNNNNNNPK.......',
      '..KQK.KKPPNNNNNPPNNNNNNPK.......',
      '...KKKQMPPNNNNNNNPPNNNNPK.......',
      '...KQMMPPPNNPPNNNNNPPNPPK.......',
      '....KQMPPPPNNNPPNNNNNPPPK.......',
      '.....KKPMPPPNNNNPPNNNNNPK.......',
      '......KMPKKPPNNNNNPPNNNPK.......',
      '.......KK.KMPPPNNNNNPPNPK.......',
      '.........KMPKKPPNNNNNNPPPK......',
      '..........KK.KMPPPNNNNNNPK......',
      '............KMPKKPPPNNNNPK......',
      '.............KK.KMPPPPNNPPK.....',
      '.................KKKMPPPPMK.....',
      '....................KKKKKK......',
      '................................',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '...................KKK..........',
      '.................KKPPPK.........',
      '................KPPMMPPK........',
      '...............KPMMNNNPPK.......',
      '..............KPMNNNNNNPPK......',
      '.............KPMNKKKKNNNPK......',
      '............KPMNKKKKKKNNPK......',
      '............KPMKWWKWWKNNNPK.....',
      '............KPMKKKKKKKNNNPK.....',
      '...KKK......KPMNKKKKKNNNNPK.....',
      '..KPPPK......KPMNNKKNNNNNNPK....',
      '.KPMMMPK..KKKKPNNNNNNNNNNNNPK...',
      'KPMQWQMPKKQMPPMNNNNNNNNNNNNPK...',
      'KPMQQNMPKKQMMPNNNNNNNNNNNNNPK...',
      'KPMQNKMPKKQMMNNNNPPNNNNNNNNPK...',
      '.KPMNMPK..KKPPNNNNNPPNNNNNNPK...',
      '..KPPPK....KPPNNNNNNNPPNNNNPK...',
      '...KKK.....KPPNNPPNNNNNPPNPPK...',
      '...........KPPPNNNPPNNNNNPPPK...',
      '..........KPMPPPNNNNPPNNNNNPK...',
      '..........KMPKKPPNNNNNPPNNNPK...',
      '...........KK.KMPPPNNNNNPPNPK...',
      '.............KMPKKPPNNNNNNPPPK..',
      '..............KK.KMPPPNNNNNNPK..',
      '................KMPKKPPPNNNNPK..',
      '.................KK.KMPPPPNNPPK.',
      '.....................KKKMPPPPMK.',
      '........................KKKKKK..',
      '................................',
      '................................',
    ],
  },
};
