import type { SpriteDef } from '../sprite';

export const SHAMAN_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    G: 'green',
    g: 'midGreen',
    Y: 'yellow',
    R: 'red',
    O: 'orange',
    B: 'brown',
    b: 'darkBrown',
    W: 'white',
    M: 'magenta',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '....KKK.........................',
      '...KWWWK........................',
      '...KKWKK........................',
      '...KWWWK....R.O.R...............',
      '....KWK....KRKOKRK..............',
      '....KWK....KRKOKRK..............',
      '....KWK...KKBBBBBKK.............',
      '....KWKKK.KGGGGGGgK.KK..........',
      '....KWK.KGKGYGGYGgKgK...........',
      '....KWK...KGGGGGGgK.............',
      '....KWK...KGWKKKWgK.............',
      '....KWK....KGGGGgK..............',
      '....KWK.....KKKKK...............',
      '....KWK...KBBWBWBBK.............',
      '....KWK..KBBBBBBBBbK............',
      '....KGGGBBBBBBBBBBbK............',
      '....KGGGKBBBBBBBBBbK............',
      '....KWK..KBBBBBBBBbK............',
      '....KWK..KbBBBBBBBbK............',
      '....KWK..KbBBBBBBBbK............',
      '....KWK.KbBBBBBBBBBbK...........',
      '....KWK.KbBBBBBBBBBbK...........',
      '....KWK.KbbBbBbBbBbbK...........',
      '....KWK..KKGGKKGGKK.............',
      '....KWK...KGGKKGGK..............',
      '....KWK...KggKKggK..............',
      '....KWK..KbbbKbbbK..............',
      '....KKK..KKKKKKKKK..............',
      '................................',
    ],
    attack: [
      '................................',
      '..M.....M.......................',
      '................................',
      '....KKK.........................',
      '.M.KWWWK........................',
      '...KMWMK........................',
      '...KWWWK....R.O.R...............',
      '....KWK.M..KRKOKRK..............',
      '....KWK....KRKOKRK..............',
      '....KWK...KKBBBBBKK.............',
      '....KWKKK.KGGGGGGgK.KK..........',
      '....KWK.KGKGYGGYGgKgK...........',
      '....KWK...KGGGGGGgK.............',
      '....KWK...KGKRRRKgK.............',
      '....KWK....KGGGGgK..............',
      '....KWK.....KKKKK...............',
      '....KWK...KBBWBWBBK.............',
      '....KWK..KBBBBBBBBbK............',
      '....KGGGBBBBBBBBBBbK............',
      '....KGGGKBBBBBBBBBbK............',
      '....KWK..KBBBBBBBBbK............',
      '....KWK..KbBBBBBBBbK............',
      '....KWK..KbBBBBBBBbK............',
      '....KWK.KbBBBBBBBBBbK...........',
      '....KWK.KbBBBBBBBBBbK...........',
      '....KWK.KbbBbBbBbBbbK...........',
      '....KWK..KKGGKKGGKK.............',
      '....KWK...KGGKKGGK..............',
      '....KWK...KggKKggK..............',
      '....KWK..KbbbKbbbK..............',
      '....KKK..KKKKKKKKK..............',
      '................................',
    ],
  },
};
