import type { SpriteDef } from '../sprite';

export const SHOPKEEPER_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    S: 'skin',
    s: 'skinShade',
    R: 'red',
    r: 'darkRed',
    W: 'white',
    B: 'brown',
    b: 'darkBrown',
    G: 'gold',
    Y: 'yellow',
  },
  frames: {
    idle: [
      '................................',
      '..............KKKK..............',
      '.............KrRRrKK............',
      '............KrRRRRrGK...........',
      '............KrRRRRrKGK..........',
      '...........KrRRRRRRrGK..........',
      '..........KsSSSSSSSSsK..........',
      '.........KsSSSSSSSSSSsK.........',
      '.........KsSKSSSSSSKSsK.........',
      '.........KsSSSSSSSSSSsK.........',
      '.........KsSSSSssSSSSsK.........',
      '.........KsbbbbbbbbbbsK.........',
      '..........KbSSSSSSSSbK..........',
      '..........KsSSSSSSSSsK..........',
      '...........KssSSSSssK...........',
      '........KKKKKssssssKKKKK........',
      '.......KbBBBBWWWWWWBBBBbK.......',
      '......KbBBBBBWWWWWWBBBBBbK......',
      '.....KbBBBBBBWGWWGWBBBBBBbK.....',
      '.....KbBBBBBBWWWWWWBBBBBBbK.....',
      '.....KbBBBBBBWGWWGWBBBBBBbK.....',
      '.....KbBBBBBBWWWWWWBBBBBBbK.....',
      '.....KbBBBBBBWGWWGWBBBGYBbK.....',
      '.....KbSSSsBBWWWWWWBBsYGSbK.....',
      '.....KbSSSsBBWWWWWWBBsSSSbK.....',
      '.....KbbbbbbbbbbbbbbbbbbbbK.....',
      '.....KbBBBBBBBBBBBBBBBBBBbK.....',
      '.....KbBBBBBBBBBBBBBBBBBBbK.....',
      '.....KbBBBBBBBBBBBBBBBBBBbK.....',
      '.....KbBBBBBBBBBBBBBBBBBBbK.....',
      '.....KbBBBBBBBBBBBBBBBBBBbK.....',
      '......KKKKKKKKKKKKKKKKKKKK......',
    ],
    attack: [
      '................................',
      '..............KKKK..............',
      '.............KrRRrKK............',
      '............KrRRRRrGK...........',
      '............KrRRRRrKGK..........',
      '...........KrRRRRRRrGK..........',
      '..........KsSSSSSSSSsK..........',
      '.........KsSSSSSSSSSSsK.........',
      '.........KsSKSSSSSSKSsK.........',
      '.........KsSSSSSSSSSSsK.........',
      '.........KsSSSSssSSSSsK.........',
      '.........KsbbbbbbbbbbsK.........',
      '..........KbSSSSSSSSbK..........',
      '..........KsSSSSSSSSsK..........',
      '...........KssSSSSssK...........',
      '........KKKKKssssssKKKKK........',
      '.......KbBBBBWWWWWWBBBBbK.......',
      '......KbBBBBBWWWWWWBBBBBbK......',
      '.....KbBBBBBBWGWWGWBBBBBBbK.....',
      '.....KbBBBBBBWWWWWWBBBBBBbK.....',
      '.....KbBBBBBBWGWWGWBBBBBBbK.....',
      '.....KbBBBBBBWWWWWWBBBBBBbK.....',
      '.....KbBBBBBBWGWWGWBBBGYBbK.....',
      '.....KbSSSsBBWWWWWWBBsYGSbK.....',
      '.....KbSSSsBBWWWWWWBBsSSSbK.....',
      '.....KbbbbbbbbbbbbbbbbbbbbK.....',
      '.....KbBBBBBBBBBBBBBBBBBBbK.....',
      '.....KbBBBBBBBBBBBBBBBBBBbK.....',
      '.....KbBBBBBBBBBBBBBBBBBBbK.....',
      '.....KbBBBBBBBBBBBBBBBBBBbK.....',
      '.....KbBBBBBBBBBBBBBBBBBBbK.....',
      '......KKKKKKKKKKKKKKKKKKKK......',
    ],
  },
};
