import type { SpriteDef } from '../sprite';

export const SKELETON_KNIGHT_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    W: 'white',
    L: 'lightGray',
    M: 'gray',
    A: 'slate',
    a: 'darkSlate',
    n: 'night',
    H: 'hotRed',
    R: 'red',
    r: 'darkRed',
    d: 'deepBrown',
    B: 'brown',
    b: 'darkBrown',
    O: 'rust',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '..............KKKK..............',
      '.............KRRRrKK....K.......',
      '............KRRRRrrrK..KWK......',
      '...........KMMMAAARrrK.KWLK.....',
      '..........KMMAAAAAaarrKKWLK.....',
      '..........KMAAAAAaaaKrKKWLK.....',
      '.........KMMMMAAAaanKK.KWLK.....',
      '..........KHKWHKaaanK..KWLK.....',
      '..........KWLKWLaanK...KWLK.....',
      '..........KWKWKWLanK...KWLK.....',
      '...KKKKKKKKKLWLManKKK..KWLK.....',
      '..KMMMMMMMAaMALMMMAAaK.KWLK.....',
      '..KMRRRRRrraMMMAAAMMAaKKWLK.....',
      '..KMRRWWWrraMMAAAaAAanKKWLK.....',
      '..KMRWWWLrdaMAAAAaaWLKKKWLKK....',
      '..KMRWKWKddaMAAAaaaLWLAMMAAaK...',
      '..KMrrWLWddaAAAaaanKKKMAAAaK....',
      '..KMrrLrLddaAAaOaanK..KKBbK.....',
      '..KArrrddddaKaWLWanK...KAaK.....',
      '...KArrdddaKbbBbbbbdK...KK......',
      '...KArrddnaKMAAaAAanK...........',
      '....KArddnK.KWLKKLMK............',
      '....KAddanK.KWLKKLMK............',
      '.....KAanK.KMAaKKAanK...........',
      '......KnK..KMAaKKAanK...........',
      '.......K...KMAaKKAanK...........',
      '..........KKMAaKKaanK...........',
      '.........KMMAAaKAAanK...........',
      '..........KKKKK.KKKK............',
      '................................',
    ],
    attack: [
      '...........................KWLK.',
      '..........................KWLK..',
      '.............KKKK........KWLK...',
      '............KRRRrKK.....KWLK....',
      '...........KRRRRrrrK...KWLK.....',
      '..........KMMMAAARrrK.KWLK......',
      '.........KMMAAAAAaarrKWLK.......',
      '.........KMAAAAAaaaKMWLK........',
      '........KMMMMAAAaanMAAK.........',
      '.........KHKWHKaaabAaMK.........',
      '.........KWLKWLaanKWLK..........',
      '.........KWKWKWLanWLK...........',
      '..KKKKKKKKKLWLManWLK............',
      '.KMMMMMMMAaMALMMMAAaK...........',
      '.KMRRRRRrraMMMAAAMMAaK..........',
      '.KMRRWWWrraMMAAAaAAanK..........',
      '.KMRWWWLrdaMAAAAaaKKK...........',
      '.KMRWKWKddaMAAAaaaK.............',
      '.KMrrWLWddaAAAaaanK.............',
      '.KMrrLrLddaAAaOaanK.............',
      '.KArrrddddaKaWLWanK.............',
      '..KArrdddaKbbBbbbbdK............',
      '..KArrddnaKMAAaAAanK............',
      '...KArddnK.KKWLKKLMK............',
      '...KAddanK..KWLKKLMK............',
      '....KAanK..KMAaKKAanK...........',
      '.....KnK...KMAaKKAanK...........',
      '......K....KMAaKKAanK...........',
      '..........KKMAaKKaanK...........',
      '.........KMMAAaKAAanK...........',
      '..........KKKKK.KKKK............',
      '................................',
    ],
  },
};
