import type { SpriteDef } from '../sprite';

export const SLIME_KING_SPRITE: SpriteDef = {
  width: 48,
  height: 48,
  legend: {
    C: 'cyan',
    G: 'green',
    K: 'black',
    L: 'lightGray',
    M: 'gray',
    O: 'orange',
    R: 'red',
    S: 'sand',
    W: 'white',
    Y: 'yellow',
    b: 'darkBrown',
    c: 'blue',
    d: 'darkGreen',
    e: 'deepBrown',
    g: 'midGreen',
    o: 'gold',
    r: 'darkRed',
    s: 'tan',
    u: 'rust',
    x: 'orangeBrown',
  },
  frames: {
    idle: [
      '................................................',
      '...............................K................',
      '........................K.....KYK...............',
      '.................K.....KYK...KYOK...............',
      '................KYK...KYoOK.KYoOK...............',
      '................KYOK..KYoOK.KYoOK...............',
      '................KYoOK.KooOOKKooOK...............',
      '................KYoOKKYoooOOYooOK...............',
      '................KYooOYoooooooooOK...............',
      '................KYoooooooooooRrOK...............',
      '................KYoooooCcoooouoOK...............',
      '................KYRrooYccooooooOK...............',
      '................KYrroooooooooxxxK...............',
      '................KYoooooxxxxxxGGGK...............',
      '..............KKGxxxxxxGGGGGGGGGKK..............',
      '............KKGGGGWGGWGGGGGGGGGGgdKK............',
      '...........KGGGGGGGGGGGGGGGGGGGGGGgdK...........',
      '..........KGGGGGGGGGGGGGGGGGGGGGGGGgdK..........',
      '.........KGGWWGGGGGGGGGGGGGGGGGGGGGGgdK.........',
      '........KGGWGGGGGGGGGGGGGGGGGGGGGGGGGgdK........',
      '.......KGGWGGGGGGGGGGGGGGGGGGGGGGGGGGGgdK.......',
      '......KGGWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgdK......',
      '......KGWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgdK......',
      '.....KGWGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgdK.....',
      '.....KGWddGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGgdK.....',
      '....KGWGddddGGGGGGGGGGGGddGGGGGGGGGGGGGGGgdK....',
      '....KGWGGddddddGGGGGGGddddGGGGGGGGGGGGGGGgdK....',
      '....KGGGGGGGddddGGGGdddddGGGoGGGGGGGGGGGGgdK....',
      '...KGGWGGGGGGGddGGGddddGGGGGGeGGbGGGGGGGGGgdK...',
      '...KGGWGGGWWKKGGGGGddGGGGGGGGGebGGGGGGGGGGgdK...',
      '...KGGGGGGKKKKGGGGGGWWKKGGggggbLLggggGGGGGgdK...',
      '...KGGGGGGKKKKGGGGGGKKKKgggggbgLMLgggggGGGgdK...',
      '..KGGGGGGGGGGGGGGGGGKKKKggggggggLMLggggggYYgdK..',
      '..KGGGGGGGGGGGGGGGGGGggggggggggggLMLggggYooodK..',
      '..KGGGGGGGGGGGGGGGGGggggggggggggggLMLgggYooOdK..',
      '..KGGGGGGGGGGGKKKKKKgggggggggggggggLMLgggOOgdK..',
      '..KGGGGGGGGGGKGggggGKgGgggggggggggggSSSgggggdK..',
      '..KGGGGGGGGGKGGGGGGggKgggggggggggggSSSSsggggdK..',
      '..KGGGGGGGGGGGGGGGGGgggggggggggggggSKSKsggggdK..',
      '..KGGGGGGGGGGGGGGGGGggggggggggggggggSSsgggggdK..',
      '..KGGGGGGGGGGGGGGGGSSgggggggSSggggggsgsgggggdK..',
      '..KGGGGGGGGGGGGGGGGGSSSSSSSSsgggggggggggggGgdK..',
      '..KGGGGGGGGGGGGGGGGssGggggggssgggGgggggggGGgdK..',
      '..KGGGGGGGGGGGGGGGGGGGGGgggggggggggggggGGGGgdK..',
      '.KggggggggggggggggggggggggggggggggggggggggggggK.',
      '.KddddddddddddddddddddddddddddddddddddddddddddK.',
      'KddddddddddddddddddddddddddddddddddddddddddddddK',
      '.KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.',
    ],
    attack: [
      '................................................',
      '.............................K..................',
      '......................K.....KYK.................',
      '...............K.....KYK...KYOK.................',
      '..............KYK...KYoOK.KYoOK.................',
      '..............KYOK..KYoOKKKYoOK.................',
      '..............KYoOKKYooOOOYooOK.................',
      '..............KYoOKKooooOooooOK.................',
      '..............KYooOYoooooooooOK.................',
      '..............KYoooooooooooRrOK.................',
      '..............KYooooYCcoooouoOK.................',
      '..............KYRroooccooooooOK.................',
      '..............KYrroooooooKKKKK..................',
      '..............KYooooKKKKK.......................',
      '.........KK....KKKKK................KK..........',
      '........KWGK.......................KWGK.........',
      '........KGgK.......................KGgK.........',
      '.........KK.........................KK..........',
      '.....KK.........................................',
      '....KWGK..................................KK....',
      '....KGgK.................................KWGK...',
      '.....KK..................................KGgK...',
      '..................KKKKKKKKKKKK............KK....',
      '...............KKKGGGGGGGGGGgdKKK...............',
      '..KK..........KGGGGGGGGGGGGGGGGgdK..............',
      '.KWGK.......KKGGGGGGGGGGGGGGGGGGgdKK.........KK.',
      '.KGgK.....KKGGGGGGGGGGGGGGGGGGGGGGgdK.......KWGK',
      '..KK...KKKWWGGGGGGGGGGGGGGGGGGGGGGGgdK......KGgK',
      '......KddWGGGGGGGGGGGGddGGGGGGGGGGGGgdK......KK.',
      '......KddddGGGGGGGGGddddGGGGGGGGGGGGGgdK........',
      '......KWdddddGGGGGdddddGGGGGGGGGGGGGGGgdK.......',
      '.....KWGGGddddGGGddddGGGGGGGGGGGGGGGGGGgdK......',
      '....KWKGGWWKKdGGGdWWKKGGGGGGGGGGGGGGGGGgdK......',
      '....KWGGGKKKKGGGGGKKKKGGGGGGGGGGGGGGGGGGgdK.....',
      '...KWGGGGGGGGGGGGGGGGGGGGGbggggggggggGGGGgdK....',
      '...KWGGGGGGGGGGGGGGGGGGgoebLLLLLLLLLggggGgdK....',
      '...KGGGGGGGGWKKKKKWGGgggggbMMMMMMMMggggggSSSK...',
      '..KWGGGGGGGGKKKKKKKgggggggggggggggggggggSSSSsK..',
      '..KWGGGGGGGKKKKKKKKKgggggggggggSSgggggggSKSKsK..',
      '..KGGGGGGGGKKKKrKKKKgggYYgggggggSSSSSSSSsSSsdK..',
      '..KGGGGGGGGGrrrrrrrgggYooogggggssgggggggssgsdK..',
      '.KKGGGGGGGGGGRRRrrGgggYooOggggggggggggggggggdKK.',
      'KdKGGGGGGGGGGGGGGGGGGggOOgggggggggggggggggGgdKdK',
      'KdKGGGGGGGGGGGGGGGGGGGGgggggggggggggggggGGGgdKdK',
      '.KggggggggggggggggggggggggggggggggggggggggggggK.',
      'KddddddddddddddddddddddddddddddddddddddddddddddK',
      'KddddddddddddddddddddddddddddddddddddddddddddddK',
      '.KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK.',
    ],
  },
};
