import type { SpriteDef } from '../sprite';

export const SLIME_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    G: 'green',
    g: 'midGreen',
    d: 'darkGreen',
    W: 'white',
    R: 'darkRed',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '............KKKKKKKK............',
      '..........KKGGGGGGGGKK..........',
      '.........KGGWWGGGGGGGGK.........',
      '........KGWWGGGGGGGGGGgK........',
      '.......KGGWGGGGGGGGGGGGgK.......',
      '......KGGGGGGGGGGGGGGGGGgK......',
      '......KGGKKGGGKKGGGGGGGGgK......',
      '.....KGGGKWGGGKWGGGGGGGGGgK.....',
      '.....KGGGKKGGGKKGGGGGGGGGgK.....',
      '.....KGGGGGGGGGGGGGGGGGGGgK.....',
      '....KGGGGGKKGGGGGGGGGGGGGGgK....',
      '....KGGGGGGGGGGGGGGGGGGGGGgK....',
      '....KgGGGGGGGGGGGGGGGGGGGggK....',
      '....KggGGGGGGGGGGGGGGGGGgggK....',
      '....KdggggggggggggggggggddK.....',
      '.....KddddddddddddddddddddK.....',
      '......KKKKKKKKKKKKKKKKKKKK......',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '............KKKKKKKK............',
      '..........KKGGGGGGGGKK..........',
      '.........KGGWWGGGGGGGGK.........',
      '........KGWWGGGGGGGGGGgK........',
      '.......KGGWGGGGGGGGGGGGgK.......',
      '......KGGGGGGGGGGGGGGGGGgK......',
      '......KGGKKGGGKKGGGGGGGGgK......',
      '.....KGGGKWGGGKWGGGGGGGGGgK.....',
      '.....KGGGKKGGGKKGGGGGGGGGgK.....',
      '.....KGGGGGGGGGGGGGGGGGGGgK.....',
      '....KGGGGKKKKGGGGGGGGGGGGGgK....',
      '....KGGGGKRRKGGGGGGGGGGGGGgK....',
      '....KgGGGGKKGGGGGGGGGGGGGggK....',
      '....KggGGGGGGGGGGGGGGGGGgggK....',
      '....KdggggggggggggggggggddK.....',
      '.....KddddddddddddddddddddK.....',
      '......KKKKKKKKKKKKKKKKKKKK......',
      '................................',
    ],
  },
};
