import type { SpriteDef } from '../sprite';

export const SPIDER_QUEEN_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    n: 'night',
    A: 'darkSlate',
    a: 'slate',
    M: 'gray',
    R: 'red',
    r: 'darkRed',
    W: 'white',
    L: 'lightGray',
    H: 'hotRed',
    G: 'green',
    g: 'midGreen',
    Y: 'gold',
    y: 'yellow',
    O: 'orange',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '....K...............KKKKK.......',
      '...KMK............KKMMMMMKK.....',
      '..KaaK...........KMMMaaaMMaK....',
      '..KaKaK.........KMMaaaaaaaaAK...',
      '.KaKKaK........KMLMaaaaaaaAAAK..',
      '.KaKKaK.......KMLaaaaaaaaAAAAAK.',
      'KaK.KaK.......KMaaaaaaaaAAAAAAK.',
      'KnK..KaKK.K.KKMMaaaaaaaAAAAAAAAK',
      '.K...KaKyKyKyKMaaaaaaaaAAAAAAAAK',
      '.....KaKYYYYOKMaaaaaaaaAAAAAAAnK',
      '......KaORYROKMaaaaAaaaAAAAAAnnK',
      '.....KMMMMMMaanaaaAAAaAAAAAAnnnK',
      '....KMaHaHaaaAnaAAAAAAAAAAAnnnnK',
      '....KMHaaaaaAAnAAAAAAAAAAnnnnnnK',
      '....KaaaaaaAAAnAAAAAAAAAnnnnnnK.',
      '....KaaaaAAAAnnAAAAAAAAnnnnnnnK.',
      '...KaaAaAAAnnnnKAAAAAAnnnnnnnK..',
      '...KAAnAAnnnnnK.KAAAnnnnnnnnAaK.',
      '...KrnrAnnnnnKaKKaAnnnnannnKKMK.',
      '...KWKWaKnnKKKaK.KaKnnnnaKK..KLK',
      '...KGKLaKAK..KaK.KaKKKAKKaaK..K.',
      '...KgKaKKAK.KaK...KaKKAK.KKMK...',
      '....KKMKAK..KaK...KMK.KaK.KaK...',
      '.....KaKaK..KMK...KaK..KAK.KaK..',
      '....KaKKAK..KaK....KaK.KAK.KaK..',
      '....KaKAK..KaK.....KaK..KAK.KaK.',
      '....KnKnK..KnK.....KnK..KnK.KnK.',
      '.....K.K....K.......K....K...K..',
      '................................',
    ],
    attack: [
      '......KKK.......................',
      '...K.KnAAKKK....................',
      '..KMK.KKKAAaK...................',
      '.KaaK....KKAK.......KKKKK.......',
      '.KaKaK....KAK.....KKMMMMMKK.....',
      'KaKKaK.....KAK...KMMMaaaMMaK....',
      'KnKKaK.....KAK..KMMaaaaaaaaAK...',
      '.K..KaK.K.KKAK.KMLMaaaaaaaAAAK..',
      '....KaKKyKyKyAKMLaaaaaaaaAAAAAK.',
      '....KaKKYYYYOAKMaaaaaaaaAAAAAAK.',
      '.....KaKORYROAMMaaaaaaaAAAAAAAAK',
      '.....KMMMMMMaanaaaaaaaaAAAAAAAAK',
      '....KMaHaHaaaAnaaaaaaaaAAAAAAAnK',
      '.K..KMHaaaaaAAnaaaaAaaaAAAAAAnnK',
      'KgK.KaaaaaaAAAnaaaAAAaAAAAAAnnnK',
      'KgGKaaaaaAAAAnnaAAAAAAAAAAAnnnnK',
      'KGKGAaAaAAAnnnnAAAAAAAAAAnnnnnnK',
      'KGgGrnrAAnnnnnKAAAAAAAAAnnnnnnK.',
      '.KGGWKWKnnnnnKKAAAAAAAAnnnnnnnK.',
      'KGgKLKK.KnnKAKKKAAAAAAnnnnnnnK..',
      'KgK.K..KaKKKAKaKKAAAnnnnnnnnAaK.',
      '.KK....KaK.KAKaKKaAnnnnannnKKMK.',
      '.KGK...KaKKAKKaK.KaKnnnnaKK..KLK',
      '..K...KaK.KAK.KaKKaKKKAKKaaK..K.',
      '......KMK.KAK.KaK.KaKKAK.KKMK...',
      '......KaK.KaK.KMK.KMK.KaK.KaK...',
      '......KaK.KAK.KaK.KaK..KAK.KaK..',
      '.....KaK.KAK.KaK...KaK.KAK.KaK..',
      '.....KaK.KAK.KaK...KaK..KAK.KaK.',
      '.....KnK.KnK.KnK...KnK..KnK.KnK.',
      '......K...K...K.....K....K...K..',
      '................................',
    ],
  },
};
