import type { SpriteDef } from '../sprite';

export const SPIDER_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    n: 'night',
    A: 'darkSlate',
    a: 'slate',
    M: 'gray',
    R: 'red',
    r: 'darkRed',
    W: 'white',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '.........K...........K..........',
      '........KMK.........KMK.........',
      '........KAK.........KAK.........',
      '....K...KAaK.......KaAK....K....',
      '...KMK..KAaK.......KaAK...KMK...',
      '...KAaKKAKaK.......KaKAK.KaAK...',
      '...KAaKKAKKaK.....KaKKAKKKaAK...',
      '..KAKKaKAKKaK.....KaAAAAAaKKAK..',
      '..KAK.KaAKKaK....KAMMaaAAAAKAK..',
      '..KAK.KaAK.KaK..KaaaaaaaaAAAAK..',
      '..KAK..KAKKKaK.KAaaaaaaaaAAAAK..',
      '..KAK..KAaAAAKKKAAaaaaaaAAAAAK..',
      '..KAK.KAARaaaAAAAAAAARRRAAAAAAK.',
      '.KAK..KARaraaaAnnAAAAARAAAAAnAK.',
      '.KAK..KrAAAAAAAAnAAAARRRAAAAnnK.',
      '.KAK..KAAAAAAAAnnAAAAAAAAAAnnAK.',
      '.KAK..KnnnAAAAnKKKAnAAAAAnnnKAK.',
      '.KAK..KWKWnnnKK...KKnnnnnnnKKAK.',
      '.KAK..KAKKKKK.......KKKAKKK.KAK.',
      'KAK..KAK...............KAK...KAK',
      'KAK..KAK...............KAK...KAK',
      'KnK..KAK...............KAK...KnK',
      '.K...KnK...............KnK....K.',
      '......K.................K.......',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '................................',
      '........K.......................',
      '.......KMK......................',
      '...K..KAaK......................',
      '..KMKKAKKaK..........K..........',
      '..KAaAK.KaK.........KMK.........',
      '.KAKaAK.KaK.........KAK.........',
      '.KAKAaK..KaK.......KaAK....K....',
      'KAKnKaK..KaK.......KaAK...KMK...',
      'KAKK.KaK.KaK.......KaKAK.KaAK...',
      'AK...KaK..KaK.....KaKKAKKKaAK...',
      'nK....KaK.KaK.....KaAAAAAaKKAK..',
      'K......KaKKaK....KAMMaaAAAAKAK..',
      '.......KaK.KaK..KaaaaaaaaAAAAK..',
      '........KaKKaK.KAaaaaaaaaAAAAK..',
      '........KaAAAKKKAAaaaaaaAAAAAK..',
      '.......KARaaaAAAAAAAARRRAAAAAAK.',
      '.......KRaraaaAnnAAAAARAAAAAnAK.',
      '......KrAAAAAAAAnAAAARRRAAAAnnK.',
      '.......KAAAAAAAnnAAAAAAAAAAnnAK.',
      '......KnnnAAAAnKKKAnAAAAAnnnKAK.',
      '.....KWKKnnnnKK...KKnnnnnnnKKAK.',
      '......K.KWKKK.......KKKAKKK.KAK.',
      '.........K.............KAK...KAK',
      '.......................KAK...KAK',
      '.......................KAK...KnK',
      '.......................KnK....K.',
      '........................K.......',
      '................................',
    ],
  },
};
