import type { SpriteDef } from '../sprite';

export const STONE_GOLEM_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    L: 'lightGray',
    M: 'gray',
    A: 'slate',
    N: 'darkSlate',
    Y: 'yellow',
    O: 'orange',
    g: 'midGreen',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '...........KKKKK................',
      '..........KMMMMMK...............',
      '.........KMLLLLMAK..............',
      '........KMLLLLLMAAK.............',
      '........KLYYLYYMAAK.............',
      '.......KKMLLLLLMAAKK............',
      '.....KKMMMMMMMMMAAAAKK..........',
      '....KMMLLLLLLLLMMMAAAAKK........',
      '...KMLLLLLLLLLOLMMMAAAAAK.......',
      '..KMLLLLMLLLLOLLLMMAAAAAAK......',
      '..KMLLLMMLLLOOLLLMMAAAAAAK......',
      '..KMLLMMMLLLOLLLLMMAAAAAAAK.....',
      '.KMLLLMAKMLOLLLLMMAAAKAAAAK.....',
      '.KMLLMAAKMMLLLLMMMAAAKAAAAK.....',
      '.KMLLMAAKMMMLLMMMAAAAKAAAAK.....',
      'KMLLLLMAKMgMMMMMAAAAAKAAAAAK....',
      'MLLLLLMAAKMMMMMAAAAAKKAAAAAK....',
      'MLLLLMMAAKgMMMAAAAgAKKAAAAAK....',
      'MMLLMMMAAKKMMMAAAAAK.KAAAAK.....',
      'KMMMMMAAK.KMMAAAAAAK.KNAANK.....',
      '.KNNNNNK..KMMAAAAAAK..KKKK......',
      '..KKKKK..KMLLMAKMMAAK...........',
      '.........KMLLMAKMMAAK...........',
      '.........KMLLMAKMMAAK...........',
      '........KMLLLMAKMMAAAK..........',
      '........KMMMMAAKMMAAAK..........',
      '........KNNNNNNKNNNNNK..........',
      '.........KKKKKK.KKKKK...........',
      '................................',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '.........KKKKK..................',
      '........KMMMMMK.................',
      '.......KMLLLLMAK................',
      '......KMLLLLLMAAK...............',
      '......KLYYLYYMAAK...............',
      '..KKKKKMLLLLLMAAKKK.............',
      '.KMMMMMMMMMMMMMAAAAKK...........',
      'KMLLLLLLLLLLLLMMMAAAAKK.........',
      'MLLLLLLLLLLLLOLLMMAAAAAK........',
      'MLLLLLLMLLLLOLLLMMAAAAAAK.......',
      'MMLLLLMMLLLOOLLLMMAAAAAAK.......',
      'KMMMMMMMMLLOLLLLLMMAAAAAAK......',
      '.KNNNNKKMLOLLLLMMAAAKAAAAK......',
      '..KKKK.KMMLLLLMMMAAAKAAAAK......',
      '.......KMMMLLMMMAAAAKAAAAK......',
      '.......KMgMMMMMAAAAAKAAAAAK.....',
      '........KMMMMMAAAAAKKAAAAAK.....',
      '........KgMMMAAAAgAKKAAAAAK.....',
      '.........KMMMAAAAAK.KAAAAK......',
      '.........KMMAAAAAAKKKNAANK......',
      '........KMLLMAKKMMAAKKKKK.......',
      '.......KMLLMAK..KMMAAK..........',
      '......KMLLMAK....KMMAAK.........',
      '.....KMLLLMAK....KMMAAAK........',
      '.....KMMMMAAK....KMMAAAK........',
      '.....KNNNNNNK....KNNNNNK........',
      '......KKKKKK......KKKKK.........',
      '................................',
      '................................',
    ],
  },
};
