import type { SpriteDef } from '../sprite';

export const TROLL_SPRITE: SpriteDef = {
  width: 48,
  height: 48,
  legend: {
    A: 'slate',
    B: 'brown',
    G: 'green',
    H: 'hotRed',
    K: 'black',
    L: 'lightGray',
    M: 'gray',
    R: 'red',
    S: 'sand',
    Y: 'yellow',
    a: 'darkSlate',
    b: 'darkBrown',
    d: 'darkGreen',
    e: 'deepBrown',
    g: 'midGreen',
    n: 'night',
    r: 'darkRed',
    s: 'tan',
    u: 'rust',
    x: 'orangeBrown',
  },
  frames: {
    idle: [
      '........................................KK......',
      '......................................KKggK.....',
      '.....................................KGgKK......',
      '.........................KKKKKKKKKKK..KgK.......',
      '........................KMMMMMMMMMuuK.KxgKKK....',
      '......................KKMMAGGGGGAuxxgKxBBBBbK...',
      '.............K...K..KKMMGGGGggggGGGSGxBBebbeK...',
      '............KbK.KbKKbnMGGgggggggggddKxBBBbBbK...',
      '...........KbBbKbBbbBbnMdddggggddGGGAxxBBBBbeK..',
      '..........KbBBBbBBBBBbnMMMMdddddGGgddBBBBbbeeK..',
      '.........KbBBBBBBBBBbbbnMMMMMMMMMdddGxBBBbeKK...',
      '........KbBBMMMBBBbbbbenMMMMMMMMAAAAGxBBBbeK....',
      '........KMMMAAAMBbbbbeenAAMAAAAAAAAAxBBBBbeK....',
      '.......KMMAAAAAAMbbbeeenAAAAAAAAAAAAxBBbbeK.....',
      '......KMMMMMMMAAAAbbeeenAAAAAAAAAAAAxBBBbeK.....',
      '......KMAnnnnnAAAAAMAeennAAAAAAAAAAAKxBBbeK.....',
      '......KMAnYKnAAAAAMMAaennnAAAAAAAAaaxBbeeK......',
      '.....KMMAAnnAAAAAAAMAAannnAAAAAAAaaaxBbeKnK.....',
      '....KMMAAAAAAAAAAAAaAaannnnAAAAAaaaaxBbeKnnK....',
      '...KMMAAAAAAAAAAAAAAaaannnAAAAaaaaaxxBbeKnnK....',
      '..KMMAAAAnAAAAAAAAAAaannnnAAAaaaaaaxBbeKannK....',
      '..KMAAAAnnaAAAAAAAAAaannnAAAaaaaaaaxBbeKnnnK....',
      '..KnAAAnnKKaAAAAAAAaannnAAaaaaaaaaaxBbeKnanK....',
      '...KnnnKSAnnnnnnAAAaannAAaaaaaaaaaxBbeKananK....',
      '....KKKMASAAAAASAAaaannAaaaaaaaaaaaaaannnnnK....',
      '...K..KMAAAAAAAAAAaannnaaaaaaaaaaaaaaannanK.....',
      '..KgK..KnaaaaaaaaannnnaaaaaaaaaaaaaaaannnnK..K..',
      '.KgGgK..KKKnnnnnnnnnnaaaaaaaaaaaaaaaaannnK..KgK.',
      '..KgK.....KMAAAAaannnaaaaaaaaaaaaannnnnnnK.KgGgK',
      '...K.....KMMAAAAAAnKMaaaaaaaaaaaaaKKaannK...KgK.',
      '.........KMAAAAAAAnneeeeeeeeSLeeeeeeeeeeeK...K..',
      '.........KMAAAAAAAnnBBBBBBBBsBBBBBBBBbbeK.......',
      '........KMMAAAAAAnnnBBBBBBBBBBBBBBBBBbeeK.......',
      '........KMAAAAAAAnKsbbbBBBBbBbBBBbbbbbeK........',
      '........KMAAAAAAAnKeeeebBBbbeebBbbeeebenK.......',
      '........KMAMAAAAnnKeKMAsbbbeeKsbbeeaaeenK.......',
      '........KMMMMMAAnK.KMMAAsbeeK.KseeaaaaannK......',
      '.......KMMAAAAnAnK..KMAAAeenK..KeaaaaaanK.......',
      '.......KMAAAAAnnnK.KMMAAAAnK....KaaaaaannK......',
      '.......KMaaaaannK...KMAAAAnK.....KaaaaanK.......',
      '.......KMAAAAnnK...KMMAAAAnK.....KaaaaannK......',
      '........KnnnnnK..KKKKMAAAAnKK.KKKKaaaaanK.......',
      '.......KSKSnSK..KMMMMMMMMMMMnKaaaaaaaaaanK......',
      '........K.KKK...KMAAAAAAAAAAnKaaaaaaaaaanK......',
      '...............KMMAAAAAAAAAAnnaaaaaaaaaanK......',
      '...............KMAAAAAAAAAAAnnaaaaaaaaaanK......',
      '...............KSnSnSnnnnnnnnnnLnLnnnnnnnK......',
      '................KKKKKKKKKKKKKKKKKKKKKKKKK.......',
    ],
    attack: [
      '................................................',
      '................................................',
      '................................................',
      '.........................KKKKKKKKKKK............',
      '........................KMMMMMMMMMuuK...........',
      '......................KKMMAGGGGGAuxxxK..........',
      '............K...K..K.KMMGGGGggggGGGSMMK.........',
      '...........KbK.KbKKbKMMGGgggggggggddAAMKK.......',
      '..........KbBbKbBbbBbnMMdddggggddGGGAGGduK......',
      '.........KbBBBbBBBBBbnMMMMMdddddGGgddGguxxK.....',
      '........KbBBBBBBBBBbbbnMMMMMMMMMMddnnnnnSK......',
      '.......KbBBMMMBBBbbbbenMMMMMMMMMAAnaaaannK......',
      '.......KMMMAAAMBbbbbeenAAAMAAAAAAnaaaaannnK.....',
      '......KMMAAAAAAMbbbeeennAAAAAAAAnaaaaaannnK.....',
      '.....KMMMMMMMAAAAbbeeenMnAAAAAAnaaaaaaannnK.....',
      '.....KMnnnnnnnAAAAMAeenAMnAAAAnaaaaaaannnnK.....',
      '.....KMAnnHKnAAAAMMAaenAAnnAAnaaaaaaannnanK.....',
      '....KMMAAAnnAAAAAAMAAanAAnnAAnaaaaaaannaanK.....',
      '...KMMAAAAAAAAAAAAaAaanAAnnnnaaaaaaannnaanK.....',
      '..KMMAAAAAAAAAAAAAAaaanAAnnnaaaaaaannnaaanK.....',
      '.KMMAAAAnAAAAAAAAAAaannAnnnaaaaaaannnaaaanK.....',
      '.KMAAAAnnaAAAAAAAAAaannnnnaaaaaaannnaaaannK.....',
      '.KnAAAnnKKKKKKKKAAaannnnnaaaaaaannnaaaaanK......',
      '..KnnnKKSrrrrrrSKAaannnnaaaaaaannnaaaaaanK......',
      '...KKKKKrrRRRrrrKAaannnnaaaaannnnaaaaaannK......',
      '.....KMKSrrrrrSKAaannnMMnaaannnnaaaaaaanK.......',
      '.....KMAKKKKKKKAAaannAAAnnnnnnaaaaaaaaanK.......',
      '......KnaaaaaaaaannnnAAAnnnnnaaaaaaaaannK.......',
      '.......KKKKKKKKKKnnnAAAnnnnaaaaaaaaaaanK........',
      '...............KeennnnnnnaaaaaaaaaaaaanKK.......',
      '..............KeebBnnnnneeeeSLeeeeeeeeeeeK......',
      '.............KeebBBxBnBBBBBBsBBBBBBBBbbeK.......',
      '............KeebBBxsBBBBBBBBBBBBBBBBBbeeK.......',
      '..........KKeebBBxKsbbbBBBBbBbBBBbbbbbeK........',
      '.........KebebBBxKKeeeebBBbbeebBbbeeebenK.......',
      '........KebbBBBxK.KeKMAsbbbeeKsbbeeaaeenK.......',
      '.......KebbbBBxK...KMMAAsbeeK.KseeaaaaannK......',
      '.KK..KKebbBBBBxK....KMAAAeenK..KeaaaaaanK.......',
      'KSsKKebbbBBBBxK....KMMAAAAnK....KaaaaaannK......',
      '.KK.KbBBBBBBxK......KMAAAAnK.....KaaaaanK.......',
      '...KebBBBBBxK......KMMAAAAnK.....KaaaaannK......',
      '...KbbbBBBxK.....KKKKMAAAAnKK.KKKKaaaaanK.......',
      '....KBeeBBxxK...KMMMMMMMMMMMnKaaaaaaaaaanK......',
      '.....KBBxxxGK...KMAAAAAAAAAAnKaaaaaaaaaanK......',
      '......KxKKgSsKKKMMAAAAAAAAAAnnaaaaaaaaaanK......',
      '....KKgK..KKKSsKMAAAAAAAAAAAnnaaaaaaaaaanK......',
      '...KggGK.....KKKSnSnSnnnnnnnnnnLnLnnnnnnnK......',
      '....KKK.........KKKKKKKKKKKKKKKKKKKKKKKKK.......',
    ],
  },
};
