import type { SpriteDef } from '../sprite';

export const VAMPIRE_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    N: 'night',
    a: 'darkSlate',
    A: 'slate',
    L: 'lightGray',
    W: 'white',
    M: 'gray',
    H: 'hotRed',
    R: 'red',
    r: 'darkRed',
    P: 'plum',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '.....................KK.........',
      '.............KKKK..KKNNK........',
      '............KNNNNKKNRrNK........',
      '...........KNNaaNNNRRrNK........',
      '..........KNNaNNNNRRrNK.........',
      '..........KLLNLLNNRRrNK.........',
      '..........KLHLHMNNRRrNK.........',
      '..........KLLLLMMNRRrNK.........',
      '..........KWrWLMMNRrNK..........',
      '..........KLLLMMNNRrNK..........',
      '.........KNRRrMMNRRrNNK.........',
      '........KNNRRWWWRPPrNNK.........',
      '.......KNNaNRWRPPPPrNNK.........',
      '.......KNaNNRWWPPPPrNNNK........',
      '......KNaLLMNWPPPPrrNNNK........',
      '......KNLLLLMNPPPPrNrNNK........',
      '......KNWNWLRaNPPPrNrNNK........',
      '......KNaNNRNNaNNNNNrrNNK.......',
      '.....KNaNNNRaNNNaNNNNrrNNK......',
      '.....KNaNNRNNNNNaNNNNrrNNK......',
      '.....KNaNNRaNNNNNaNNNNrrNK......',
      '....KNaNNRNNNNNNNaNNNNrrNNK.....',
      '....KNaNRaNNNNNNNNaNNNNrrNK.....',
      '....KNNNRNNaaNNaaNNNNNNNrNK.....',
      '.....KKKKKKaaKKKaaKKKKKKKK......',
      '..........KaaK.KaaK.............',
      '..........KaaK.KaAK.............',
      '.........KNNNKKNNNK.............',
      '..........KKK..KKK..............',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '..................KK............',
      '...........KKKK..KNNK...........',
      '..........KNNNNKKNRNK...........',
      '.........KNNaaNNNRrNK...........',
      '........KNNaNNNNRRrNK......KK...',
      '........KLLNLLNNRRrNK.....KNNK..',
      '........KLHLHMNNRRrNK....KNRrNK.',
      '........KLLLLMMNRRrNK...KNRRrNK.',
      '........KWrWLMMNRrNK...KNRRRrNK.',
      '........KrrrLMNNRrNK..KNRrRRrNK.',
      '.KKKK....KWLMMNRRrNNKKNRRrRRrNK.',
      'KWLLLKKKKKNMMNRRrNNNNNRRrRRRrNK.',
      '.KKMLLWaaNNRWWWRPPrNRRRrRRRRrNK.',
      'KWLLLMWaaaNRRWRPPPPrRRrRRRRRrNK.',
      '.KKWMKKNNNNRWWPPPPPrRRrRRRRrrNK.',
      '...KK..KNNNNRWPPPPrNRrRRRRRrrNK.',
      '.......KNaNNNRPPPPrNRrRRRRrrrNK.',
      '.......KNaNNNNPPPPrNRrRRRrrrrNK.',
      '......KNaNNNNNNNNNNNrRRRrrrNNK..',
      '......KNNNNaaaNNNNNNrRRrrrNKK...',
      '.......KNNaaaaaNaaNNrRrrrNK.....',
      '.......KaaaKKKKaaaNNNrrNKK......',
      '......KaaaK....KaaaNNrNK........',
      '......KaaK......KaaNNKK.........',
      '.....KaaK........KaaNK..........',
      '.....KaaK.........KaaK..........',
      '....KNNNK.........KaaNK.........',
      '....KNNNNK.........KNNNK........',
      '.....KKKK...........KKK.........',
      '................................',
    ],
  },
};
