import type { SpriteDef } from '../sprite';

export const WARLOCK_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    E: 'sand',
    F: 'tan',
    r: 'darkRed',
    R: 'red',
    P: 'deepBrown',
    S: 'skin',
    s: 'skinShade',
    Q: 'hotRed',
    G: 'gold',
    O: 'orange',
    Y: 'yellow',
    W: 'white',
    b: 'deepBrown',
  },
  frames: {
    idle: [
      '........K....K..................',
      '.......KEK..KEK.................',
      '........KEK.KFK.................',
      '.........KEKKKK.................',
      '..........KRrrrKK...............',
      '..........KRrrrrrK..............',
      '.........KRrrPSSSSK.............',
      '.........KRrrPSQSSK.............',
      '.........KRrrPSSSSSK............',
      '.........KRrrPsSSsK.............',
      '..........KRrrPPPK..............',
      '..........KRrrrPPK...K..........',
      '.........KKRrrrPPK..KRK.........',
      '........KRrrrrrrPrPKRORK........',
      '........KRrrrrrrPrrPOYOK........',
      '........KRrrrrrrPKrrGOK.........',
      '.......KRrrrrrrrrPK.SS..........',
      '.......KRrrrrrrrPPK.............',
      '.......KRrrPrrrrPPK.............',
      '.......KRRrPrrrrPPK.............',
      '......KRRrrPPPPrrPPK............',
      '......KRRrrPPPPrrPPK............',
      '......KRRrrPPPPrrPPK............',
      '......KRRrrPPPPrrPPK............',
      '......KRRrrPPPPrPPPK............',
      '.....KRRrrrPPPPrrPPPK...........',
      '.....KRRrrrPPPPrrPPPK...........',
      '.....KGGGGGGGGGGGGGGK...........',
      '.......KKKbbKKKbbKKK............',
      '.........KbbK.KbbK..............',
      '.........KKKK.KKKK..............',
      '................................',
    ],
    attack: [
      '........K....K..................',
      '.......KEK..KEK.................',
      '........KEK.KFK.................',
      '.........KEKKKK.................',
      '..........KRrrrKK...............',
      '..........KRrrrrrK..............',
      '.........KRrrPSSSSK.............',
      '.........KRrrPSQSSK.............',
      '.........KRrrPSSSSSK............',
      '.........KRrrPsSSsK.............',
      '..........KRrrPPPK........K.K...',
      '..........KRrrrPPK.......KRKRK..',
      '.........KKRrrrPPK......KROROK..',
      '........KRrrrrrrPrPKKKKKKOYYORK.',
      '........KRrrrrrrPrrrrrGSSOYWYOK.',
      '........KRrrrrrrPrPPPPGssROYORK.',
      '.......KRrrrrrrrrPKKKKKK.KRORK..',
      '.......KRrrrrrrrPPK.......KKK...',
      '.......KRrrPrrrrPPK.............',
      '.......KRRrPrrrrPPK.............',
      '......KRRrrPPPPrrPPK............',
      '......KRRrrPPPPrrPPK............',
      '......KRRrrPPPPrrPPK............',
      '......KRRrrPPPPrrPPK............',
      '......KRRrrPPPPrPPPK............',
      '.....KRRrrrPPPPrrPPPK...........',
      '.....KRRrrrPPPPrrPPPK...........',
      '.....KGGGGGGGGGGGGGGK...........',
      '.......KKKbbKKKbbKKK............',
      '.........KbbK.KbbK..............',
      '.........KKKK.KKKK..............',
      '................................',
    ],
  },
};
