import type { SpriteDef } from '../sprite';

export const WOLF_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    L: 'lightGray',
    M: 'gray',
    A: 'slate',
    N: 'darkSlate',
    Y: 'yellow',
    W: 'white',
    R: 'red',
  },
  frames: {
    idle: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '.....................K..........',
      '....................KLK.........',
      '...................KLMLKK.......',
      '..................KLMMMLLK......',
      '..................KLMMMYKMKKK...',
      '.................KLMMMMMMMMMMK..',
      '.................KLMMMMMMAAAAK..',
      '..............KKKKMMMMMMAAKKK...',
      '...KKKKKKKKKKKLLLLMMMMMAAK......',
      '..KLLMMLLLLLLLMMMMMMMMMAAK......',
      '.KLMAKLMMMMMMMMMMMMMMMMAAAK.....',
      '.KLMAKLMMMMMMMMMMMMMMMAAAK......',
      '.KMMAKLMMMMMMMMMMMMMMAAAAK......',
      '..KMAKMAAAMMMMMMMMMMAAAAK.......',
      '..KAAKMAKAAAAAAAAAAAAKAAK.......',
      '...KKKMAKAAKKKKKKMAKKKAAK.......',
      '.....KMAKAAK....KMAK.KAAK.......',
      '.....KMAKAAK....KMAK.KAAK.......',
      '.....KNNKNNK....KNNK.KNNK.......',
      '......KK.KK......KK...KK........',
      '................................',
    ],
    attack: [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '......................K.........',
      '.....................KLK........',
      '....................KLMLKK......',
      '...................KLMMMLLK.....',
      '...................KLMMMYKMKKK..',
      '..................KLMMMMMMMMMMK.',
      '..............KKKKKLMMMWRRRRKK..',
      '..KKKKKKKKKKKKLLLLLLMMMWAAAAK...',
      '.KLLLMMLLLLLLLMMMMMMMMMAAKKK....',
      'KLMAKKLMMMMMMMMMMMMMMMMAAAK.....',
      '.KKK.KLMMMMMMMMMMMMMMMAAAAK.....',
      '.....KLMMMMMMMMMMMMMMAAAAK......',
      '....KKMAAAMMMMMMMMMMAAAAK.......',
      '...KMMAKKAAAAAAAAAAAAKKAAK......',
      '..KMAKK.KAAKKKKKKKMAK..KAAK.....',
      '.KMAK...KAAK......KMAK..KAAK....',
      '.KMAK...KAAK......KMAK..KAAK....',
      '.KNNK...KNNK......KNNK..KNNK....',
      '..KK.....KK........KK....KK.....',
      '................................',
    ],
  },
};
