import type { SpriteDef } from '../sprite';

export const WYVERN_SPRITE: SpriteDef = {
  width: 32,
  height: 32,
  legend: {
    K: 'black',
    D: 'midGreen',
    d: 'darkGreen',
    C: 'green',
    n: 'deepTeal',
    L: 'sand',
    Y: 'yellow',
    W: 'white',
    R: 'red',
    r: 'darkRed',
    P: 'magenta',
    p: 'plum',
  },
  frames: {
    idle: [
      '................K.......KKKKKK..',
      '...........KK..KWKKKKKKKCCCCCCK.',
      '....KKKKKKKLLK.KDDCCCCCCdddddK..',
      '..KKdDDDDLLKK..KDDCCCdddddKKK...',
      '.KdDDDDDDDDdK..KDDCddCCCddKKK...',
      'KdDDDYKDDDDdK..KDDdCddddCCCddK..',
      'KCnDDDDDDDDDdKKDDdddCddddddCCdK.',
      'KnWnWnWnDDDDdKKDDddddCdddddddCK.',
      '.KLLLLLLdDDDdKKDDdddddCdddKKKK..',
      '..KKdddddDDDdKKDDddddddCdK...K..',
      '....KKKdLDDDDdDDdddddddCdK..KPK.',
      '......KdLDDDDdDDddddddddCdKKPPPK',
      '......KdLLDDDdDDdddddddddCKKpDpK',
      '......KdLLDDDDdDddddddKKKK.KdDK.',
      '......KdLLLDDDDDDDdddDDDdK.KdDK.',
      '.....KdDLLLLDDDDDDDDDDDDDdKdDdK.',
      '.....KdDLLLLLDDDDDDDDDDDDDdDdK..',
      '......KdLLLLLDDDDDDDDDDDDDDDDdK.',
      '.......KdLLLLDDDDDdDDDDDddddKK..',
      '........KKKKKKKKKKdDDDDDDddKK...',
      '..................KKddDDDDDDdK..',
      '....................KKdddDDDDdK.',
      '......................KKKWdWdWK.',
      '.........................KKKKK..',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
    attack: [
      '................K.......KKKKKK..',
      '...............KWKKKKKKKCCCCCCK.',
      '............KK.KDDCCCCCCdddddK..',
      '.....KKKKKKKLLKKDDCCCdddddKKK...',
      '...KKdDDDDLLKK.KDDCddCCCddKKK...',
      '.KKdDDDDDDDDdK.KDDdCddddCCCddK..',
      'KdDDDDYKDDDDdKKDDdddCddddddCCdK.',
      'KCnDDDDDDDDDdKKDDddddCdddddddCK.',
      '.KWnWnWdDDDDdKKDDdddddCdddKKKK..',
      '..KKKRRRRdDDdKKDDddddddCdK...K..',
      '.KKrRRRRRdDDDdDDdddddddCdK..KPK.',
      'KWnWnWLLLdDDDdDDddddddddCdKKPPPK',
      '.KLLLLLLdLDDDdDDdddddddddCKKpDpK',
      '..KKKKKdLLDDDDdDddddddKKKK.KdDK.',
      '......KdLLLDDDDDDDdddDDDdK.KdDK.',
      '.....KdDLLLLDDDDDDDDDDDDDdKdDdK.',
      '.....KdDLLLLLDDDDDDDDDDDDDdDdK..',
      '......KdLLLLLDDDDDDDDDDDDDDDDdK.',
      '.......KdLLLLDDDDDdDDDDDddddKK..',
      '........KKKKKKKKKKdDDDDDDddKK...',
      '..................KKddDDDDDDdK..',
      '....................KKdddDDDDdK.',
      '......................KKKWdWdWK.',
      '.........................KKKKK..',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  },
};
